### ISSUE TITLE
Implement a new flashing progress widget

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#1095]
Depends on https://github.com/resin-io/etcher/issues/1094

<img width="300" alt="screenshot 2017-02-10 12 30 23" src="https://cloud.githubusercontent.com/assets/2192773/22834781/b7c3db6c-ef8c-11e6-89d8-3f8a78c55568.png">

<img width="308" alt="screenshot 2017-02-10 12 06 20" src="https://cloud.githubusercontent.com/assets/2192773/22834185/b96ee3c8-ef8a-11e6-931b-814166386698.png">

The color of each dot represents the portion of the drive that has been written, validated, the parts that failed, etc.

Since the amount of dots seem to be static (e.g: it doesn't depend on the image/drive size), I believe this problem can be elegantly solved by a well crafted SVG representing the circle. We can style each dot separately using simply CSS.

**Comment by jhermsmeier** [comment]
Connects to https://github.com/resin-io/etcher/issues/778

**Comment by jviotti** [comment]
Closing stale issues
