### ISSUE TITLE
Attempt to detect incomplete images

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#1115]
Some images might not be complete (e.g: the download stops halfway through). We could implement the following heuristics to determine if the image is complete or not:

- Inspect the partition table and ensure every position referenced there exists
- If the image contains a GPT, the GPT is also duplicated at the end of the file. Check that it exists at the end as well

 If we detect the image is incomplete, we should present an error/warning to the user.

**Comment by jviotti** [comment]
Maybe @jhermsmeier has other ideas as well?

**Comment by lurch** [comment]
As mentioned elsewhere, until I see evidence to the contrary, I still suspect all images will be an exact multiple of 512 bytes... ;-)

**Comment by jviotti** [comment]
Fair enough, but if the image download stopped in the middle, then the changes are suddenly way higher.

**Comment by lurch** [comment]
OTOH, I suspect _most_ people will download images as a compressed file (`.zip`, `.xz`, etc.) in which case I believe the archive won't even open if "the download stopped in the middle" ?

**Comment by jviotti** [comment]
Maybe. The module we found to unzip while streaming ignores the zip integrity warnings altogether in order to be able to work. Who knows what we will encounter :)

**Comment by lurch** [comment]
I guess streaming images will mean that we won't be able to apply these heuristics until after we've already streamed the whole file.

**Comment by jviotti** [comment]
Closing stale issues
