### ISSUE TITLE
Add dfu support

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#170]
This feature would allow Etcher to flash DFU devices, like the Intel Edison. The task would be to create a brand new NPM module, named something like etcher-dfu, which implements DFU support in a cross platform way.

Challenges:
- Make it work in a cross platform way.
- Make it work without external dependencies.
- Make it work when being packaged inside an ASAR archive.

The final module should expose a function that returns an EventEmitter instance which emits stdout and stderr in real time. Some stdin support might be required depending on the implementation, which should preferably be handled by the module itself instead of prompting the user if possible.

This module can be implemented using external tools like dfu-util as long as the user is not required to install such tool himself (it's bundled in the package instead).

Native addons may be fine here, but only if really necessary.

**Comment by lurch** [comment]
I wonder if this would be stretching Etcher too far outside of its "core mission"?

**Comment by alexandrosm** [comment]
Not at all! This is actually part of our to-do list as we add more "IoT
device" functionality. If you're interested in helping get Etcher there,
I'm sure @jviotti would be more than happy to point you in the right
direction.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by jviotti** [comment]
Consider that the main focus of Etcher is flashing IoT devices. If you
look at it from that perspective, dfu makes a lot of sense.

On Thu, Sep 29, 2016 at 05:37:47AM -0700, Andrew Scheller wrote:
> I wonder if this would be stretching Etcher too far outside of its "core mission"?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/issues/170#issuecomment-250453860

-- 
Juan Cruz Viotti
Software Engineer

**Comment by lurch** [comment]
Ah, fair enough. I was coming from the Raspberry Pi world, where Etcher was being pitched as a cross-platform image-writing utility :-)

**Comment by jviotti** [comment]
Check this awesome WebUSB dfu example: https://github.com/devanlai/webdfu/

**Comment by dragon788** [comment]
Dfu support would also potentially open up the world of custom keyboards based on the Teensy or other AVR chips? I believe we can use DFU utils to flash the ErgoDox EZ and/or the ErgoDox Infinity if not using the Teensy application.

**Comment by jviotti** [comment]
Closing stale issues
