### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by ayrat555** [balena-io/etcher#2083]
Etcher installer is downloaded very slowly

**Comment by Avaray** [comment]
Bumping because it's really annoying.
Download speed is about 160 kB/s... so you need to wait about 10 minutes to download Etcher.
You should make mirrors.

**Comment by lurch** [comment]
Are you sure this isn't a problem with your ISP? I just downloaded it at over 3 MB/s.

**Comment by Tiedemate** [comment]
Today I could download with decent speed (I had tried unsuccessfully for about a week). Can probably be closed again...

**Comment by Avaray** [comment]
In my case that was ISP. I switched to VPN (Dutch server) and I had full download speed. I have really good 100 MBit connection and I have problems only with downloading Ether. Weird. It seems my ISP don't like Etcher :P

**Comment by lurch** [comment]
...or AWS?

**Comment by Serjaru** [comment]
Very slow! Idiotism!! Make mirrors! idiots

**Comment by lurch** [comment]
Do the links here work any better?
https://github.com/balena-io/etcher/releases

**Comment by bjoernhohe** [comment]
Download speed is basically none existent - the 8 GB Image loads faster than the few MB for etcher

**Comment by deelite** [comment]
Why not using torrent? My machine's ready to serve!

**Comment by saqib-ahmed** [comment]
I'm having the same issue. Download speed is really slow.

**Comment by thundron** [comment]
It's not something that is on our hands, the releases are distributed through GitHub, and depending on the region they might be slower/faster. Locking
