### ISSUE TITLE
Fix command escaping on Windows

### ISSUE THREAD

**Issue by jhermsmeier** [balena-io/etcher#2176]
Connects To: #2172 
See [MSDN Blog: Everyone quotes command line arguments the wrong way](https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/)

**Comment by lurch** [comment]
In case it helps, see also my comments in #1376 and #1395

**Comment by jhermsmeier** [comment]
Ref https://github.com/resin-io/etcher/issues/1399, https://github.com/resin-io/etcher/issues/1398, https://github.com/resin-io/etcher/issues/1394
