### ISSUE TITLE
USB drive with macOS sierra not detected

### ISSUE THREAD

**Issue by seenickcode** [balena-io/etcher#2188]
- Etcher version: 1.3.1
- Operating system and architecture: OSX 10.13.2 High Sierra, 64bit
- Image flashed:  elementaryos-0.4.1-stable.20180214.iso
- Do you see any meaningful error information in the DevTools: No

Hi there, I'm using the OSX boot loader isn't detecting my USB drive that Etcher flashed. 

I tried using Etcher's "Unsafe mode" as well, no luck.

Also, the drive shows "Removable Media:          Removable", not "Fixed":

```
diskutil info /dev/disk2
   Device Identifier:        disk2
   Device Node:              /dev/disk2
   Whole:                    Yes
   Part of Whole:            disk2
   Device / Media Name:      Innostor

   Volume Name:              Not applicable (no file system)
   Mounted:                  Not applicable (no file system)
   File System:              None

   Content (IOContent):      FDisk_partition_scheme
   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 USB
   SMART Status:             Not Supported

   Disk Size:                15.8 GB (15806234624 Bytes) (exactly 30871552 512-Byte-Units)
   Device Block Size:        512 Bytes

   Read-Only Media:          No
   Read-Only Volume:         Not applicable (no file system)

   Device Location:          External
   Removable Media:          Removable
   Media Removal:            Software-Activated

   Virtual:                  No
   OS 9 Drivers:             No
   Low Level Format:         Not supported
```

Any ideas?

**Comment by jhermsmeier** [comment]
Hey hey; I'm a bit confused as to what role the OS boot loader is playing – is the issue that you've flashed elementary to the USB drive, and the Mac won't boot from it? Or is Etcher not showing the USB drive in the "Select drive" list?
