### ISSUE TITLE
Check lock

### ISSUE THREAD

**Issue by ageevp** [balena-io/etcher#2222]
- 1.3.1
-   dfgd
- No!

Please add a check if device is locked by another   program after pressing FLASH button.

**Comment by jhermsmeier** [comment]
"dfgd" & "No!" is not helpful information.
What kind of lock do you mean? Windows' FSCTL lock? Which operating system are you on? What is the error you get, and how is it displayed to you?

**Comment by ageevp** [comment]
10:03, 21 апреля 2018 г., Jonas Hermsmeier <notifications@github.com>:"dfgd" & "No!" is not helpful information.
What kind of lock do you mean? Windows' FSCTL lock? Which operating system are you on? What is the error you get, and how is it displayed to you?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




Windows 10Conflict with Hard disk low level format toolNo errors.No notification?????Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail
