### ISSUE TITLE
Measure flashing speed on development kit

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#2231]
Lets document the results and compare them to the goal (33 MB/s on every drive during multi-writes).

**Comment by konmouz** [comment]
Adjust for new architecture (new goal is 45MB/s writing speed)

**Comment by konmouz** [comment]
Test proposal:

- Test 01: Flash 16 cards measuring speed and temperature to benchmark performance
- Test 02: Loop test01 and make sure performance is consistent over time
