### ISSUE TITLE
Add an image selection dropdown to pick from selecting a file or duplicating a drive

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#2239]
![screen 01-03](https://user-images.githubusercontent.com/2192773/39320823-446f04c6-4953-11e8-8761-1237b9307424.png)

**Comment by jviotti** [comment]
I just noticed we need to sort out what to present if, in the case of Etcher Pro, the source drive has multiple partitions. Should we make the user pick? cc @konmouz

**Comment by jviotti** [comment]
This is blocked by https://github.com/resin-io/etcher/issues/2230

**Comment by jviotti** [comment]
When selecting one of these options, there should be a label that says "Remove" that makes the user go back to the initial screen.

**Comment by jviotti** [comment]
If the user selects a drive to clone, then the UI shouldn't allow the user to select that same drive as the target.

**Comment by konmouz** [comment]
@jviotti, We should add image streaming as a third option.

<img width="1601" alt="screenshot 2019-02-26 at 11 34 59" src="https://user-images.githubusercontent.com/15323961/53410041-918abe00-39ba-11e9-9661-caa43ae201b0.png">

**Comment by konmouz** [comment]
New screen: https://zpl.io/bAvWJMq
