### ISSUE TITLE
Implement multi-writes success/error screens

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#2240]
We want to keep the banner, so we must figure out a way to display the banner while showing meaningful summaries.

The logic is the following:

- If at least one drive was successful, then the user goes to the success screen
- If all drives fail, you get the usual error modal with the "Retry" action

**Let's make sure this is touch friendly**

![screen 04-01-2](https://user-images.githubusercontent.com/2192773/39320522-65897ad4-4952-11e8-878c-5ff139ed635b.png)

Here the user should see more details when tapping the summaries area.

**Comment by jhermsmeier** [comment]
ping @konmouz ^

**Comment by konmouz** [comment]
@Shou, what do you think?

![screen 04-02](https://user-images.githubusercontent.com/15323961/40112667-ade6adae-58fe-11e8-861a-ccfc4a32d760.jpg)

**Comment by konmouz** [comment]
maybe the CTA can be 'Re-flash failed targets'

**Comment by Shou** [comment]
Thanks!

**Comment by lurch** [comment]
Something that's just occurred to me - when the "Failed drives" modal is being displayed on the EtcherPro, perhaps it'd be more useful to display drive-paths like "USB slot 3" rather than "/dev/sdf" ?

**Comment by dazz100** [comment]
Hi
I am trying to use several 4-slot SD card readers.  If a SD card fails, Etcher doesn't tell me which slot the failed card is in.
Based on practical experience, I think the best solution is to give the user all of the information available to Etcher about the slot.  That would include both  /dev/sdf    usb 01:slot 02 etc.

**Comment by konmouz** [comment]
EP success screen - no banner screen - @konmouz

**Comment by konmouz** [comment]
<img width="1216" alt="Screenshot 2019-06-24 at 16 30 11" src="https://user-images.githubusercontent.com/15323961/60031868-66308b00-969d-11e9-82bf-cc269d59471d.png">
<img width="1212" alt="Screenshot 2019-06-24 at 16 30 18" src="https://user-images.githubusercontent.com/15323961/60031869-66308b00-969d-11e9-90da-9ef17464b301.png">
<img width="1218" alt="Screenshot 2019-06-24 at 16 30 28" src="https://user-images.githubusercontent.com/15323961/60031870-66308b00-969d-11e9-9427-b8e368fefddd.png">

https://zpl.io/ankLE6J -- @thundron new screens

**Comment by dazz100** [comment]
Hi 
Received copies of the screen shot by email without comment. 
I like the screenshot layouts but
I am using one of these :  [USB3.0 to 4xSD Card Reader](http://www.chinagallop.com/products_detail/productId=752.html).  
I don't know what device you are testing on so I can't tell from the screenshots if your code will identify the slot of a failed flash within a single multi-card writer/reader.  If it can, that would be great.
If it can't, then this code is doesn't help anyone with a multi-card reader/writer.

I am more than happy to do testing if that will help.

**Comment by zvin** [comment]
@dazz100 there's no way to identify a port number on a multi-card reader.
We may have a physical path (like `/dev/disk/by-path/pci-0000:00:14.0-usb-0:3:1.0-scsi-0:0:0:0` or `/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.5/1-1.5:1.0` on Linux for example) but that won't help you identifying the physical port.
