### ISSUE TITLE
Make settings page a modal

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#2248]
![screen 04-01](https://user-images.githubusercontent.com/2192773/39320581-856cb226-4952-11e8-946a-cf01807ecb71.png)

**Make sure this is touch friendly**

Of course, the Wifi and UUID buttons will not be there for desktop Etcher

**Comment by konmouz** [comment]
For this implementation we need to move all settings to a page, not a modal - redesign screens - @konmouz

**Comment by konmouz** [comment]
<img width="1215" alt="Screenshot 2019-06-24 at 16 28 15" src="https://user-images.githubusercontent.com/15323961/60031675-15b92d80-969d-11e9-8736-32aad269ff0a.png">

https://zpl.io/ankLE6J -- @thundron new design
