### ISSUE TITLE
Use LEDs to mirror the state of the Etcher Pro

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#2250]
- When inserting the drive, the corresponding LED turns on
- When removing the drive, the corresponding LED turns off
- When validating the drive, the corresponding LED should blink with purple
- When a failure occurs, the corresponding LED should be red
- When the flash is successful, the corresponding LED should be green
- When writing, the corresponding LED should be blinking with orange

**Comment by lurch** [comment]
What colour should the LED be when a drive is inserted but before you've started writing to it?

**Comment by jviotti** [comment]
Not sure yet. I left unspecified since its probably not worth to raise a discussion for it yet (and be updated really easily). We can use any color not used by the other states, like blue.

**Comment by lurch** [comment]
I wonder if it'd be worth updating parts of the GUI, so that the colours used in the GUI match the colours used on the LEDs? (which might make it much more obvious what the different LED colours mean?)

**Comment by curcuz** [comment]
@jhermsmeier please issue a WIP PR for this

**Comment by konmouz** [comment]
- Write the library to control the LEDs
- Define the LEDs behaviour according to EP function

**Comment by konmouz** [comment]
Prompt to plug source: 1st LED > blue - breathing
Source plugged: 1st LED > blue - on
Prompt to plug target: 2nd to 16th LED > white - breathing (or all LEDs in case of an external source)
Target plugged: LED of the plugged drive > white - on
Flashing > green - blinking
Validating > purple - blinking
Successfully flashed > green - on
Failed drives > red - on

**Comment by lurch** [comment]
Relates to #3046 ?

**Comment by konmouz** [comment]
Diagram: https://docs.google.com/drawings/d/12n5z5qhw6eriHyaDEnId2Jhgjt95wBn4PXR1pkqCORQ/edit?usp=sharing

![EP LED states](https://user-images.githubusercontent.com/15323961/82209313-fa828c80-9904-11ea-8619-9bd2db02aca4.jpg)
