### ISSUE TITLE
Implement a UI to interact with the Wifi container

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#2252]
Obviously depends on https://github.com/resin-io/etcher/issues/2251.

This will be a separate wifi configuration panel, probably accessible through a wifi icon on the top right corner of the app (like the settings cog). This is Etcher Pro specific, so it should not be enabled for desktop Etcher.

**Comment by jviotti** [comment]
We're pending some designs for this. @konmouz

**Comment by konmouz** [comment]
@jviotti @Shou let me know what you think of these screens:

![screen 05-01 copy 2](https://user-images.githubusercontent.com/15323961/39518073-b0da1934-4df9-11e8-9a08-fca39c9d0dfd.jpg)
![screen 05-01 copy 3](https://user-images.githubusercontent.com/15323961/39518075-b2aff8a0-4df9-11e8-9e54-32208a6a8952.jpg)
![screen 05-01 copy 4](https://user-images.githubusercontent.com/15323961/39518080-b45455d4-4df9-11e8-8801-e052fd9e7976.jpg)

**Comment by jviotti** [comment]
@konmouz What does "Advanced Configuration" show? Overall looks good to me. @majorz Are all the features in those screens supported by wifi connect?

**Comment by konmouz** [comment]
@jviotti, this is just in case we want to include further or advanced options. We can remove it if this is irrelevant.

**Comment by curcuz** [comment]
@jviotti @konmouz I guess advanced stuff would be static IP config, or anything non DHCP standard
