### ISSUE TITLE
Implement an embedded on-screen keyboard on the Wifi configuration container

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#2253]
This depends on both https://github.com/resin-io/etcher/issues/2252 and https://github.com/resin-io/etcher/issues/2251.

There are two ways to go with this:

- There are GNU/Linux keyboard modules we can install and setup on the wifi container. We never did this before, but apparently what's out there is tricky to setup and hard to theme (and looks terrible)
- Implement the keyboard on the front-end

We can take a peek at what Linux has to offer, otherwise https://www.npmjs.com/package/virtual-keyboard seems to be a great front-end module.

**Comment by lurch** [comment]
Will users be able to plug a real USB keyboard into Etcher Pro, should they choose to do so?

**Comment by jviotti** [comment]
We probably don't need to worry about that for now.

**Comment by Shou** [comment]
React version of the package for convenience https://github.com/Utzel-Butzel/react-virtual-keyboard

**Comment by konmouz** [comment]
@thundron, is this done? Can you please post a screenshot of the new keyboard?

**Comment by thundron** [comment]
@konmouz It's not merged yet, I still need to move the input (keyboard's ready though)
