### ISSUE TITLE
Add "no drag and drop" mode environment variable

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#2284]
When enabled, we should disable the dashed squares around the image selection step that hints that the user can drag and drop a file.

![screen 01-01](https://user-images.githubusercontent.com/2192773/39321241-74b8adde-4954-11e8-8a0b-b570edfcf104.png)

**Comment by Shou** [comment]
Removing this from the MVP as this isn't relevant now, we don't have a drag-and-drop field yet.

**Comment by jviotti** [comment]
Closing stale issues
