### ISSUE TITLE
Add device UUID to the settings page when running as a Resin application

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#2287]
![screen 04-01](https://user-images.githubusercontent.com/2192773/39321337-bf09dbce-4954-11e8-9aa2-da5eb21573c7.png)

**Comment by konmouz** [comment]
Updated screens:

![screen 05-01](https://user-images.githubusercontent.com/15323961/39517952-5609f934-4df9-11e8-8fc6-052be2d5dd79.jpg)
![screen 05-01 copy](https://user-images.githubusercontent.com/15323961/39517957-57f528b8-4df9-11e8-9a74-87dbaea56a15.jpg)

**Comment by konmouz** [comment]
Implementation - @thundron 

(connected to )

**Comment by thundron** [comment]
implemented in https://github.com/balena-io/etcher/pull/3628 , you can close!

**Comment by jviotti** [comment]
Closing stale issues
