### ISSUE TITLE
command diskutil list -plist returned without data

### ISSUE THREAD

**Issue by varunkalyan** [balena-io/etcher#2471]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by varunkalyan** [comment]
![etcher error](https://user-images.githubusercontent.com/37028967/45256457-829c4a80-b34b-11e8-8911-25090430910b.png)

**Comment by varunkalyan** [comment]
Unable to flash a USB and see the above error

**Comment by sidouglas** [comment]
Me too

**Comment by thundron** [comment]
Which balenaEtcher version are you using @varunkalyan @sidouglas ? Did you try that command by itself to check its output? `diskutil list -plist`

**Comment by thundron** [comment]
Also, when are you seeing this error? During image selection, drive selection or when clicking the flash button? Also please fill in the information above on the issue template

**Comment by zvin** [comment]
Etcher no longer uses diskutil since v1.5.0
