### ISSUE TITLE
W:GPG error debian

### ISSUE THREAD

**Issue by apolitech** [balena-io/etcher#2487]
- **Operating system and architecture:18.04.1 / 64-bit
There is a problem with https://dl.bintray.com/resin-io/debian
W:GPG error: https://dl.bintray.com/resin-io/debian stable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379CE192D401AB61, E:The repository 'https://dl.bintray.com/resin-io/debian stable Release' is not signed.

**Comment by thundron** [comment]
Hi there,
Did you follow instructions here https://github.com/resin-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64 ?
