### ISSUE TITLE
Add "skip" link below validation progress bar

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#250]
Add am underlined "skip" link in validation stage under the progress bar. Once the "skip" link is pressed, it should then ask: "Skip once?", "Skip always?".

**Comment by jviotti** [comment]
![screen shot 2016-04-12 at 10 23 41 am](https://cloud.githubusercontent.com/assets/2192773/14461002/a6b6ad56-008e-11e6-8a85-048bc18b1c1c.png)

**Comment by jviotti** [comment]
![screen shot 2016-04-12 at 10 14 45 am](https://cloud.githubusercontent.com/assets/2192773/14461007/b02ead70-008e-11e6-8ac7-9acd0f73ee7a.png)

**Comment by jviotti** [comment]
As discussed, this can be simply reduced to "Skip".

**Comment by jviotti** [comment]
We're pending designs for the modal that appears after the user clicks "Skip", which asks him if he wants to skip just once, or always.

**Comment by Josephvb10** [comment]
3 years and still not implemented such a simple feature?

**Comment by jeffersonest** [comment]
> 
> 
> 3 years and still not implemented such a simple feature?

4 Years***

**Comment by whatbh** [comment]
5 years

**Comment by jviotti** [comment]
Closing stale issues
