### ISSUE TITLE
Expected a number

### ISSUE THREAD

**Issue by freekvh** [balena-io/etcher#2508]
- **etcher-electron-1.4.5-x86_64.AppImage** 
- *KDE Neon 18.04:** 
- **none** 
- **Do you see any meaningful error information in the DevTools?** 

Etcher is unresponsive and can't be used.

The Error:

TypeError: Expected a number
    at prettyBytes (/tmp/.mount_OSOdsn/usr/bin/resources/app.asar/node_modules/pretty-bytes/pretty-bytes.js:18:10)
    at module.exports.getDrivesSubtitle (file:///tmp/.mount_OSOdsn/usr/bin/resources/app.asar/generated/gui.js:7477:14)
    at fn (eval at compile (/tmp/.mount_OSOdsn/usr/bin/resources/app.asar/node_modules/angular/angular.js:15351:15), <anonymous>:4:182)
    at expressionInputWatch (/tmp/.mount_OSOdsn/usr/bin/resources/app.asar/node_modules/angular/angular.js:16352:31)
    at Scope.$digest (/tmp/.mount_OSOdsn/usr/bin/resources/app.asar/node_modules/angular/angular.js:18002:34)
    at Scope.$apply (/tmp/.mount_OSOdsn/usr/bin/resources/app.asar/node_modules/angular/angular.js:18280:24)
    at /tmp/.mount_OSOdsn/usr/bin/resources/app.asar/node_modules/angular/angular.js:20127:36
    at completeOutstandingRequest (/tmp/.mount_OSOdsn/usr/bin/resources/app.asar/node_modules/angular/angular.js:6274:10)
    at /tmp/.mount_OSOdsn/usr/bin/resources/app.asar/node_modules/angular/angular.js:6554:7
    at wrapped (/tmp/.mount_OSOdsn/usr/bin/resources/app.asar/node_modules/raven-js/dist/raven.js:444:21)

**Comment by freekvh** [comment]
It could have something to do with opening Etcher twice very quickly after each other (KDE does not require double clicks for opening... took some getting used to). It did work normally the last 2 times I tried.

**Comment by Jacalz** [comment]
I am getting the exact same error every time I start Etcher on Solus after upgrading to the latest version, see picture below:
![image](https://user-images.githubusercontent.com/25466657/47265351-23734d80-d527-11e8-9d29-419097edf3a5.png)

**Comment by Kuoi** [comment]
I did get this too , but rightclicked on the file , > preferences > set all rights to 'read and write' and enabled "make it run as a program" (translated from dutch :-) ) 
Then on opening i answered "no" on the question for the desktop file , and it opened without the warning.
I don't know what did the actual trick to let it open fine ,but this way it works like it should

**Comment by lukasmedia** [comment]
Same on Ubuntu 16:

![image](https://user-images.githubusercontent.com/11347254/47920569-a5159480-deb2-11e8-8940-7b444638bf20.png)

**Comment by thundron** [comment]
Seems to be related to read/write permissions given to etcher *before* running it.
Did you all try this procedure https://github.com/balena-io/etcher/issues/2508#issuecomment-432415759 ?

**Comment by ivangsm** [comment]
The same thing happened to me after I installed the `.desktop` file when I ran the `.appimage` file. The way I fixed it was to delete the file `appimagekit-Etcher.desktop` which is in the path:  `~/.local/share/applications`

**Comment by matejmosko** [comment]
> Seems to be related to read/write permissions given to etcher _before_ running it.
> Did you all try this procedure [#2508 (comment)](https://github.com/balena-io/etcher/issues/2508#issuecomment-432415759) ?

Doesn't work for me.

**Comment by thundron** [comment]
We chased down the issue and it seems to go all the way back to nodejs itself, which has been fixed in new nodejs versions.
We're working on updating electron used by etcher so we'll include the newer nodejs versions and fixes

**Comment by Jacalz** [comment]
I was using the Solus version and the thing is that they are building with NodeJS version 8.  In what version can the bug be found? Or will this simple get fixed with electron getting updated? @thundron

**Comment by dragon788** [comment]
I only ran into this issue when attempting to "launch/open" the AppImage via the quicksearch `Super` menu in Gnome (Ubuntu 18.04). If I instead opened "Files" and ran the AppImage from Nautilus (Gnome file explorer) it ran correctly.

**Comment by Xosmond** [comment]
I just chaged the permissions on the Iso file and the application downloaded to 777 and it worked, i think you can debug with the permissions and get the problem.
