### ISSUE TITLE
Etch Flash Error

### ISSUE THREAD

**Issue by SakeBacsu** [balena-io/etcher#2516]
Etcher version: 1.4.5
Operating system and architecture: Windows 10  32-bit OS, x64-based processor
Image flashed: Kanux-Beta-v4.1.0-Hopper-stretch-rc-2018-10-01_00-54-noobs.img
Do you see any meaningful error information in the DevTools? Yes
[Kano_img_flashERROR.log](https://github.com/resin-io/etcher/files/2508482/Kano_img_flashERROR.log)

I am trying to build a learning station for my kids, but for some reason I am running into this issue while flashing. I have used Etcher to flash before and haven't run into any issues like this one. Any advice as to what I may need to do get past this problem? Thank you and you are appreciated.

**Comment by lurch** [comment]
Appears to be the same problem as #2518 ?

**Comment by thundron** [comment]
Which is the same as https://github.com/balena-io/etcher/issues/2508, closing

**Comment by thundron** [comment]
Nevermind, it's a different error though it's been resolved in ac068f353acc53de5ed4edd7b06f5791307abb40
