### ISSUE TITLE
README links are broken

### ISSUE THREAD

**Issue by milkmiruku** [balena-io/etcher#2523]
Too simple for a PR methinks. Possibly there are other references in the repo, but I haven't checked.

(Edit: original title was "README needs an s/balena-io/resin-io/g")

**Comment by milkmiruku** [comment]
Ah, I see from the recent history that things are going the other way! Well, README links are still broken, however they will be fixed :)

**Comment by thundron** [comment]
They should be ok now :) thanks for the patience!

**Comment by lurch** [comment]
Should the Travis and Appveyor badges be removed?
