### ISSUE TITLE
corupt SD card or etcher not able to write to card

### ISSUE THREAD

**Issue by peter-65** [balena-io/etcher#2548]
- 1.4.4
- win 10 64 bit pro
- raspbian 2018-11-13 
- No 

problem with formatting or corrupt SD HC card - (also sent to SD format programmers)

Hi (this is being copied to etcher also via GitHub)

I have a 8Gb Samsung micro sd HC card C6 format. 

This card has been used on a raspberry pi (NOBS) formatted card. Last produced on or about 25/01/18 00:12. 

This has 4 partitions when shown on windows 10, 3 have to be formatted by win 10 as they are none windows format. 

The Sd formatter v 5.0.01 will not format to a single partition.  Ready to be used again for the raspberry pie. 

When using the formatter the following is displayed - 

![image](https://user-images.githubusercontent.com/12758431/48765270-b54ab380-eca9-11e8-9500-4b3813e8d17e.png)

 

The formatter dose not reformat. The pie (fat32) partition is not over written, this occurs for each of the drives all complete with  

 
![image](https://user-images.githubusercontent.com/12758431/48765289-c0054880-eca9-11e8-8fa3-feacf9c1ca44.png)

Any ideas or methods to get this card reformatted. 

Etcher gives error when trying to load a new image. 
![image](https://user-images.githubusercontent.com/12758431/48765310-cd223780-eca9-11e8-946d-3eda859914df.png)

 
![image](https://user-images.githubusercontent.com/12758431/48765336-d8756300-eca9-11e8-88d5-6230acf5067e.png)

**Comment by thundron** [comment]
Hi @peter-65 
Did you try giving Etcher admin permissions before running it?

**Comment by peter-65** [comment]
Yes etcher works on other cards without problem. I also ran it as an administrator from the program file.by right click "run as admin" to get these errors.
