### ISSUE TITLE
2 versions installed after updating.

### ISSUE THREAD

**Issue by thunderpants** [balena-io/etcher#2554]
- **Etcher version:*1.47* 
- **Operating system and architecture:*win10.x64LTSC -INTEL CPU* 

I had v1.46 installed in appdata Etcher folder
I updated to v.1.47 and it made a new folder in appdata balena-etcher.
I now have 2 desktop shortcuts ,one called Etcher and one called balena-etcher .

**Comment by thundron** [comment]
That's because we changed the application name to `balena-etcher` so you'll need to uninstall the old one manually unfortunately, you'll find more details [here](https://www.balena.io/blog/resin-io-changes-name-to-balena-releases-open-source-edition/)
