### ISSUE TITLE
Etcher Crashes on Launch

### ISSUE THREAD

**Issue by steve018** [balena-io/etcher#2555]
1.4.8
Ubuntu 18.10 64-bit minimal installation
Using .appimage

Whenever I try to open Etcher, I get this error:
`/tmp/.mount_NshRWX/usr/bin/balena-etcher-electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory`

**Comment by ParthOSDev** [comment]
Hi,

I suppose you should try sudo apt-get install -y libgconf-2-4 and then try running Etcher again. It solved my problem!

Regards,
?
________________________________

**Comment by steve018** [comment]
That did not fix the issue for me.

**Comment by thundron** [comment]
It's strange though, we ship the AppImage with all the needed libraries, including libgconf-2-4.
Did you try installing that @ParthOSDev ?

**Comment by ParthOSDev** [comment]
Well it’s not my issue, it is Steve’s and it fixed my problem.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by thundron** [comment]
@steve018 Could you please try installing `libgtk2.0-0:i386` and try running etcher again? It is shipped with the AppImage like the other dependencies, but some users still have issues with them on newer Ubuntu versions

**Comment by thundron** [comment]
@mbt45 Did you already try with one/both of the packages suggested above?

**Comment by thundron** [comment]
@mbt45 That doesn't sound related to this issue though (this is specific to ubuntu), you can search your error in the other issues and/or open a new one if you can't find it :)

**Comment by steve018** [comment]
After installing `libgconf-2-4` and removing it and installing it a second time, the issue is fixed (Didn't work the first time for some reason).

**Comment by steve018** [comment]
@ParthOSDev @thundron 
The issue was resolved with a `sudo apt-get install libgconf-2-4 libgtk2.0-common`

**Comment by lurch** [comment]
See also https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#runtime-gnulinux-dependencies
