### ISSUE TITLE
why there is no compilation instructions? I want to build an armhf linux binary

### ISSUE THREAD

**Issue by Askmewho** [balena-io/etcher#2565]
thanks for the develop! 
:)

**Comment by lurch** [comment]
There is, see https://github.com/balena-io/etcher/blob/master/docs/CONTRIBUTING.md#developing

**Comment by Askmewho** [comment]
ok, let me explaint. I am not a software developer, but there is a necesity in the rpi community to avoid command line burning of .img's)
I follow all the steps of https://github.com/balena-io/etcher/blob/master/docs/CONTRIBUTING.md#developing
I make etcher run on raspberry (with "npm start"), at least I burn an .img and it boot perfect on my pi3.
I dont know how to pack this, because npm pack give me a .tar than cant run on another pi (at least I fail).
1) btw, how could I run etcher outside npm? the all folder its to heavy to be practical to use or share.
2) how I could create a package to share to my friends?

thanks!

**Comment by lurch** [comment]
Okay, so it seems you're actually asking for an Etcher package for Raspberry Pi 3? That's quite different to asking for compilation instructions :wink: 

You might want to look at #1992

**Comment by Askmewho** [comment]
well! if there is no binary, the most common way to run on a new platform its going on compilation hahahaa so, I will continue the topic on that one. at least it works like I said, but I need to pack this thing.

**Comment by Askmewho** [comment]
https://drive.google.com/file/d/1tbt4aQ2EGAKR6u4AhOVyXF9bfXJaDUhn/view?usp=sharing

I get something, but electron-builder didnt achieve a .deb because of architecture problem (fmp-linux its an x86 package and it doesnt have an arm one).
