### ISSUE TITLE
Worked twice no issues then failure

### ISSUE THREAD

**Issue by Hitchhyker** [balena-io/etcher#2566]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

Worked fine then on 3rd and subsequent use just failures.

copy and verifies ok the comes up with disk unreadable and will not load

**Comment by thundron** [comment]
Could you please fill the above info? Thanks in advance

**Comment by thundron** [comment]
@Hitchhyker Would you mind sharing the error log or a screenshot of the error?

**Comment by thundron** [comment]
@Hitchhyker Would you mind sharing the error log or a screenshot of the error?
