### ISSUE TITLE
Invalid executable name or typo in the documentation

### ISSUE THREAD

**Issue by zrzka** [balena-io/etcher#2581]
Check [this forum post](https://forums.balena.io/t/etcher-cli-binary-is-named-balena-etcher/4659).

* Releases do contain `balena-etcher` binary
* [Documentation](https://www.balena.io/etcher/cli/#Running) says `etcher`

**Comment by thundron** [comment]
@zrzka Fixed the docs in https://github.com/balena-io/etcher/issues/2540. Closing and reaching back to the user on the forum
