### ISSUE TITLE
Coulndn't clean the drive, spawn diskpart ENOENT

### ISSUE THREAD

**Issue by chezyann** [balena-io/etcher#2585]
- Etcher version: 1.4.8
- Operating system and architecture: Windows 7 - 64 bits - Core i3
- Image flashed: https://drive.google.com/open?id=1adkYTjiy6W0DrBD4Iiiy3VVKD3FY8bk3

![erreur etcher](https://user-images.githubusercontent.com/21059985/50167382-564c7e80-02e9-11e9-9cd8-067feca3a19e.JPG)

**Comment by chezyann** [comment]
Another one reported this error in a closed issue thread : 
https://github.com/balena-io/etcher/issues/1991#issuecomment-441358234

**Comment by thundron** [comment]
It's a known issue that will be resolved once we bump Electron version since the fix relies in later nodejs versions. Closing for now (we already have a PR in the works for it)

**Comment by chezyann** [comment]
BalenaEtcher 1.5.0 (jumped to Electron 3) does not solve the problem. Can you reopen this issue ?

![capture d ecran 2019-03-01 a 12 27 43](https://user-images.githubusercontent.com/21059985/53635464-81bee400-3c1d-11e9-9a27-7daf12fbbe65.png)
