### ISSUE TITLE
Remove Old Version of Etcher

### ISSUE THREAD

**Issue by fleamour** [balena-io/etcher#2591]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by fleamour** [comment]
Hi

I am running openSUSE Tumbleweed & need to remove older version. I think Electron apps only have a desktop shortcut menu linked to executable? I was wondering the correct way to uninstall older app?

**Comment by fleamour** [comment]
Delete entry under;

/home/user/.local/share/applications

**Comment by lurch** [comment]
Duplicate of #451 ?
