### ISSUE TITLE
gpg: keyserver receive failed: No data

### ISSUE THREAD

**Issue by djkerya** [balena-io/etcher#2600]
sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61
Executing: /tmp/apt-key-gpghome.3wzLSL1SLd/gpg.1.sh --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61
gpg: keyserver receive failed: No data

**Comment by lurch** [comment]
@djkerya Please don't spam multiple issues :wink: 
I left a comment here: https://github.com/balena-io/etcher/issues/1786#issuecomment-453067610

**Comment by thundron** [comment]
@djkerya Please follow the guide [here](https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64) to add the correct GPG key signature. Closing
