### ISSUE TITLE
Etcher has been separate partition on USB drive without make it bootable

### ISSUE THREAD

**Issue by KittipatGH** [balena-io/etcher#2605]
- **Etcher version: 1.4.9** 
- **Operating system and architecture: Windows 10 Pro  x64** 
- **Image flashed: Bootable Chrome OS** 
- **Do you see any meaningful error information in the DevTools? : No, I don't see anything about error I see the result after making bootable drive with Etcher**

<u>Normally after I used other tools to make bootable drive, after finished I'll see the nice results that's it containing with selected image file, but Etcher is not, don't just separate partition on my drive but not containing anything that's I needed, Please look this picture in Removable drive with 7.21 GB can be use, I won't use this until It have been fixed with other bugs as others created report issues.</u>

![image](https://user-images.githubusercontent.com/40468195/51249510-13ec8f00-19c6-11e9-968c-e26f0af3c7ef.png)

**Comment by lurch** [comment]
That picture looks totally normal - Etcher is just a "raw" flasher tool (until #413 gets implemented), and so the sizes and layouts of the partitions you get after flashing an image to your drive are determined entirely by whatever is contained in the image.

**Comment by thundron** [comment]
Please refer to [this](https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#why-is-my-drive-not-bootable) for bootable drives. Etcher doesn't support that unless the image itself is specifically made to do so. Closing
