### ISSUE TITLE
etcher sending info to internet

### ISSUE THREAD

**Issue by alfredoivan** [balena-io/etcher#2608]
- **Etcher version: 1.4.4** 
- **Operating system and architecture: Linux** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

Etcher sends or downloads information regarding the version and if there are updates, right?
Is there a way to disable the traffic of information from Etcher to internet?
Ideally it should be as simple as a checkbox "offline usage" or so.

**Comment by thundron** [comment]
@alfredoivan The anonymous usage analytics are opt-out, you can disable them in the settings whenever you want. Be sure to check the icon in top right of Etcher
