### ISSUE TITLE
False Device failure message at the end of a burn operation 

### ISSUE THREAD

**Issue by Rickll110** [balena-io/etcher#2609]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by Rickll110** [comment]
I used this app to burn an install; .ISO image to a USB flash drive so I could create a USB stick to install a LINUX partition on my system for a dual platform system on the same device.  I had used an LINUX .ISO image I downloaded from a vendor. I followed the instructions as provided by the vendor to create an install USB stick with this version of LINUX. The burn operation went fine until the last message indicated that there was a device fail message in the session log after the operation completed.  I checked the session log but there was no conspicuous error message indicating that there was an error or failure during the operation. Upon closer inspection of the error message detail, the summary said there was a read/write failure of the physical media when the operation was occurring.  After re-running the burn process several times and each time the same error message at the end of each session was the same. device fail.  However at no time when the operation was running was an error or alert message produced to the operator as I sat in attendance with each burn session,  

I ran the boot procedure with the USB stick I created and the LINUX .iso image mounted and installed using the menu provided by the vendor.  So even though there was a device fail this seems inconsequential since the install stick executed without errors.  As this was consistent  with at least 3 different USB flash drives \, I did not attribute the device failure to a defective target media. 

So in this case the Etcher app generated a false error message at the end of the burn operation of am .iso image.  The only explai

**Comment by lurch** [comment]
By "false device failure" do you mean that you got a verification failure? A screenshot of the error message or (even better) a copy'n'paste of the DevTools log would be useful. What OS are you running Etcher on?

On some OSes it can happen that Etcher successfully writes the image to the target drive, but then the host OS (annoyingly) auto-mounts one of the partitions on the new image and modifies some meta-data (e.g. mount date) on the partition, which means that when Etcher reads back the data from the target drive, it's no longer byte-for-byte identical with the original image, and so verification fails.

**Comment by thundron** [comment]
@Rickll110 Sounds like what @lurch explained thoroughly. You can disable the verification step in the settings (although I wouldn't recommend it of course) if that's the error you're talking about and everything turns out to work just fine when you use the device you flashed.
