### ISSUE TITLE
Failure adding etcher repository

### ISSUE THREAD

**Issue by mfbalin** [balena-io/etcher#2612]
- **Operating system and architecture:** Ubuntu 18.04 

Failure when trying to add etcher repository to apt.

Command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
Output: gpg: keyserver receive failed: Server indicated a failure

**Comment by lurch** [comment]
Maybe a temporary glitch? Working for me.

**Comment by mfbalin** [comment]
Is there any other way of signing the repository?

**Comment by thundron** [comment]
@mfbalin You can try using other mirrors if `keyserver.ubuntu.com` doesn't work for you, here's a list with [some of them](https://www.rossde.com/PGP/pgp_keyserv.html#pubserv)

**Comment by camilojm27** [comment]
Do not work  for me neither i am using deepin (debian based)
![deepinscreenshot_20190203161008](https://user-images.githubusercontent.com/14319090/52182761-3eb05300-27ce-11e9-8b83-c1eeb90562b2.png)

**Comment by thundron** [comment]
@camilojm27 Did you try the other keyservers listed at https://www.rossde.com/PGP/pgp_keyserv.html#pubserv by chance?

**Comment by brianleePTL** [comment]
I'm still getting this error. I have tried the other keyservers and still get the same thing. Does anyone have a verified keyserver that they know works?

**Comment by tilsammans** [comment]
This is a DNS issue. To fix it, make sure you are using a DNS resolver that doesn't filter.

e.g. in `/etc/resolv.conf` have one of these:
```
nameserver 8.8.8.8 # Google public DNS
nameserver 1.1.1.1 # or Cloudflare
```

**Comment by thundron** [comment]
Thanks @tilsammans , closing this one as it's (unfortunately) unrelated to Etcher itself
