### ISSUE TITLE
Unexpected token x in JSON at position 5100

### ISSUE THREAD

**Issue by epsilonrt** [balena-io/etcher#2614]
- Etcher Gui 1.4.9 
- Ubuntu Xenial amd64

![capture d ecran de 2019-01-28 21-55-58](https://user-images.githubusercontent.com/13524484/51865877-dbdf3780-2347-11e9-9acd-8cba09d233fe.png)
This window always appears at startup.

**Comment by thundron** [comment]
@epsilonrt Could you please paste here the output of `lsblk --all --json --paths --output-all`?

**Comment by epsilonrt** [comment]
Hi,
`
lsblk --all --json --paths --output-all
{
   "blockdevices": [
      {"name": "/dev/sda", "kname": "/dev/sda", "maj:min": "8:0", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": "ST500LM000-1EJ16", "serial": "W76570S8", "size": "465,8G", "state": "running", "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "4096", "opt-io": "0", "phy-sec": "4096", "log-sec": "512", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "disk", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": "0x5000c5008a6ce52c", "rand": "1", "pkname": null, "hctl": "0:0:0:0", "tran": "sata", "subsystems": "block:scsi:pci", "rev": "SM36", "vendor": "ATA     ",
         "children": [
            {"name": "/dev/sda1", "kname": "/dev/sda1", "maj:min": "8:1", "fstype": "ntfs", "mountpoint": null, "label": "Win7x64", "uuid": "D0A43186A4316FD8", "parttype": "0x7", "partlabel": null, "partuuid": "849eafe5-01", "partflags": "0x80", "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "138G", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "4096", "opt-io": "0", "phy-sec": "4096", "log-sec": "512", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": "0x5000c5008a6ce52c", "rand": "1", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null},
            {"name": "/dev/sda3", "kname": "/dev/sda3", "maj:min": "8:3", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": "0x5", "partlabel": null, "partuuid": "849eafe5-03", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "1K", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "1024", "min-io": "4096", "opt-io": "0", "phy-sec": "4096", "log-sec": "512", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": "0x5000c5008a6ce52c", "rand": "1", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null},
            {"name": "/dev/sda4", "kname": "/dev/sda4", "maj:min": "8:4", "fstype": "ext4", "mountpoint": "/", "label": null, "uuid": "60682565-e840-4cce-a7ec-e16c4e0dfdc0", "parttype": "0x83", "partlabel": null, "partuuid": "849eafe5-04", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "100,5G", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "4096", "opt-io": "0", "phy-sec": "4096", "log-sec": "512", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": "0x5000c5008a6ce52c", "rand": "1", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null},
            {"name": "/dev/sda5", "kname": "/dev/sda5", "maj:min": "8:5", "fstype": "ext4", "mountpoint": null, "label": null, "uuid": "17910e87-41b9-4e09-9489-d49a3eb64038", "parttype": "0x83", "partlabel": null, "partuuid": "849eafe5-05", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "47,7G", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "4096", "opt-io": "0", "phy-sec": "4096", "log-sec": "512", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": "0x5000c5008a6ce52c", "rand": "1", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null}
         ]
      },
      {"name": "/dev/sdb", "kname": "/dev/sdb", "maj:min": "8:16", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": "ST2000LM003 HN-M", "serial": "S377J9AG900162", "size": "1,8T", "state": "running", "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "4096", "opt-io": "0", "phy-sec": "4096", "log-sec": "512", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "disk", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": "0x50004cf210bb739d", "rand": "1", "pkname": null, "hctl": "1:0:0:0", "tran": "sata", "subsystems": "block:scsi:pci", "rev": "0001", "vendor": "ATA     ",
         "children": [
            {"name": "/dev/sdb1", "kname": "/dev/sdb1", "maj:min": "8:17", "fstype": "ntfs", "mountpoint": "/media/Donn\xc3\xa9es", "label": "Donn\xc3\xa9es", "uuid": "ECFA6CAEBEC71B44", "parttype": "0x7", "partlabel": null, "partuuid": "c3a816a5-01", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "1000G", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "4096", "opt-io": "0", "phy-sec": "4096", "log-sec": "512", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": "0x50004cf210bb739d", "rand": "1", "pkname": "/dev/sdb", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null},
            {"name": "/dev/sdb3", "kname": "/dev/sdb3", "maj:min": "8:19", "fstype": "ext4", "mountpoint": null, "label": null, "uuid": "06ef50ae-22c1-49b9-8367-38473d2bf773", "parttype": "0x83", "partlabel": null, "partuuid": "c3a816a5-03", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "50G", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "4096", "opt-io": "0", "phy-sec": "4096", "log-sec": "512", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": "0x50004cf210bb739d", "rand": "1", "pkname": "/dev/sdb", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null},
            {"name": "/dev/sdb4", "kname": "/dev/sdb4", "maj:min": "8:20", "fstype": "ext4", "mountpoint": "/home", "label": null, "uuid": "3febfbbf-7478-4313-95f0-a8668b5e6420", "parttype": "0x83", "partlabel": null, "partuuid": "c3a816a5-04", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "813G", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "4096", "opt-io": "0", "phy-sec": "4096", "log-sec": "512", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": "0x50004cf210bb739d", "rand": "1", "pkname": "/dev/sdb", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null}
         ]
      },
      {"name": "/dev/sdc", "kname": "/dev/sdc", "maj:min": "8:32", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "1", "model": "My Book 1170    ", "serial": "WD-WMC1T3874821", "size": "2,7T", "state": "running", "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "4096", "opt-io": "0", "phy-sec": "4096", "log-sec": "4096", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "disk", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": "0x50014ee658f1e68c", "rand": "1", "pkname": null, "hctl": "7:0:0:0", "tran": "usb", "subsystems": "block:scsi:usb:pci", "rev": "1042", "vendor": "WD      ",
         "children": [
            {"name": "/dev/sdc2", "kname": "/dev/sdc2", "maj:min": "8:34", "fstype": "ext4", "mountpoint": "/media/pascal/MyBookExt4", "label": "MyBookExt4", "uuid": "61b1df0e-8956-4251-98e3-82445f704328", "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "1", "model": null, "serial": null, "size": "2,7T", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "4096", "opt-io": "0", "phy-sec": "4096", "log-sec": "4096", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": "0x50014ee658f1e68c", "rand": "1", "pkname": "/dev/sdc", "hctl": null, "tran": null, "subsystems": "block:scsi:usb:pci", "rev": null, "vendor": null}
         ]
      },
      {"name": "/dev/sr0", "kname": "/dev/sr0", "maj:min": "11:0", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "1", "hotplug": "1", "model": "BD-CMB UJ160    ", "serial": "WN63_063975", "size": "1024M", "state": "running", "owner": "root", "group": "cdrom", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "deadline", "rq-size": "128", "type": "rom", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": null, "rand": "1", "pkname": null, "hctl": "2:0:0:0", "tran": "sata", "subsystems": "block:scsi:pci", "rev": "1.00", "vendor": "MATSHITA"},
      {"name": "/dev/loop0", "kname": "/dev/loop0", "maj:min": "7:0", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "20G", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": null, "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4K", "disc-max": "4G", "disc-zero": "1", "wsame": "0B", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null,
         "children": [
            {"name": "/dev/mapper/tmp.Tdd5rZQsV6", "kname": "/dev/dm-0", "maj:min": "252:0", "fstype": "ntfs", "mountpoint": "/home/pascal/Perso", "label": null, "uuid": "A2AAF6BAAAF68A55", "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "20G", "state": "running", "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": null, "rq-size": "128", "type": "crypt", "disc-aln": "0", "disc-gran": "4K", "disc-max": "4G", "disc-zero": "0", "wsame": "0B", "wwn": null, "rand": "0", "pkname": "/dev/loop0", "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null}
         ]
      },
      {"name": "/dev/loop1", "kname": "/dev/loop1", "maj:min": "7:1", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": null, "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": null, "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null},
      {"name": "/dev/loop2", "kname": "/dev/loop2", "maj:min": "7:2", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": null, "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": null, "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null},
      {"name": "/dev/loop3", "kname": "/dev/loop3", "maj:min": "7:3", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": null, "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": null, "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null},
      {"name": "/dev/loop4", "kname": "/dev/loop4", "maj:min": "7:4", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": null, "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": null, "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null},
      {"name": "/dev/loop5", "kname": "/dev/loop5", "maj:min": "7:5", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": null, "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": null, "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null},
      {"name": "/dev/loop6", "kname": "/dev/loop6", "maj:min": "7:6", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": null, "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": null, "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null},
      {"name": "/dev/loop7", "kname": "/dev/loop7", "maj:min": "7:7", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": null, "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": null, "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "0B", "disc-max": "0B", "disc-zero": "0", "wsame": "0B", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null}
   ]
}

`

**Comment by lurch** [comment]
FWIW the text above gets parsed fine by Python's JSON pasrser, but https://jsonlint.com/ complains about `"mountpoint": "/media/Donn\xc3\xa9es"` - looks like a classic Unicode escaping / unescaping issue.

**Comment by epsilonrt** [comment]
Hi,
Bingo, thanks a lot !
I changed the mount point name and partition label to remove the UTF-8 character and it works.

**Comment by lurch** [comment]
...although this is probably still a bug (in `drivelist`) that needs fixing, in case anyone else runs into it in future?

**Comment by zvin** [comment]
Blame it on lsblk https://github.com/karelzak/util-linux/issues/330
