### ISSUE TITLE
Etcher lowers capacity of sd cards when flashing retropie

### ISSUE THREAD

**Issue by gizardo** [balena-io/etcher#2620]
- **E1.49:** 
- **Mac 10.12.6:** 
- **Retropie:** 

Ever since etcher prompted me to upgrade to "balena etcher" a haven't been able to successfully flash any versions of retropie to an sd card. This includes the newest version of retropie, recalbox, or custom images. It always looks like it flashed successfully, and I can see the contents of retropie on my micro sd card. However, I see nothing when I pop my SD cards into my raspberry pi. Additionally, the sd cards read think they are 55 mb. They think they are 55 mb on multiple macs and a windows computer, so I don't think the reader is the issue. This issue occurs on a 32 gig samsung micro sd card and 16 gig sandisk cards from Amazon, one of which was brand new. The issue also occurs on multiple sd card adapters. I have figured out how to return the sd cards to their original capacity, but it just happens again when I flash a retropie image. Does anyone know what is going on? Thanks in advance.

**Comment by gizardo** [comment]
Before I waste anyone's time, I think the issue is within my pi.

**Comment by lurch** [comment]
> Additionally, the sd cards read think they are 55 mb. They think they are 55 mb on multiple macs and a windows computer, so I don't think the reader is the issue. This issue occurs on a 32 gig samsung micro sd card and 16 gig sandisk cards from Amazon, one of which was brand new.

That's just the way that partitioning on Raspberry Pi SD cards works - see https://github.com/raspberrypi/noobs/wiki/Standalone-partitioning-explained for more detailed info. Windows and Mac computers are only able to read the FAT format partition.

**Comment by mliakos** [comment]
Have the same issue using a 32 GB samsung card and balena.

**Comment by lurch** [comment]
@mliakos I suspect that if you want a more detailed response, you'll have to provide a more detailed description of your problem? :man_shrugging:
