### ISSUE TITLE
etcher to debian main repo 

### ISSUE THREAD

**Issue by sumanrajan** [balena-io/etcher#2623]
First of all i want to thank the devs for such a cool software 
Secondly i want to see etcher in debian main repos 
If i could get some help i would like to volunter to it as well 
Hope the dev team will look into it 
Thankyou

**Comment by lurch** [comment]
The Etcher team already provide a `.deb` file ( https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64 ) - I think to get it in the "debian main repos" is an issue for Debian, rather than an issue for Balena? :man_shrugging:

**Comment by camilojm27** [comment]
> The Etcher team already provide a `.deb` file ( https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64 ) - I think to get it in the "debian main repos" is an issue for Debian, rather than an issue for Balena? man_shrugging
> 
> EDIT: To clarify, the opinions are my own and I'm not involved in any way with Balena! (or Debian)

The problem is the gpt signature, the server is down, i have to use an appImagen

**Comment by lurch** [comment]
> The problem is the gpt signature, the server is down

@thundron provided a (link to a) list of keyserver mirrors in #2612

**Comment by thundron** [comment]
Going to integrate that list in the readme soon™
