### ISSUE TITLE
Unable to flash RPi CM3+ 16GB compute module

### ISSUE THREAD

**Issue by SparcV** [balena-io/etcher#2624]
- **Etcher version: 1.4.9
- **Operating system and architecture: Windows 10 Pro x64
- **Image flashed: rasbian

I'm unable to flash the New Raspberry Pi CM3+ module. It just sits at Initializing device.

Works with rpiboot after updated to the latest version.

**Comment by thundron** [comment]
@SparcV A new version of etcher with added support for CM3+ is in the works, ETA hopefully next week!

**Comment by zvin** [comment]
This should work correctly on v1.5.19+
