### ISSUE TITLE
no module found "../generated/etcher"

### ISSUE THREAD

**Issue by an0nym0u5-404** [balena-io/etcher#2627]
- **Etcher version:** 
- **Operating system and architecture:** ubuntu 16.04
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

 Hi I am new to electron and etcher, and I have tried to build the tool from source by **npm install** for installing dependencies. However, when I **npm start** which basically calls **electron lib/start.js**, it gives me the error of missing module "../generated/etcher" which is caused by the require(...) statement in start.js. Therefore, I am just wondering what is the correct way of building the tool from source and if I have missed anything? Please let me know and thank you!

**Comment by thundron** [comment]
@an0nym0u5-404 Before that, you need to run `make webpack` or if you are trying to develop and want to continuously build the UI, `npm run watch` watches changes to javascript files and updates the generated bundle accordingly

**Comment by an0nym0u5-404** [comment]
@thundron thank you so much!

**Comment by lurch** [comment]
You can't use "npm install" with Etcher, you need to read through https://github.com/balena-io/etcher/blob/master/docs/CONTRIBUTING.md#developing :wink:  (although I've no idea if those instructions are still up to date)
