### ISSUE TITLE
1.4.9 installer for OSX downloads the 1.0.0-beta.8

### ISSUE THREAD

**Issue by TomCos** [balena-io/etcher#2632]
Title says it all.  The download link looks right, but maybe the wrong app was packaged into the .dmg?

**Comment by lurch** [comment]
According to https://github.com/balena-io/etcher/blob/master/CHANGELOG.md v1.4.9 was released towards the end of last year. I don't have a Mac myself, but it'd be kinda surprising if you were the first person to notice this problem? :confused:

**Comment by TomCos** [comment]
Seems like a mixup on my end, sorry for the confusion.
