### ISSUE TITLE
Getting Plain Screen On Ubuntu 18.04 after following the steps given in guidelines..

### ISSUE THREAD

**Issue by shivarajnaidu** [balena-io/etcher#2633]
- **Etcher version:**  : Cloned From Latest Master
- **Operating system and architecture:**  
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

- **Do you see any meaningful error information in the DevTools?** 

![screenshot_20190215_083115](https://user-images.githubusercontent.com/12374494/52832184-70de8080-30fd-11e9-86b6-e2d48cb2de0f.png)

![image](https://user-images.githubusercontent.com/12374494/52831990-b9496e80-30fc-11e9-94c8-4970fcb62b4f.png)

**Comment by thundron** [comment]
@shivarajnaidu Did you run `make electron-develop` too?

**Comment by shivarajnaidu** [comment]
Yes @thundron .. got this error
![image](https://user-images.githubusercontent.com/12374494/52869399-94401480-316b-11e9-9843-1246447f0677.png)

**Comment by thundron** [comment]
@shivarajnaidu Run `git submodule init && git submodule update`, then retry `make electron-develop`

**Comment by shivarajnaidu** [comment]
Getting error.. for this too.. 
![image](https://user-images.githubusercontent.com/12374494/52869980-dc136b80-316c-11e9-8493-6ff27f28a768.png)

**Comment by shivarajnaidu** [comment]
Got this error.. 
![image](https://user-images.githubusercontent.com/12374494/52870302-8be8d900-316d-11e9-974e-4e8da4d440c7.png)

**Comment by shivarajnaidu** [comment]
After installing jq .. it's compiling properly

**Comment by thundron** [comment]
@shivarajnaidu Follow the guide [here](https://github.com/balena-io/etcher/blob/master/docs/CONTRIBUTING.md) to check that you have everything

**Comment by shivarajnaidu** [comment]
Sure.. I followed the same @thundron  It's working now
Thank You very much.. 

finally it gets compiled successfully ..
 I think we can add 
Run `git submodule init && git submodule update`, then retry `make electron-develop` these steps and `sudo apt install jq` command in linux section.. 
I think it will be helpful for new contributors. Please consider adding these in contribution guide. Thank You Once Again.

**Comment by thundron** [comment]
@shivarajnaidu Definitely, and remember you can always issue a PR for that as well! They are always very welcome and encouraged

**Comment by shivarajnaidu** [comment]
Sure.. I'll try to rise an PR as soon as possible.. Thank You for your kind and timely guidance @thundron  :relaxed:
