### ISSUE TITLE
AppImages link leads to a file/folder, which doesn't exist (user documentation)

### ISSUE THREAD

**Issue by zrzka** [balena-io/etcher#2652]
* Open user documentation, chapter [Deactivate desktop shortcut prompt on GNU/Linux](https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#deactivate-desktop-shortcut-prompt-on-gnulinux)
* There's AppImages link, which leads to https://github.com/balena-io/etcher/blob/master/docs/appimage

But this file/folder doesn't exist.

**Comment by lurch** [comment]
Looks like changing `[AppImages](appimage)` to `[AppImages][appimage]` would fix that?

**Comment by zrzka** [comment]
Thanks, did add to #2653.

**Comment by lurch** [comment]
I guess this can be closed :wink:
