### ISSUE TITLE
etcher can't no display 

### ISSUE THREAD

**Issue by goooglethink** [balena-io/etcher#2659]
1 years
i download this software
every people can use it 
but i just.........
![2019-02-25_13-18](https://user-images.githubusercontent.com/26277664/53315799-1b298580-3900-11e9-9da5-edf72409de74.png)

what is hapen ,........................... :(

**Comment by bartisimos** [comment]
some here - no display - no response from Development tool. 

both blank. 
Win 10 
i5 - NVidea - 8 gb
perhaps you have an idea.

**Comment by lurch** [comment]
Similar issues... in case it helps the devs track down a common problem
https://github.com/balena-io/etcher/issues/2456
https://github.com/balena-io/etcher/issues/1752
https://github.com/balena-io/etcher/issues/1031
https://github.com/balena-io/etcher/issues/2569
https://github.com/balena-io/etcher/issues/2397
https://github.com/balena-io/etcher/issues/2596
https://github.com/balena-io/etcher/issues/129

**Comment by bartisimos** [comment]
short feedback after testing more. Virus Scanner stopped the application - all centent. 
After disabling the virus scanner - evola - screen appeared.
Funny enough - downloading the file triggers as well now the antivirus - potential trojan infection.

**Comment by lurch** [comment]
Yeah, sometimes the virus scanners are a bit over-keen on flagging up Etcher, but I think it's simply because it's an executable they've not seen before #2392 #2289 #2291 #862 etc.

**Comment by edricus** [comment]
I'm on archlinux same problem and I can't disable my "virus scanner" I don't have it

**Comment by crackingthecodethomas** [comment]
Have exact same issue. Win 10 Pro. Tried clean install. Still white blank window.

**Comment by mac1494** [comment]
same issue windows 7 64bit clean installed.

**Comment by koon95** [comment]
run it on compatibility mode. that should fixed it

**Comment by rossssco** [comment]
uname -a 

```
Linux i5-dell 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
getting the same error on version 
balenaEtcher-1.5.90-x64.AppImage
(i.e diplays for a second then blank)

Version 
balenaEtcher-1.5.89-x64.AppImage
works fine.

Iv attached full logs from the dev console
[210520_etcher_error_v1.5.90.zip](https://github.com/balena-io/etcher/files/4661912/210520_etcher_error_v1.5.90.zip)

**Comment by lurch** [comment]
@rossssco see #3160 (I believe the Etcher devs are already fixing this)

**Comment by thundron** [comment]
> run it on compatibility mode. that should fixed it

I think this is the solution for the o.g. issue
Closing, and @rossssco a new release is in the way to fix yours
