### ISSUE TITLE
lingconf error on Ubuntu Budgie 18.04.2

### ISSUE THREAD

**Issue by sevku** [balena-io/etcher#2666]
- **Etcher version:** 1.49
- **Operating system and architecture:** Ubuntu Budgie 18.04.2
- **Image flashed:** none
- **Do you see any meaningful error information in the DevTools?**
/tmp/.mount_GKCigu/usr/bin/balena-etcher-electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

**Comment by lurch** [comment]
Duplicate of #2641 ?
