### ISSUE TITLE
Burn drive without completely erasing it

### ISSUE THREAD

**Issue by sako0938** [balena-io/etcher#2670]
- **Etcher version:** 
1.4.9
- **Operating system and architecture:** 
Ubuntu 18.04 AMD64
- **Image flashed:** 
Balena Image
- **Do you see any meaningful error idnformation in the DevTools?** 

I have been using etcher for burning Balena disk images onto a SSD. Is it typical behavior that it deletes the partition table of the drive prior to the image burn? Is there any way around that.

Example:
Have a SSD drive that is 120gb. At position 80-120gb I have a partition that needs to stay on the drive. I want to be able to burn the drive, and have my new fairly small balena partitions at the beginning of the drive, and keep the previous partition at the end? 

Am I understanding image burning correctly?

**Comment by lurch** [comment]
This isn't possible with Etcher, it always overwrites the MBR too, since some disk images (typically for Linux) contain multiple partitions.
You might be looking for #413 ?
