### ISSUE TITLE
Hi. Thanks for this product.

### ISSUE THREAD

**Issue by AceOfJade** [balena-io/etcher#2672]
Thanks much for this product. I'm a PHP/webdev hobbyist and just trying to install a few different linux distros as I begin to learn Linux. Currently using a Xubuntu distro on usb key and using this program to tri-stall (lol?) Linux Mint MATE to try that out too!

I just wanted to say thanks. I'm new to GitHub and not sure if this was the proper place for a thank you or not.

**Comment by shawaj** [comment]
Thanks very much @AceOfJade - will close this issue now but your kind words are very much appreciated by the team 👍
