### ISSUE TITLE
Filter out APFS containers (macOS)

### ISSUE THREAD

**Issue by zrzka** [balena-io/etcher#2678]
See ...

* https://github.com/balena-io/etcher/issues/2661#issuecomment-468643641
* https://github.com/balena-io/etcher/issues/2661#issuecomment-468662837
* https://github.com/balena-io/etcher/issues/2661#issuecomment-469262018
* https://github.com/balena-io/etcher/issues/2661#issuecomment-469269690

**Comment by zvin** [comment]
We should probably move this to the drivelist repo.

**Comment by zrzka** [comment]
Moved to https://github.com/balena-io-modules/drivelist/issues/334
