### ISSUE TITLE
can't download it in China

### ISSUE THREAD

**Issue by anjoean** [balena-io/etcher#2685]
- **Etcher version:** v1.5.0
- **Operating system and architecture:** macOS 10.14.1
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 
Hi, I am a Chinese student and very like this tool! However,I found that I can't download the file "balenaEtcher-1.5.0.dmg" , Why? it said"github-production-release-asset-2e65be.s3.amazonaws.com refused our connection request“. Thanks!

**Comment by theLMGN** [comment]
This is an issue with China's firewall blocking Amazon's AWS servers, that GitHub uses for distributing releases.

**Comment by anjoean** [comment]
OK...but thank you all the same!
