### ISSUE TITLE
source.getInnerSource(...).then(...).catch(...).finally is not a function

### ISSUE THREAD

**Issue by matmis** [balena-io/etcher#2697]
- **Etcher version: 1.5.5-1** 
- **Operating system and architecture: Antergos, intel core i7 6700HQ**
- **Image flashed: 2018-11-13-raspbian-stretch-lite.img**
- **Do you see any meaningful error information in the DevTools?:**

> /usr/lib/etcher/node_modules/resin-corvus/src/resin-corvus.js:233 {"stack":"TypeError: source.getInnerSource(...).then(...).catch(...).finally is not a function\n    at module.exports.selectImageByPath (file:///usr/lib/etcher/generated/gui.js:8862:15)\n    at file:///usr/lib/etcher/generated/gui.js:8896:15\n    at tryCatcher (/usr/lib/etcher/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/usr/lib/etcher/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/usr/lib/etcher/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/usr/lib/etcher/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/usr/lib/etcher/node_modules/bluebird/js/release/promise.js:694:18)\n    at _drainQueueStep (/usr/lib/etcher/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/usr/lib/etcher/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/usr/lib/etcher/node_modules/bluebird/js/release/async.js:147:5)\n    at Async.drainQueues (/usr/lib/etcher/node_modules/bluebird/js/release/async.js:17:14)\n    at <anonymous>","message":"source.getInnerSource(...).then(...).catch(...).finally is not a function"}

![image](https://user-images.githubusercontent.com/10931410/54639715-51d16680-4a8e-11e9-8fce-e9490b168603.png)

**Comment by exodious** [comment]
I have the same issue. Same OS and same version.

**Comment by zvin** [comment]
The package was probably using electron 1 which is not supported.
You can try using the AppImage instead.
