### ISSUE TITLE
electron2

### ISSUE THREAD

**Issue by medioman** [balena-io/etcher#2700]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

Hi,electron on aur is Flagged out-of-date on 2019-03-10 it is possible to compile etcher with electron2?
Thank
Cheers

etcher 1.5.5-2
archlinux

**Comment by lurch** [comment]
https://github.com/balena-io/etcher/blob/master/CHANGELOG.md#v150---2019-02-16 :wink:

**Comment by medioman** [comment]
Hi,I don't understand, I'm not a great expert.ThankCheers




  ----Messaggio originale----
 
 Da: notifications@github.com
 
 Data: 20-mar-2019 14.02
 
 A: "balena-io/etcher"<etcher@noreply.github.com>
 
 Cc: "medioman"<sonbello@alice.it>, "Author"<author@noreply.github.com>
 
 Ogg: Re: [balena-io/etcher] electron2 (#2700)
 

 

 
https://github.com/balena-io/etcher/blob/master/CHANGELOG.md#v150---2019-02-16
  
   ��

**Comment by medioman** [comment]
Se solo un grande coglione.Vergognati cretino fa un altro mestiere idiota.




  ----Messaggio originale----
 
 Da: notifications@github.com
 
 Data: 20-mar-2019 14.13
 
 A: "balena-io/etcher"<etcher@noreply.github.com>
 
 Cc: "medioman"<sonbello@alice.it>, "Author"<author@noreply.github.com>
 
 Ogg: Re: [balena-io/etcher] electron2 (#2700)
 

 

 
Closed #2700.

**Comment by lurch** [comment]
I was pointing out that according to the Changelog, in "v1.5.0" Etcher "Upgrade to Electron v3." - sorry for being too concise.

**Comment by lurch** [comment]
@thundron Why has **resin-ci** made so many edits to @medioman 's last comment??

**Comment by medioman** [comment]
@Lurch thanks for answering, but where do I find electron3 in archlinux?
I have a hard head.
I repeat I am not a great expert
Thank

**Comment by lurch** [comment]
I've never used Arch Linux myself, and IIRC the Etcher package for Arch was made by a 3rd party?
(I'm not directly involved with the Etcher project myself)

**Comment by mati865** [comment]
`electron2` package in Arch is old `electron 2.0` kept for compatibility, current `electron 3.1` will be replaced by [version 4.1](https://www.archlinux.org/packages/community-staging/x86_64/electron/) when it's deemed stable enough.

**Comment by zvin** [comment]
electron2 is not supported

**Comment by medioman** [comment]
Thank i remove electorn2




  ----Messaggio originale----
 
 Da: notifications@github.com
 
 Data: 3-apr-2019 19.21
 
 A: "balena-io/etcher"<etcher@noreply.github.com>
 
 Cc: "medioman"<sonbello@alice.it>, "Mention"<mention@noreply.github.com>
 
 Ogg: Re: [balena-io/etcher] electron2 (#2700)
 

 

 
Closed #2700.

**Comment by medioman** [comment]
thak.ector




  ----Messaggio originale----
 
 Da: notifications@github.com
 
 Data: 21-mar-2019 19.26
 
 A: "balena-io/etcher"<etcher@noreply.github.com>
 
 Cc: "medioman"<sonbello@alice.it>, "Mention"<mention@noreply.github.com>
 
 Ogg: Re: [balena-io/etcher] electron2 (#2700)
 

 

 
electron2 package in Arch is old electron 2.0 kept for compatibility, current electron 3.1 will be replaced by version 4.1 when it's deemed stable enough.
