### ISSUE TITLE
linux x64 v1.5.15 "not found"

### ISSUE THREAD

**Issue by NukeManDan** [balena-io/etcher#2706]
https://github.com/balena-io/etcher/releases/download/v1.5.15/balena-etcher-electron-1.5.15-linux-x64.zip

get `not found`

**Comment by lurch** [comment]
@thundron Looks like your auto-publish-to-github is publishing the raw AppImage, but not publishing the AppImage-wrapped-in-a-zip ?

**Comment by lurch** [comment]
I think this can be closed now?
