### ISSUE TITLE
Writer process ended unexpetedly

### ISSUE THREAD

**Issue by vamp111** [balena-io/etcher#2713]
I get this error when trying to write on a brand new SD, after this the card becomes unrecognizable, windows doesn't see the card, can't format it! I've tried with 2nd card, which was used many times, got the same error, now again the card is unrecognizable. Anyone had this problem ? a way to restore my SDcard ?

Etcher ver. 1.5.5 on Windows 10

**Comment by lurch** [comment]
> Anyone had this problem ?

Yeah, looks like it https://github.com/balena-io/etcher/search?q=Writer+process+ended+unexpectedly&type=Issues

**Comment by thundron** [comment]
@vamp111 Does it fail right away when trying to flash or does it stop at a certain step? Try also with the latest `1.5.19`

**Comment by vamp111** [comment]
it doesnt start writing, crashes about 3-5 sec. after I press the "flash"button. I tryed an older version as i read reccomendations and it worked just fine, also i managed to save my SD card, recovering it using an old method. Thx

**Comment by zaxhalmon** [comment]
Having this very same issue happen to two different Samsung 32GB SD Cards, rendering them useless. Using Version 1.5.19.

**Comment by vamp111** [comment]
> Having this very same issue happen to two different Samsung 32GB SD Cards, rendering them useless. Using Version 1.5.19.

follow this guide here, so you can recover your cards at least: https://www.youtube.com/watch?v=hYwjMmJ4qk0

**Comment by vamp111** [comment]
@thundron no nothing, and yet again I still dont know what happened. Anyway the recovery methods didnt worked, so I figured one by myself you can see the vid. one comment above yours ;)

**Comment by thundron** [comment]
> along with others you might already know

We're still investigating the issue, looks like it happens mostly on Windows for now

**Comment by vamp111** [comment]
@thundron this was on Windows 10, I never had issues flashing cards on Ubuntu 16.04 before
