### ISSUE TITLE
32GB images reports incorrectly but writes OK on MS Windows

### ISSUE THREAD

**Issue by DG12** [balena-io/etcher#2719]
**Etcher version:** -1.5.19
**Operating system and architecture:** MS Windows 64- 

When flashing a 5,040,031,819 .gz file which results in a 32GB SD image,
Etcher reports size of 866.89MB. 
This causes progressive's bar to advance incorrectly rapidly.
SD card is correctly written (after an unpredictably long time)

Thanks for your (otherwise) great program.

**Comment by lurch** [comment]
Duplicate of #638 ?

**Comment by DG12** [comment]
Duplicate of #638
