### ISSUE TITLE
image etched to 64gb sd card, will not boot.. same image to 32gb card works okl

### ISSUE THREAD

**Issue by sdetweil** [balena-io/etcher#2737]
- **Etcher version:** 
1.5.4
- **Operating system and architecture:** 
WIndows 10 64bit
- **Image flashed:** 
nvidia jetson nano
https://developer.nvidia.com/embedded/dlc/jetson-nano-dev-kit-sd-card-image
- **Do you see any meaningful error information in the DevTools?** 
no.. says completed ok

**Comment by sdetweil** [comment]
image is ubuntu 18.04

**Comment by thundron** [comment]
@sdetweil Probably due to this https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#why-is-my-drive-not-bootable , as mentioned there Etcher doesn't modify the image in any way; as a result, some images need some additional steps
Also look into this for more infos on bootable ubuntu isos: https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos

**Comment by lurch** [comment]
If Etcher says the writing completed okay, it sounds to me like it might be a problem with the "nvidia jetson nano" rather than a problem with Etcher? Perhaps it's not compatible with such large SD cards? :man_shrugging:

**Comment by szb512** [comment]
Have you tried reflashing the SD card with the image?

**Comment by sdetweil** [comment]
Tried 3 times. Would not boot all three. Used a 32gig card, booted 1st time

**Comment by szb512** [comment]
Does the .zip file have a .iso (disk image file)?

**Comment by sdetweil** [comment]
not iso, but img

jetson-nano-sd-r32.1-2019-03-18.img

you can download it from the link in the initial post

**Comment by szb512** [comment]
Have you tried redownloading the file?

**Comment by sdetweil** [comment]
yes, i have it without problem... unzipped and then used etcher to install the .img to the card...

32gig card boots after, 64gig card does not

**Comment by szb512** [comment]
It's probably a problem with the file, I guess it can't support 64 GB cards.

**Comment by talkingtab** [comment]
I have a jetson nano, used etcher on my mac to flash the image onto a 64G card and it was able to boot just fine.  

One thing is that I did not unzip the nano image file, just selected the zip file with etcher.

**Comment by sdetweil** [comment]
@talkingtab  thank you.. that worked!

**Comment by lurch** [comment]
How odd! :confused:

**Comment by sdetweil** [comment]
@lurch exactly!

**Comment by lurch** [comment]
@zvin or @thundron Any ideas what might explain this unusual behaviour? (just out of curiosity...)

**Comment by thundron** [comment]
Well tbh we fixed many things since v1.5.4 so you could maybe try flashing the extracted image with the recent `v1.5.33` "for science" @sdetweil @talkingtab 
I'll try to get my hands on a jetson nano to check it but this will require some more time

**Comment by talkingtab** [comment]
@thundron I will try to  run some experiments on my system. It will probably take a couple of days, but the variables I can think of are:

- macos vs windows
- v1.5.4 vs v1.5.33 vs v1.4.9
- nano vs everything else

The first two seem much more likely to me than it being a nano issue.  
My current version on the mac reports: balenaEtcher, v1.4.9, so I guess the first step is try the most recent versions.

**Comment by sdetweil** [comment]
i am using Windows 10, and etcher 1.5.24
was just offered 1.5.33 as first update

**Comment by lurch** [comment]
> is the best way to get v1.5.4. for the mac to clone the repo && build it myself?

Old releases can be found at https://github.com/balena-io/etcher/releases

> can I use etcher to go from SD => img ?

Not yet :wink: #266

**Comment by talkingtab** [comment]
I tried this on a mac on with 1.5.4 and did not have a problem. I was offered 1.5.33 as an upgrade but when I clicked on the "download" button it took me to a page that only had 1.5.4. Not sure it is worth pursuing this, at least on the mac.

**Comment by lurch** [comment]
> I was offered 1.5.33 as an upgrade but when I clicked on the "download" button it took me to a page that only had 1.5.4

See #2773

**Comment by talkingtab** [comment]
Not sure I got the release info right in some of the earlier messages. In any case I have 1.4.9, 1.5.24 and 1.5.35. I tested the nano file extracted from the zip to an .img and successfully booted the SD card on all versions.  This is on a Mac running 10.14.1
Thanks @lurch for the help getting 1.5.35.
