### ISSUE TITLE
"Error Opening image" Something went wrong while opening jetson-nano-sd-r32.1-2019-03-18.zip  Error: end of central directory record signiture not found.

### ISSUE THREAD

**Issue by bw1995** [balena-io/etcher#2743]
- **Etcher version:** 1.5.24-x64
- **Operating system and architecture:** Win10Pro 64bit
- **Image flashed:**  jetson-nano-sd-r32.1-2019-03-18.zip
![Error writing Nano image to ### SD](https://user-images.githubusercontent.com/47490574/56382861-0a014480-61de-11e9-96d5-5e7256581429.PNG)

- **Do you see any meaningful error information in the DevTools?** No

**Comment by lurch** [comment]
Are you sure the .zip file you've chosen has been downloaded correctly? Are other ZIP tools able to open it okay?

**Comment by szb512** [comment]
Have you tried 7zip?

**Comment by bw1995** [comment]
The downloaded file was corrupt. Took me five attempts to download a good file.  Then etcher worked fine.
Thanks for the follow-up.
Please close trouble ticket.
Bill

Sent from Mail for Windows 10
