### ISSUE TITLE
GUI window turns blank grey

### ISSUE THREAD

**Issue by AMDphreak** [balena-io/etcher#2756]
- **Etcher version:** 1.5.24
- **Operating system and architecture:** Win10 Pro 64-bit
- **Do you see any meaningful error information in the DevTools?** No (Did not know how to access this while the bug showed).

The window turns blank/grey after loading properly. This error happens with or without burning an image. It does happen while burning images. It is not 100% predictable.

![etcher io blank windows 10](https://user-images.githubusercontent.com/1058978/56873973-0a7ab600-69fc-11e9-91de-c722b365b844.PNG)

**Comment by thundron** [comment]
@AMDphreak You can check the dev tools' console by pressing `ctrl + shift + i`

**Comment by MimbaMonkeyHouse** [comment]
I have exactly the same issue here. Can't even finish install process... Any solution?

**Comment by thundron** [comment]
@MimbaMonkeyHouse could you paste here the logs you see in the devtools console mentioned above? `ctrl + shift + i` then focus the `Console` tab

**Comment by jkuehl** [comment]
This maybe the same issue ?
![grafik](https://user-images.githubusercontent.com/26136754/58504865-dece2580-818b-11e9-8458-e5873fa0e231.png)
[gui bug.txt](https://github.com/balena-io/etcher/files/3229290/gui.bug.txt)

**Comment by thundron** [comment]
@jkuehl just released a new version for that, 1.5.43

**Comment by jkuehl** [comment]
> 
> 
> @jkuehl just released a new version for that, 1.5.43
Looks fixed to me 👍 
![grafik](https://user-images.githubusercontent.com/26136754/58509041-e5fa3100-8195-11e9-9090-ea48f1167efc.png)

**Comment by AMDphreak** [comment]
It was never a sure thing. It would randomly do this. I closed the app and didn't bother testing it for the random bug again. It's a high incidence rate, so I will add a log later.

**Comment by Cabji** [comment]
I have a similar issue on my PC. After installing, I run Etcher (Windows 10) and all I get is a blank, dark grey/gray window titled Etcher.

From memory, I believe Etcher has _never_ worked correctly on this computer. It works on my wife's laptop, so I'm unsure if there's some underlying config problem on this computer that causes the trouble?

Etcher version installed: balenaEtcher-Setup-1.5.74

![Etcher Dark Grey 2020-02-05 104040](https://user-images.githubusercontent.com/1270367/73800302-02aa3680-4804-11ea-93f1-e5412b7ba1cc.png)

**Comment by lurch** [comment]
Seems the 1.5.74 release is problematic - check #3057 (and its duplicates)
