### ISSUE TITLE
Removing the old resin-io repo?

### ISSUE THREAD

**Issue by adalvigi** [balena-io/etcher#2762]
I used to use Etcher since when resin-io wasn't named balena. I now have an old key on my Ubuntu system. How do I remove the old key and repo so I don't get the `apt update` error?

**Comment by thundron** [comment]
@adalvigi You should be good to go with these instructions https://github.com/balena-io/etcher#uninstall and the above ones for re-installation

**Comment by thundron** [comment]
@adalvigi Actually, you'll have to reference the old repository name using the removal instructions
