### ISSUE TITLE
Cannot install etcher

### ISSUE THREAD

**Issue by mdellacoco** [balena-io/etcher#2769]
- **Etcher version:** 
- **Operating system and architecture: Ubuntu 14.04.6 LTS** 
- **Image flashed:none** 
- **Do you see any meaningful error information in the DevTools? E: Unable to locate package balena-etcher-electron**

**Comment by lurch** [comment]
Yeah, I've seen that problem too - seems to be a limitation with Ubuntu 14.04's APT version https://github.com/balena-io/etcher/pull/2592#issuecomment-451882927

**Comment by thundron** [comment]
Try taking a look at https://www.nixcraft.com/t/unable-to-locate-package-on-ubuntu-linux-when-using-apt-get/1077 and one of the solutions proposed there
There's not much we can do unfortunately.
