### ISSUE TITLE
1.5.24 prompting upgrade to 1.5.33 at startup, which is not available

### ISSUE THREAD

**Issue by jeremynz** [balena-io/etcher#2773]
- **Etcher version: 1.5.24** 
- **Operating system and architecture: MacOS Mojave** 
- **Image flashed: N/A** 
- **Do you see any meaningful error information in the DevTools? N/A** 

1.5.24 on startup is saying 1.5.33 is available for download, but its not available on the website.

**Comment by thundron** [comment]
@jeremynz What do you actually see on the website? Sounds like a UI bug, because it's there

<img width="249" alt="Screenshot 2019-05-09 at 11 58 04" src="https://user-images.githubusercontent.com/5888446/57445075-df8d2f00-7251-11e9-8e77-002b1fb3f2d2.png">

**Comment by jeremynz** [comment]
looks like it was an issue with ad blocking in Chrome, either from AdBlock or AdBlock+
