### ISSUE TITLE
[Feature Request] - Burn from URL

### ISSUE THREAD

**Issue by badbat75** [balena-io/etcher#2804]
Maybe an idea to implement a function that burn images directly from an URL?

**Comment by lurch** [comment]
Duplicate of #1804 ?

**Comment by badbat75** [comment]
Sorry, yes it is. You can mark as duplicate and close.

**Comment by zvin** [comment]
This is implemented in etcher-sdk [example](https://github.com/balena-io-modules/etcher-sdk/blob/master/examples/http-zip.ts) but I don't know how this should look in etcher itself.

Closing as it is a duplicate of #1804
