### ISSUE TITLE
Windows Download 404

### ISSUE THREAD

**Issue by jswatts92** [balena-io/etcher#2811]
404 on windows download from https://www.balena.io/etcher/ for 1.5.42

**Comment by lurch** [comment]
Caching problem? https://www.balena.io/etcher/ shows me that the latest version is 1.5.43

**Comment by jswatts92** [comment]
Maybe, I was able to change the URL to 1.5.43 to let me download it.  Thanks for the help

**Comment by lurch** [comment]
The files can also be downloaded from https://github.com/balena-io/etcher/releases
