### ISSUE TITLE
Last available version in repository is 1.5.19 (from march 2019)

### ISSUE THREAD

**Issue by rradar** [balena-io/etcher#2825]
- **Etcher version:** 

Latest version from official debian repo: **1.5.19**
https://dl.bintray.com/etcher/debian/pool/e/etcher/

- **Operating system and architecture:** 

debian based

- **Image flashed:** 

you don't need to care

- **Do you see any meaningful error information in the DevTools?**

**Comment by rradar** [comment]
....and it's june now

**Comment by peliopoulos** [comment]
July!

**Comment by thundron** [comment]
Updated to 1.5.51 💪

**Comment by rradar** [comment]
Not needed anymore! Save disk space and purge etcher :laughing: 

[**usbimager**](https://gitlab.com/bztsrc/usbimager) comes in a package of less than 1MB (like 400 hundred(!) times less than etcher), does more things and does it better. No spyware, adware, bullshitware! :heart:

**Comment by lurch** [comment]
Does usbimager allow you to flash RPi Compute Modules? Does usbimager allow you to flash to multiple drives at once?

**Comment by rradar** [comment]
> Does usbimager allow you to flash RPi Compute Modules? Does usbimager allow you to flash to multiple drives at once?

No idea because I never used such features in my live.

What matters to me is **privacy, size** and **speed** - usbimager outperforms etcher in all these :rocket:
