### ISSUE TITLE
Implement new UI designs

### ISSUE THREAD

**Issue by konmouz** [balena-io/etcher#2834]
<img width="1215" alt="Screenshot 2019-06-24 at 16 44 30" src="https://user-images.githubusercontent.com/15323961/60032868-5ca82280-969f-11e9-98cc-ceaf4ea86f26.png">

Implement new designs from @apexider -- https://zpl.io/ankLE6J

cc @thundron

**Comment by shawaj** [comment]
Guessing we can close this @konmouz @thundron ?

**Comment by apexider** [comment]
@shawaj yes! :)

**Comment by shawaj** [comment]
@apexider great 👍
