### ISSUE TITLE
Etcher Broke my 3 SD cards

### ISSUE THREAD

**Issue by bawantha** [balena-io/etcher#2847]
- **Etcher version:** 1.5.51
- **Operating system and architecture:** Windows10 x64
- **Image flashed:** 2019-06-20-raspbian-buster-full

I used ethcer to burn my raspbian os but after burning my SD card(s) didn't recognize by windows , even in **CMD** _diskpart_ nothing showing

**Comment by thundron** [comment]
Did you ultimately use the sd cards you flashed? Even if not, it's perfectly normal for Windows not to be able to recognise a Linux image, and in fact even macOS would complain (mine does!) about the newly-flashed sd card/usb stick not being readable by the OS, which doesn't mean the target is broken; it just means the OS can't read/mount the partitions that are in it.
Of course, be mindful of the fact that when flashing an image, the target gets erased and everything is replaced by the new content, a.k.a. the image.
I suggest following the steps we listed here to recover the drive(s), in case it wasn't your intention to write an image for later use https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#windows
