### ISSUE TITLE
file size of balenaEtcher-...-1.5.5.1.zip /.exe is now >=122MByte

### ISSUE THREAD

**Issue by beta-tester** [balena-io/etcher#2857]
- **Etcher version:** 
1.5.51 setup exe or portable zip
- **Operating system and architecture:** 
Windows

why is the file size of Etcher setup and portable grown that much?
currently ~139MB for setup and ~122MB for portable zip?
what else is inside Etcher now that lets Etcher bloat to that huge size?
i had an older version of Etcher with the same functionality and look and feel, that was ~50MB - and that file size i thought was already too big.
and now the file size is nearly three times as big as the old one i had from the past.

when the file size of Etcher keeps growing in that speed, it will take more time to download Etcher than downloading the image to flash ...

**Comment by thundron** [comment]
While it's not possible to give the exact reason, I can tell you that some fixes we made required a major overhaul and we're also in the process of switching UI frameworks entirely, which means we'll have two libraries (and their separate dependencies) for the duration of the transition. We're also implementing features that users will be able to switch on/off based on where they're running Etcher, which adds to the size as well.
We'll be adding treeshaking for dependencies Soon™ though!
