### ISSUE TITLE
When I launch Etcher, I get a blank screen.

### ISSUE THREAD

**Issue by inismor** [balena-io/etcher#2866]
- **Etcher version:** 
1.5.51 (1.5.51)

- **Operating system and architecture:** 
macOS Mojave 10.14.5

- **Image flashed:** 
Never got that far

- **Do you see any meaningful error information in the DevTools?** 
"DevTools was disconnected from the page. Once page is reloaded, DevTools will automatically reconnect."

<img width="1534" alt="Screenshot 2019-07-26 at 22 26 17" src="https://user-images.githubusercontent.com/88064/61982604-34d91100-aff5-11e9-8501-166222a1bbb7.png">

**Comment by lurch** [comment]
Similar to #2659 ?

**Comment by DouglasHeriot** [comment]
I have the same issue on Windows 10 (latest 1903)
I installed Etcher fresh from the website.

**Comment by crackingthecodethomas** [comment]
Same here. Shows the normal grey etcher screen and then goes white where i cant click anything. Ctrl + Shift + I says Dev tools was disconnected.

**Comment by thundron** [comment]
Could you try opening the devtools then reloading by pressing `ctrl + R` ? That *should* show the content of the previous logs too. If not, try enabling logs persistence in the console settings

**Comment by inismor** [comment]
thundron, I did as you asked. It goes off for a second and then returns with the same error. I've turned on log preservation. This is the response I get in the console:
```
Navigated to file:///Applications/balenaEtcher.app/Contents/Resources/app.asar/lib/gui/app/index.html
/Applications/balenaEtcher.app/Contents/Resources/app.asar/node_modules/raven-js/dist/raven.js:58 Download the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
/Applications/balenaEtcher.app/Contents/Resources/app.asar/node_modules/raven-js/dist/raven.js:58  _____ _       _
|  ___| |     | |
| |__ | |_ ___| |__   ___ _ __
|  __|| __/ __| '_ \ / _ \ '__|
| |___| || (__| | | |  __/ |
\____/ \__\___|_| |_|\___|_|

Interested in joining the Etcher team?
Drop us a line at join+etcher@balena.io

Version = 1.5.53, Type = dmg
/Applications/balenaEtcher.app/Contents/Resources/app.asar/node_modules/raven-js/dist/raven.js:58 Wed Aug 14 2019 17:17:35 GMT+0100 (BST) Application start ({"packageType":"dmg","version":"1.5.53","applicationSessionUuid":"43a54a92-2272-4ff1-bb1d-81a5e5bb2481","sample":0.1})
```

and then the alert pops up about DevTools being disconnected. All of the while, every window is just white. Oddly, when I trace the URL, `app.asar` turns out to be a document, not a directory, so I'm not sure how it was supposed to work.

**Comment by lurch** [comment]
You can read more about `.asar` files at https://github.com/electron/asar

**Comment by DavidFW1960** [comment]
same issue here

**Comment by pawankumar30** [comment]
Try Running with low configuration under compatibility, also with reduces resolution. It worked for me at 640*480 resolution.

**Comment by quamis** [comment]
Had the problem, on Ubuntu, devtools (ctrl+shit+i) reported the same error as here: https://github.com/signalapp/Signal-Desktop/issues/2641

Fixed as suggested in the above issue by changing /tmp:

TMPDIR=./tmp ./balenaEtcher-1.5.80-x64.AppImage 


As a note, running things from /tmp seems like a security issue.

**Comment by lurch** [comment]
@quamis Hmm, maybe something like #1699 is affecting Etcher again? :confused:

**Comment by quamis** [comment]
Yeah, seems so. Using a non default temp folder worked as expected

**Comment by stanleeway** [comment]
to fix this on windows 7 run it at 256 colors,it should work

**Comment by Stefanious** [comment]
Same issue, Zorin, Ubuntu, Debian live disk... Does not work. Shame. Switched to Ventoy...

**Comment by glaubersm** [comment]
Same problem with balenaEtcher-Portable-1.18.4 on Windows 7 Professional 64 bits.

**Comment by jimboelter** [comment]
Same, version 1.18.4 on Win7 Pro 64, just ran Rufus and built my boot image
