### ISSUE TITLE
Any chance of a debian build for ARM (Raspberry Pi)?

### ISSUE THREAD

**Issue by iandstanley** [balena-io/etcher#2879]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment]
See #2870

**Comment by thundron** [comment]
Not now, but we're using [this issue](https://github.com/balena-io/etcher/issues/2870) to track when we'll do. Closing in favour of the other issue

**Comment by Askmewho** [comment]
Ive already done this for rpi3 and it should work on armhf distros for rpi4
Compile it by yourself if you want, I am doing it right now for my manjaro Aarch64
https://drive.google.com/file/d/1tbt4aQ2EGAKR6u4AhOVyXF9bfXJaDUhn/view
