### ISSUE TITLE
Etcher asked for permissions to access my photos on Mac OS Mojave

### ISSUE THREAD

**Issue by cyberplant** [balena-io/etcher#2891]
- **Etcher version:** 1.5.39  
- **Operating system and architecture:** Mac OS X Mojave
- **Image flashed:** 128Gb file
- **Do you see any meaningful error information in the DevTools?** 

No errors, the image is still flashing, but while the percentage was about 26% it asked for access to my photos in Mac OS, which I accidentally accepted, worried that my flashing will stop! 

Any ideas?

**Comment by thundron** [comment]
I think that's a bug on OSX, it happened some time ago with the Contacts and Calendar permissions, see here https://github.com/electron/electron/issues/14833
On our side, the only permissions we ask for are for writing to the chosen target; surely not Photos, and surely not *during* flashing

**Comment by thundron** [comment]
My suggestion is to revoke those permissions and check that you can still flash.
If not, I guess we got an issue with Mojave again
