### ISSUE TITLE
1.5.56 on Win7, 'STARTING' dies

### ISSUE THREAD

**Issue by bbillp** [balena-io/etcher#2892]
1.5.56 August 21, 2019
Windows 7 
SDR_play_RPI_V0.6.img 
- **Do you see any meaningful error information in the DevTools?** 
No

Etcher executes, I select the input file, Etcher advances to Starting and never shows additional activity but after 10 minutes the FLASH screen reappears.  The SD will open in explorer but is empty.  Before starting Etcher the 32gig Samsung SD was cleared with diskpart then formatted FAT16 in Windows disk manager.

**Comment by lurch** [comment]
Took a bit of searching, but I eventually found a link to the mentioned image at https://www.sdrplay.com/community/viewtopic.php?f=6&t=4884 in case it helps the Etcher developers.

**Comment by bbillp** [comment]
I found the problem, after starting Etcher and selecting input and output devices and files, START, a Microsoft message pops up behind the Etcher window that cannot be seen, the message needs acknowledgement to execute a MS command then once clicked the SD write continued to completion.     Bill P.
