### ISSUE TITLE
Etcher installer should allow installation to a different folder

### ISSUE THREAD

**Issue by pdcastro** [balena-io/etcher#2895]
Creating this issue following feedback from a user in the following balenaEtcher forum thread:
https://forums.balena.io/t/conflicting-messages/29171

User case: user has a separate partition for programs and does not want to install anything on the C partition that is not directly related to the operating system.

- **Operating system and architecture:** Windows PC

**Comment by lurch** [comment]
Duplicate of #2793 ?

**Comment by thundron** [comment]
Yes. Closing as duplicate of #2793
