### ISSUE TITLE
Won't flash to usb

### ISSUE THREAD

**Issue by ghost** [balena-io/etcher#2898]
it's not flashing anything, saying 'something went wrong due to an internal error!' running Mac catalynia beta 

Wanted to install ubuntu, no go, not any bistro :/ instantly etcher shuts down as soon as it has to flash
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by mrmarcsmith** [comment]
I'm experiencing this error too!

**Comment by lurch** [comment]
For issues with Etcher on macOS Catalina, see #2833

**Comment by thundron** [comment]
As mentioned by @lurch , please see #2833 and #2911 as well for temporary workarounds on Catalina. Closing as duplicate
