### ISSUE TITLE
My SD card doesnt work

### ISSUE THREAD

**Issue by MegaBloopy** [balena-io/etcher#2912]
- Etcher version: Newest
- Operating system and architecture: Windows 10 64 Bit
- Image flashed: Linux
- Do you see any meaningful error information in the DevTools? Can't Access 

- So i cant access my 128GB SD card anymore, it says please insert something into drive. and when i plug it in it says directory is invalid

**Comment by lurch** [comment]
https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives

**Comment by MegaBloopy** [comment]
That doesn’t work, diskpart doesn’t load unless I unplug the Ed card

**Comment by MegaBloopy** [comment]
I’ve tried literally everything I can

**Comment by lurch** [comment]
Try a different card-reader and/or different computer and/or different OS? :man_shrugging:

**Comment by MegaBloopy** [comment]
Havent tried linux but mac and windows and switch dont work

**Comment by MegaBloopy** [comment]
Mac worked with some jiggling and modifying i could get an empty 126.6 GB SD card thanks
