### ISSUE TITLE
Blank USB stick is created

### ISSUE THREAD

**Issue by jasonology** [balena-io/etcher#2918]
- **Etcher version:** 1.5.57
- **Operating system and architecture:** macOS 10.14.6
- **Image flashed:** lubuntu-18.04.3-desktop-i386.iso
- **Do you see any meaningful error information in the DevTools?** 

No, all looks OK in the console: 

> Wed Oct 02 2019 09:46:34 GMT+1000 (AEST) Done ({"errors":[],"devices":{"failed":0,"successful":1},"status":"started","image":"/Users/jason/Downloads/lubuntu-18.04.3-desktop-i386.iso","drives":[{"size":8002732032,"isVirtual":false,"enumerator":"DiskArbitration","logicalBlockSize":512,"raw":"/dev/rdisk2","error":null,"isReadOnly":false,"displayName":"/dev/disk2","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"/dev/disk2","busVersion":null,"isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":"IODeviceTree:/PCI0@0/XHC1@14","mountpoints":[],"description":"SanDisk Cruzer Facet Media","isUAS":null}],"driveCount":1,"uuid":"58509926-837c-41fb-afad-71d8f03a8ad6","flashInstanceUuid":"58509926-837c-41fb-afad-71d8f03a8ad6","unmountOnSuccess":true,"validateWriteOnSuccess":true,"trim":false,"applicationSessionUuid":"6521f038-a768-4d26-a948-c0b4ab6f1dad","flashingWorkflowUuid":"f71ed111-a1f1-4221-ba24-6616e765dd48","sample":0.1})

As soon as it’s done I see “The disk is not recognized by this computer” standard macOS dialog. Disk Utility reports no volume on the the USB stick.

**Comment by lurch** [comment]
That's probably because of https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos ? i.e. the image _has_ been flashed correctly, but macOS just isn't able to recognise it.
