### ISSUE TITLE
the writer process ended unexpectedly. Please try again... 

### ISSUE THREAD

**Issue by chelseamw13** [balena-io/etcher#2925]
- **1.5.58:** 
- **macOS Catalina 10.15:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

Just updated my computer to Catalina and unfortunately am no longer able to use etcher. Any help/tips would be great! thanks

{"name":"Error","message":"EPERM: operation not permitted, open '/dev/rdisk2'","stack":"Error: EPERM: operation not permitted, open '/dev/rdisk2'","code":"EPERM","syscall":"open","errno":-1}

**Comment by lurch** [comment]
See #2833
