### ISSUE TITLE
  Download speed VERY VERY SLOW at China!!!!!

### ISSUE THREAD

**Issue by ghost** [balena-io/etcher#2938]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment]
See #2083 and #2336 and #2910

**Comment by mifi** [comment]
Same problem in singapore

**Comment by thundron** [comment]
We'll do our best to reduce the package size (e.g. [here](https://github.com/balena-io/etcher/pull/2987)) but for now there's little we can do other than that

**Comment by lurch** [comment]
@thundron Just asking out of curiosity, but there doesn't seem to be much change in download-size between 1.5.69 and 1.5.70 ? https://github.com/balena-io/etcher/releases

**Comment by Antony-L** [comment]
For you guys in China copy the link for your file and use Xulei(迅雷)
