### ISSUE TITLE
MacOS Catalina (10.15) Apple-Malware-Scan failed to scan

### ISSUE THREAD

**Issue by grichner** [balena-io/etcher#2946]
- Etcher version: 1.5.60 of Cask balenaetcher
- Operating system and architecture: MacOS 10.15 Catalina
- Image flashed: Software does not run
- Do you see any meaningful error information in the DevTools? BalenaEtcher cannot be executed because apple cannot search for Malware

**Comment by thundron** [comment]
We're working on the package notarization for macOS Catalina which will come in the next version; in the meanwhile, please see #2833 (run Etcher as `sudo`). Closing
