### ISSUE TITLE
autoupdate on Win10 not working

### ISSUE THREAD

**Issue by FlorinAndrei** [balena-io/etcher#2947]
- **Etcher version:** 1.5.56
- **Operating system and architecture:** Win10 x64
- **Image flashed:** none
- **Do you see any meaningful error information in the DevTools?** no

The latest Etcher version on GitHub is 1.5.60. Autoupdates are enabled. My app doesn't seem to do anything to auto-update.

**Comment by thundron** [comment]
See https://github.com/balena-io/etcher/issues/2956#issuecomment-549301238
