### ISSUE TITLE
Synaptic Package Manager - E: Malformed line 1 in source list /etc/apt/sources.list.d/balena-etcher.list (type)

### ISSUE THREAD

**Issue by Bill-Lo3** [balena-io/etcher#2952]
- **Etcher version:**  Etcher 1.5.59
- **Operating system and architecture:**  Parrot Security OS

Trying to open Synaptic Package Manager.

E: Malformed line 1 in source list /etc/apt/sources.list.d/balena-etcher.list (type)
E: The list of sources could not be read.
Go to the repository dialog to correct the problem.
E: _cache->open() failed, please report.

The balena-etcher.list file just contains this
https://github.com/balena-io/etcher.git

**Comment by Bill-Lo3** [comment]
I ended up just removing it for now but would like to try to install it correct this time. If anyone can, lmk why that happened and how to fix it? Thanks

to uninstall
sudo rm /etc/apt/sources.list.d/balena-etcher.list

sudo apt-update

**Comment by lurch** [comment]
> The balena-etcher.list file just contains this
https://github.com/balena-io/etcher.git

That's incorrect. See https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64
