### ISSUE TITLE
Etcher secretly spies on the user without consent.

### ISSUE THREAD

**Issue by sneak** [balena-io/etcher#2977]
Reopening #2057 - the issue is still valid.

- **Etcher version:** 1.5.63
- **Operating system and architecture:** darwin x64

Wikipedia defines spyware as:

> Spyware is a software that aims to gather information about a person or organization, sometimes without their knowledge, and send such information to another entity without the consumer's consent. 

## Required Elements

1. is software :white_check_mark: etcher is software
1. gather information about a person :white_check_mark: information: that the user is launching etcher
1. without their knowledge :white_check_mark: no indication is displayed at any time that this is happening
1. send information to another entity :white_check_mark: information is transmitted to LAN, ISP, interchange points, and hundreds of others
1. without consent :white_check_mark: no consent is asked for or given (and indeed, none exists)

Etcher has done *precisely this* for some time.

This **silent** tracking **includes IP address and timestamp information**, which is more than sufficient to **identify a user (and perhaps even their physical location)** to the other people who gain access to this data, such as analytics providers, network hosts, interchange points, ISPs, and intelligence services (hi Ed!).

Upon opening Etcher for the **first time**, the following connections are attempted:

<img width="548" alt="Screen Shot 2019-11-26 at 09 51 53" src="https://user-images.githubusercontent.com/408977/69659317-c94e9100-1032-11ea-9e77-4de1dce9f227.png">
<img width="549" alt="Screen Shot 2019-11-26 at 09 52 01" src="https://user-images.githubusercontent.com/408977/69659318-c94e9100-1032-11ea-95f7-7d7dd2f78f2f.png">

At no point am I prompted for consent, or provided the ability or UI to opt out.  This happens *silently*, regardless of user intent or consent.  Only after balena has been contacted by the software does the main application window open:

<img width="912" alt="Screen Shot 2019-11-26 at 09 52 04" src="https://user-images.githubusercontent.com/408977/69659361-de2b2480-1032-11ea-82ab-cbd1ec9fdf11.png">

Then, the user could attempt to disable the settings, but by then their IP address (and physical location) has by this time already been transmitted to the manufacturer, likely against their consent and wishes.

This issue is not about the GDPR, or the legality of this collection, simply the very practical issue that the software phones home and **leaks the user's IP address to the developers and hundreds of others without consent or even notification**.  At no point does the user have the ability to disable this on first launch.  By simply phoning home, thousands of other people have gained access to the piece of information that a given user is using this software.

At present, that makes this application fit the definition of **spyware**.

Remember: humans have an inalienable right to privacy.  By leaking users' personal data (even if you do not save it, or don't receive it yourself - by *causing it to be sent out of their computer at all*) you have **infringed upon their human rights**.

Do not abuse the human rights of your users.  Ask the user for consent before transmitting *any* data out of their computer.

**Comment by m00dy** [comment]
hmm greek style spyware xD

**Comment by ukd1** [comment]
Looks like there were some updates shipped to try stop this a while back;

- https://github.com/balena-io/etcher/blob/a155811678bfaac5439a301bf8e74d1d8b86b0b1/CHANGELOG.md#v121---2017-12-06

but that it's probably this request - https://github.com/balena-io/etcher/blob/a155811678bfaac5439a301bf8e74d1d8b86b0b1/lib/gui/app/modules/analytics.js#L30 -that's causing your alert. 

That url returns;

```json
{
  "version": 1,
  "analytics": {
    "mixpanel": {
      "HTTP_PROTOCOL": "https",
      "api_host": "api.balena-cloud.com/mixpanel",
      "probability": 0.1
    }
  },
  "autoUpdates": {
    "checkForUpdatesTimer": 300000,
    "autoUpdaterConfig": {
      "autoDownload": false
    }
  }
}
```

This should probably not be requested, as it doesn't look like it's needed?

**Comment by sneak** [comment]
The line you quoted does not make a network request, it just sets a constant.

**Comment by cixtor** [comment]
@sneak you clearly haven’t installed + used `brew cask install steam`

I have thirty-eight (38) hostnames blocked for “Steam.app” and twelve (12) for “Steam Helper.app”.

Blocking one or two requests from “Balena Etcher” is not a big deal compared to other apps.

**Comment by sneak** [comment]
Comparing an unethically-produced, dangerous app to another unethically-produced, dangerous app does not make either one good or safe.

**Comment by cixtor** [comment]
@sneak how is Steam an unethically-produced / dangerous app?

**Comment by cixtor** [comment]
> _The issue is not for people like you who block it, obviously - you are not affected by it. You are an outlier. The issue is for the thousands and thousands of people who are silently being spied on without their knowledge and without their consent._

Fair enough. I understand your point of view now.

**Comment by thundron** [comment]
As you may or may not know, all data Etcher gathers is anonymous which doesn't violate any "user" or "person" data (as in, there's nothing in our analytics that points to you specifically)
We had a discussion for opt-in vs. opt-out a while ago, but we still don't see enough reasons for us to switch over to opt-in, even more so since if it's really an issue, you can disable the analytics in the settings and the only calls you'll see will be for external content that is better placed outside of the application (i.e. the featured project)

**Comment by sneak** [comment]
> * As you may or may not know, all data Etcher gathers is anonymous which doesn't violate any "user" or "person" data (as in, there's nothing in our analytics that points to you specifically)*

This is a false statement. The data Etcher transmits from my machine includes my IP address, which uniquely identifies me.

**Comment by evanlandreneau** [comment]
Looks like it's time to move to UNetBootin...

**Comment by lurch** [comment]
@sneak Out of curiosity, how did you download Etcher in the first place without "leaking your IP address and physical location to thousands of people" ??

**Comment by sneak** [comment]
I don’t use Etcher (funny because it seems I will likely soon be forking it); I know how to use dd. Anyone who wishes, however, can download Etcher using Tor and it will not disclose their ip/location/identity to the manufacturer.

**Comment by jordanius** [comment]
You could always just run Tor on your router, and then ditto for any phone-home telemetry by any program. Problem solved.

Incidentally, I wonder why you're trying to pick on this one application when, to the best of my knowledge, at least one out of four Mac apps "phones home" with similar telemetry. Of course you're going to say that just because others are doing it too doesn't make it ok, but in any case, it seems you really have your work cut out for you, and had better get to writing all of the services promoting all of those other apps too. Or, actually, on second  thought, please don't. Most people aren't really bothered by this sort of telemetry. For those who are, like you, there's always the route of installing Tor directly on your router and having all outgoing connections that you make from any app anonymized. So just solve your own problem, and quit bothering other people who couldn't care less about this "invasion of their privacy" (or if they did care, they probably already thought of the Tor-router thing and solved their own problem themselves, unlike you).

**Comment by pinchies** [comment]
"most people aren't really bothered" -> Citation needed. AFAIK, most people aren't aware. If that were true, and most people really weren't bothered, then why not _ask_ before transmitting?
GDPR set the standard to be expected.

**Comment by sneak** [comment]
It is unethical to assume consent.

**Comment by rradar** [comment]
Easy nowadays. Don't use software which comes bundled with adware and spyware (namely balena etcher).

You can have a 'clean' version of etcher which is called [**usbimager**](https://gitlab.com/bztsrc/usbimager), does things right, respects your privacy and comes in a executable package of 250kb :tada:

**Comment by sneak** [comment]
usbimager's UI is super confusing, especially for new users who just want the 1-2-3 of "select image, select disk, hit flash".  There's a reason people recommend Etcher.  The correct answer is to fork this free software, rename it, remove the spyware, and re-release it.

**Comment by shideneyu** [comment]
Popups started to come up BECAUSE of this dumpy software. That's why I hate Windows. Thank you, Belena, for installing all of those adware on my friend's machine.

**Comment by thundron** [comment]
@shideneyu Etcher doesn't install any adware and will never do. Either your friend installed some bloatware coming from another website/application, downloaded from a *highly* untrusted source or has something else on his PC that is causing trouble.
Either way, Etcher isn't the issue and is definitely not spying on anyone's PC.
There is an option in the settings that disables the *anonymous* data collection (which means there's nothing related to you but only how the application is working, errors and the likes) - as such, there's no need to continue the conversation any further.
