### ISSUE TITLE
Ubuntu Bionic 18.04 Auto update fuction never worked

### ISSUE THREAD

**Issue by Ntemis** [balena-io/etcher#3008]
- **Etcher version:** 
1.5.63
- **Operating system and architecture:** 
Ubuntu Bionic 18.04.x 64bit

I always have to update manually, is there anyway to fetch latest released version from github and then ask for root password kill the current running version and install the new deb package then delete it and run the updated version?

**Comment by lurch** [comment]
See the comments in #2956
