### ISSUE TITLE
Failed device when writing multiple SD cards at the same time

### ISSUE THREAD

**Issue by pglu** [balena-io/etcher#3010]
- **Etcher version:** 1.5.52
- **Operating system and architecture:** Windows 10
- **Image flashed:** Raw image (.img)
- **Do you see any meaningful error information in the DevTools?**

I work with an ICY BOX with 10 slots for Micro SD cards. In Etcher it is possible to specify several Micro SD cards as target. When writing on the card the error message "... Failed device" appears.

If the parallel writing does not work, it would also be good if it could be done serially automated (i.e. one card after the other).

**Comment by thundron** [comment]
Hi, can you fill in the last question of the template regarding devtools console? (`ctrl + shift + i` to open it)

**Comment by pglu** [comment]
Please see the last line

Download the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58  _____ _       _
|  ___| |     | |
| |__ | |_ ___| |__   ___ _ __
|  __|| __/ __| '_ \ / _ \ '__|
| |___| || (__| | | |  __/ |
\____/ \__\___|_| |_|\___|_|

Interested in joining the Etcher team?
Drop us a line at join+etcher@balena.io

Version = 1.5.52, Type = nsis
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:32 GMT+0100 (Mitteleuropäische Zeit) Application start ({"packageType":"nsis","version":"1.5.52","applicationSessionUuid":"2ef7ca75-9d69-4c0a-b111-4d61859c3d9d","sample":0.1})
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:34 GMT+0100 (Mitteleuropäische Zeit) SafeWebview loaded ({"event":{"fromCache":false,"headers":{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) balena-etcher/1.5.52 Chrome/66.0.3359.181 Electron/3.1.9 Safari/537.36"},"id":11,"method":"GET","referrer":"","resourceType":"mainFrame","responseHeaders":{"Accept-Ranges":["bytes"],"Cache-Control":["public, max-age=0"],"Connection":["keep-alive"],"Content-Encoding":["gzip"],"Content-Type":["text/html; charset=UTF-8"],"Date":["Wed, 11 Dec 2019 20:35:33 GMT"],"Etag":["W/\"3c810-16e8d73c970\""],"Last-Modified":["Thu, 21 Nov 2019 10:13:26 GMT"],"Server":["Cowboy"],"Transfer-Encoding":["chunked"],"Vary":["Accept-Encoding"],"Via":["1.1 vegur, 1.1 vegur"]},"statusCode":200,"statusLine":"HTTP/1.1 200 OK","timestamp":1576096534024.7532,"url":"https://www.balena.io/etcher/success-banner/?etcher-version=1.5.52&api-version=2&optOutAnalytics=false"},"applicationSessionUuid":"2ef7ca75-9d69-4c0a-b111-4d61859c3d9d","flashingWorkflowUuid":"8802aece-75fa-475b-808b-10e7a2227e4c","sample":0.1})
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:34 GMT+0100 (Mitteleuropäische Zeit) Open modal ({"name":"drive-selector","applicationSessionUuid":"2ef7ca75-9d69-4c0a-b111-4d61859c3d9d","flashingWorkflowUuid":"8802aece-75fa-475b-808b-10e7a2227e4c","sample":0.1})
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:34 GMT+0100 (Mitteleuropäische Zeit) Reselect drive ({"applicationSessionUuid":"2ef7ca75-9d69-4c0a-b111-4d61859c3d9d","flashingWorkflowUuid":"8802aece-75fa-475b-808b-10e7a2227e4c","sample":0.1})
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:35 GMT+0100 (Mitteleuropäische Zeit) Toggle drive ({"drive":{"size":7932477440,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive10","error":null,"isReadOnly":false,"displayName":"\\\\.\\PhysicalDrive10","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive10","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[],"description":"Generic STORAGE DEVICE USB Device","isUAS":false},"previouslySelected":false,"applicationSessionUuid":"2ef7ca75-9d69-4c0a-b111-4d61859c3d9d","flashingWorkflowUuid":"8802aece-75fa-475b-808b-10e7a2227e4c","sample":0.1})
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:36 GMT+0100 (Mitteleuropäische Zeit) Modal accepted ({"name":"drive-selector","applicationSessionUuid":"2ef7ca75-9d69-4c0a-b111-4d61859c3d9d","flashingWorkflowUuid":"8802aece-75fa-475b-808b-10e7a2227e4c","sample":0.1})
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:38 GMT+0100 (Mitteleuropäische Zeit) Open image selector ({"applicationSessionUuid":"2ef7ca75-9d69-4c0a-b111-4d61859c3d9d","flashingWorkflowUuid":"8802aece-75fa-475b-808b-10e7a2227e4c","sample":0.1})
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:41 GMT+0100 (Mitteleuropäische Zeit) Select image ({"image":{"size":7654604800,"name":"pglu_raspbian-os_v3.3_8GB.img","hasMBR":true,"partitions":[{"offset":32256,"size":66060288,"type":6,"index":1},{"offset":74027520,"size":7340032000,"type":131,"index":2}],"path":"D:\\Rolf\\Dropbox\\01_-_PGLU\\999-PGLU_MASTER\\pglu_raspbian-os_v3.3_8GB.img","extension":"img","logo":false,"blockMap":false},"applicationSessionUuid":"2ef7ca75-9d69-4c0a-b111-4d61859c3d9d","flashingWorkflowUuid":"8802aece-75fa-475b-808b-10e7a2227e4c","sample":0.1})
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:42 GMT+0100 (Mitteleuropäische Zeit) Flashing 0 devices, 0% at null MB/s (total null MB/s) eta in undefineds with 0 failed devices
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:42 GMT+0100 (Mitteleuropäische Zeit) Flash ({"image":"D:\\Rolf\\Dropbox\\01_-_PGLU\\999-PGLU_MASTER\\pglu_raspbian-os_v3.3_8GB.img","drives":[{"size":7932477440,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive9","error":null,"isReadOnly":false,"displayName":"J:\\","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive9","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[{"path":"J:\\"}],"description":"Generic STORAGE DEVICE USB Device","isUAS":false},{"size":7932477440,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive10","error":null,"isReadOnly":false,"displayName":"\\\\.\\PhysicalDrive10","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive10","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[],"description":"Generic STORAGE DEVICE USB Device","isUAS":false}],"driveCount":2,"uuid":"893970b0-5b8f-4509-bd8d-f84aa062e0cf","status":"started","flashInstanceUuid":"893970b0-5b8f-4509-bd8d-f84aa062e0cf","unmountOnSuccess":true,"validateWriteOnSuccess":false,"trim":false,"applicationSessionUuid":"2ef7ca75-9d69-4c0a-b111-4d61859c3d9d","flashingWorkflowUuid":"8802aece-75fa-475b-808b-10e7a2227e4c","sample":0.1})
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Elevating command: C:\Users\Rolf\AppData\Local\Programs\balena-etcher\balenaEtcher.exe C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:43 GMT+0100 (Mitteleuropäische Zeit) SafeWebview loaded ({"event":{"fromCache":false,"headers":{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) balena-etcher/1.5.52 Chrome/66.0.3359.181 Electron/3.1.9 Safari/537.36"},"id":29,"method":"GET","referrer":"","resourceType":"mainFrame","responseHeaders":{"access-control-allow-origin":["*"],"age":["0"],"cache-control":["max-age=600"],"cf-cache-status":["DYNAMIC"],"cf-ray":["543a3f1fde9b63bf-FRA"],"content-encoding":["br"],"content-type":["text/html; charset=utf-8"],"date":["Wed, 11 Dec 2019 20:35:42 GMT"],"expect-ct":["max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""],"expires":["Wed, 11 Dec 2019 05:05:34 GMT"],"last-modified":["Mon, 09 Dec 2019 15:11:26 GMT"],"server":["cloudflare"],"status":["200"],"vary":["Accept-Encoding"],"via":["1.1 varnish"],"x-cache":["HIT"],"x-cache-hits":["1"],"x-fastly-request-id":["f276649295bd8162165ea7f55bafb79bd035cd53"],"x-github-request-id":["C7A4:5A2C:74DC45:96FA2A:5DF076C6"],"x-proxy-cache":["MISS"],"x-served-by":["cache-fra19144-FRA"],"x-timer":["S1576096543.714654,VS0,VE95"]},"statusCode":200,"statusLine":"HTTP/1.1 200","timestamp":1576096543278.072,"url":"https://assets.balena.io/etcher-featured/index.html?etcher-version=1.5.52&api-version=2&optOutAnalytics=false"},"applicationSessionUuid":"2ef7ca75-9d69-4c0a-b111-4d61859c3d9d","flashingWorkflowUuid":"8802aece-75fa-475b-808b-10e7a2227e4c","sample":0.1})
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:35:43 GMT+0100 (Mitteleuropäische Zeit) Flashing 0 devices, 0% at null MB/s (total null MB/s) eta in undefineds with 0 failed devices
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Successfully connected to IPC server: etcher-server-85664, socket root C:\Users\Rolf\AppData\Local\Temp\
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Image: D:\Rolf\Dropbox\01_-_PGLU\999-PGLU_MASTER\pglu_raspbian-os_v3.3_8GB.img
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Devices: \\.\PhysicalDrive9, \\.\PhysicalDrive10
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Umount on success: true
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Validate on success: false
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Trim: false
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:36:05 GMT+0100 (Mitteleuropäische Zeit) Flash error ({"error":{"name":"Error","message":"Couldn't clean the drive, Command failed: diskpart s n (code 2147756042)","stack":"Error: Couldn't clean the drive, Command failed: diskpart s n (code 2147756042)\n    at Object.<anonymous> (C:\\Users\\Rolf\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\etcher-sdk\\build\\diskpart.js:96:23)\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\Rolf\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\etcher-sdk\\build\\diskpart.js:20:65)"},"applicationSessionUuid":"2ef7ca75-9d69-4c0a-b111-4d61859c3d9d","flashingWorkflowUuid":"8802aece-75fa-475b-808b-10e7a2227e4c","flashInstanceUuid":"893970b0-5b8f-4509-bd8d-f84aa062e0cf","image":"D:\\Rolf\\Dropbox\\01_-_PGLU\\999-PGLU_MASTER\\pglu_raspbian-os_v3.3_8GB.img","drives":[{"size":7932477440,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive9","error":null,"isReadOnly":false,"displayName":"J:\\","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive9","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[{"path":"J:\\"}],"description":"Generic STORAGE DEVICE USB Device","isUAS":false},{"size":7932477440,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive10","error":null,"isReadOnly":false,"displayName":"\\\\.\\PhysicalDrive10","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive10","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[],"description":"Generic STORAGE DEVICE USB Device","isUAS":false}],"driveCount":2,"uuid":"893970b0-5b8f-4509-bd8d-f84aa062e0cf","unmountOnSuccess":true,"validateWriteOnSuccess":false,"trim":false,"sample":0.1})
C:\Users\Rolf\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 Wed Dec 11 2019 21:36:06 GMT+0100 (Mitteleuropäische Zeit) Flashing 1 devices, 0% at 2.1 MB/s (total 2.1 MB/s) eta in 3649s with 1 failed devices

**Comment by lurch** [comment]
@pglu Have you verified that Etcher is able to successfully write both cards individually, to rule out any possible hardware problems?
