### ISSUE TITLE
Works absolutely flawlessly

### ISSUE THREAD

**Issue by vualeks** [balena-io/etcher#3011]
I just needed to write this down somewhere and to say THANK YOU!
This utility it a rare thing today that has so good UX, so simple interface that works just as expected without so many not needed and never used options and features that clutter everything. Just amazing. This is how software should look like and should work. Bravo!

I guess you can close this issue now :D

**Comment by shawaj** [comment]
Closing this @vualeks but thanks so much for the kind words 👍
