### ISSUE TITLE
gpg: keyserver receive failed: Server indicated a failure

### ISSUE THREAD

**Issue by kylefelipe** [balena-io/etcher#3017]
- **Etcher version:** Stable
- **Operating system and architecture:** Debian
Im trying to install and your GPG key is down...

**Comment by lurch** [comment]
This is a common problem - see e.g. https://github.com/balena-io/etcher/search?q=gpg&type=Issues

It's usually a temporary problem with the 3rd-party keyserver, and will work again if you try later...
