### ISSUE TITLE
Etcher - brand new USB RAW, unusable

### ISSUE THREAD

**Issue by rand538** [balena-io/etcher#3019]
- Etcher version: v1.5.70
- Operating system and architecture: Win 10 Pro 1909 / i3-5005U
- Image flashed: Debian Live 10.2.0
USB Kingston DT50 16GB 3.1

Most of the solutions I found on forums and Github don’t work:
1. DISKPART
USB appears as 14GB / 0 Free. 
Volume 6: RAW / Removable / Healthy
Partition 1 / Primary
1.a) clean -> A device which does not exist was specified (disconnects)
1.b) select partition 1 -> delete partition -> create partition primary -> select ... -> active -> format FS=FAT32 quick -> 'The parameter is incorrect.'

2. Format in File / Disk Management
Windows can't format device

3. Format in gdisk or fdisk
Formatted in FAT32 in Gparted. Formatted in gdisk and fdisk as well. Still the same. This is first time I'm using these, so it could be I haven't formatted with the right options. 

4. Using Easeus, AOMEI 
Can't format, same as Windows
Easeus showed no bad sectors

5. Formatting in Rufus gives Error: Undetermined error while formatting

**Comment by lurch** [comment]
Just out of curiosity, is Etcher itself still able to flash a different image to the drive?

**Comment by dylanf** [comment]
I am experiencing a similar problem but with SDHC cards, etcher v1.5.70
Unfortunately I cannot determine exactly if the problem lies with etcher, the (old) raspberry Pi that I then tried to boot from the cards, or the new card reader that I am using to write them.

But the end result is I have 2 inaccessible sdhc cards in the last couple of hours, one of them brand new.  Note I am running in windows 10 (which can no longer even identify the cards).

**Comment by rand538** [comment]
I solved the problem. Whenever I went to diskpart to clean and format, I would add 'quick' attribute. I tried formatting without the quick part and it worked. It took longer but now my USB is fine. Tried copying files and reading them, no problem. Before this, some methods would appear to be successful, but eventually the USB would revert to RAW. Now it's stable. 
Back to Rufus, Etcher never again.

**Comment by lurch** [comment]
As mentioned in many other issues, this isn't a "problem" of Etcher, but a "problem" of the image you're tying to flash. See e.g. https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos for more info.
