### ISSUE TITLE
etcher on os x allowes no write (v1.5.70)

### ISSUE THREAD

**Issue by pwy300** [balena-io/etcher#3022]
- Etcher version: v1.5.70
- Operating system and architecture: os x 
- Image flashed: all

**Comment by lurch** [comment]
I _suspect_ the Etcher developers would appreciate more detail (e.g. a screenshot and/or any error messages), in order to try and determine what might be going wrong? :wink:

**Comment by thundron** [comment]
More details would definitely be appreciated, otherwise there's nothing we can do.
Could you tell us a bit more about the behaviour, as well as filling in the last point of the issue template (logs in the console after the failed operation with `cmd + opt + i`)?

**Comment by rememberedbound** [comment]
This fixed it for me, I had a previous FTDI USB serial driver installed, on Catalina it grabs write access to the USB serial device in exclusive mode and won't allow anything else to talk to it. Installed 2.3 from here https://www.ftdichip.com/Drivers/VCP.htm and that fixed it without even restarting etcher.

No having to use sudo etc either.
