### ISSUE TITLE
New (suspicious?) password prompt

### ISSUE THREAD

**Issue by f-fritz** [balena-io/etcher#3025]
- **Etcher version: 1.5.70** 
- **Operating system and architecture: macOS 10.15.2 (x86 64bit)** 
- **Image flashed: 2019-09-26-raspbian-buster-lite.img** 

Since upgrading to 1.5.70 the password prompt appearing when hitting the Flash!-button looks different than before. And different than the standard macOS prompt (at least I have not seen this before). Is it safe or a custom prompt, passing the password to Etcher - technically enabling it to do things I may not want?

<img width="532" alt="etcher password prompt" src="https://user-images.githubusercontent.com/46245228/71662909-74015000-2d53-11ea-93aa-858dea54873a.png">

**Comment by thundron** [comment]
It's due to the latest changes by macOS Catalina and needed to elevate the writing process for flashing the selected target(s). We're still on the lookout for a nicer solution, as we had some permission issues with the previous module (only on macOS)
