### ISSUE TITLE
Etcher can not running well(version  1.5.74)

### ISSUE THREAD

**Issue by a18214264850** [balena-io/etcher#3060]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

in windows version,i tried in system version 1909/1809,but when i open it(no matter whether i turn off uac)it doesn't display bottom at all,but it works well in 1.5.73.

**Comment by lurch** [comment]
See #3062
