### ISSUE TITLE
Allow PolKit to identify etcher temporary file

### ISSUE THREAD

**Issue by ffissore** [balena-io/etcher#3065]
Etcher creates a temporary file after hitting the "flash" button. Running that file requires superuser privileges.
However the file name is totally random, which makes it impossible to set up a PolKit rule that allows normal users to run that file without asking them root password
Investigate how to set up such a rule, for example by prefixing the name of the temporary file with a known value

- **Etcher version:** 1.5.51
- **Operating system and architecture:** linux

**Comment by lurch** [comment]
Is that what #3047 was attempting to do? :man_shrugging:

**Comment by ffissore** [comment]
It looks like so, and it's now part of #3064. Let's see if prefix does the trick, otherwise we'll need to look for something else

**Comment by lurch** [comment]
That PR has now been merged, so I guess it's included in Etcher 1.5.76 ? :man_shrugging:

**Comment by thundron** [comment]
Correct @lurch , closing

**Comment by thundron** [comment]
Did the prefix solve the issue @ffissore ?

**Comment by ffissore** [comment]
I'll ping the [forum user](https://forums.balena.io/t/how-to-identify-etcher-with-polkit/58363/28) that requested this change. What's the prefix on linux?

**Comment by thundron** [comment]
It's `balena-etcher-electron-`, closing so this gets propagated

**Comment by georgiats** [comment]
Not sure if it helps, but the user has found a resolution and reported it here. https://forums.balena.io/t/how-to-identify-etcher-with-polkit/58363/30

**Comment by thundron** [comment]
I guess the prefix is working as intended then.
Thank you @georgiats
