### ISSUE TITLE
Cannot flash Raspbian with Etcher on macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by VeronicaDavichi** [balena-io/etcher#3066]
- **Etcher version: 1.5.76 ** 
- **Operating system and architecture: macOS Catalina 10.15.3** 
- **Image flashed: 2020-02-05-raspbian-buster-full.img (also failed with 2019-09-26 version)** 
- **Do you see any meaningful error information in the DevTools?** 
I used windows version to flash it successfully, but macos not. Sorry I do not have any other card to reproduce it. And it is too late for me to see the Cmd+Alt+I command. The Image I used was copyed from macOS and I checked its sha-256 on both operating systems.

**Comment by thundron** [comment]
It would be useful to have the actual error + the logs in the console. Meanwhile you can have a look at other issues OSX related, we can reopen this one if you manage to reproduce
