### ISSUE TITLE
Non-standard password dialog

### ISSUE THREAD

**Issue by adamkdean** [balena-io/etcher#3067]
Upon making changes, as would be expected, Etcher asks for the password so it can get superuser access but it uses a non-standard dialog. This makes me nervous.

![image](https://user-images.githubusercontent.com/1639527/74420665-baae9380-4e43-11ea-8376-e94a7ffeecbd.png)

You'd imagine it to use the standard prompt like #1526.

> Version 1.5.76 (1.5.76)

**Comment by lurch** [comment]
AFAIK this is related to #2939

**Comment by zvin** [comment]
There is currently no other way for writing to `/dev/rdiskN` on macOS Catalina.
See the linked issues above.

**Comment by CanonCan** [comment]
Marcos Catalina broke writing to USB drives for many tools such as the unraid USB creator as wel best to grab a copy of windows and do it in boot camp or a virtual environment

**Comment by lurch** [comment]
The reason _why_ it uses a non-standard password prompt is explained in #3107
