### ISSUE TITLE
Running ia32 version on an x64 laptop results in FUSE error

### ISSUE THREAD

**Issue by imrehg** [balena-io/etcher#3076]
- **Etcher version:** 1.5.78 (and before), ia32
- **Operating system and architecture:** x64, ArchLinux
- **Image flashed:** N/A
- **Do you see any meaningful error information in the DevTools?** N/A

While I know this might be an edge case but might uncover something more interesting.
I've accidentally downloaded the `ia32` version of Etcher from the website, and tried to run the AppImage before realizing it. It resulted in:
```
~/Downloads/etcher> ./balenaEtcher-1.5.78-ia32.AppImage                   
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
exit 1
```
The thing, though, that if I do an extract:
```
~/Downloads/etcher> ./balenaEtcher-1.5.78-ia32.AppImage --appimage-extract
squashfs-root/.DirIcon
squashfs-root/AppRun
squashfs-root/LICENSE.electron.txt
squashfs-root/LICENSES.chromium.html
[...snip...]
squashfs-root/usr/share/icons/hicolor/512x512/apps/balena-etcher-electron.png
squashfs-root/v8_context_snapshot.bin
```
and then run it directly
```
~/Downloads/etcher> squashfs-root/balena-etcher-electron
Gtk-Message: 08:42:31.005: Failed to load module "canberra-gtk-module"
Checking for update
ready-to-show: 2517.655ms
Update for version 1.5.78 is not available (latest version: 1.5.78, downgrade is disallowed).
```
then it works, and corectly burns stuff.
Same if I start with the `AppRun`
```
~/Downloads/etcher> squashfs-root/AppRun
Gtk-Message: 08:43:11.356: Failed to load module "canberra-gtk-module"
Checking for update
ready-to-show: 2472.083ms
Update for version 1.5.78 is not available (latest version: 1.5.78, downgrade is disallowed).
```

The x64 version can run totally fine from an `.AppImage` in either case.

This issue with the 32-bit version is present to at least `1.5.49` that I went back to check, didn't look further. Also, I don't have a 32-bit machine at the moment to check whether the AppImage runs correctly there, but might try in the future.
Cheers!

**Comment by lurch** [comment]
Yeah, that's a fairly common error see e.g. https://github.com/balena-io/etcher/search?q=appimage+libfuse&type=Issues

Interesting that the "application inside" still runs though, even if the AppImage itself doesn't. :eyes: 
I guess that counts as an AppImage-issue rather than an Etcher-issue? :man_shrugging:
