### ISSUE TITLE
403 Forbidden error on package repository

### ISSUE THREAD

**Issue by hollec** [balena-io/etcher#3078]
- **Etcher version:** 
1.5.76
- **Operating system and architecture:**
Ubuntu 19.10 (x64)
- **Image flashed:** 
N/A
- **Do you see any meaningful error information in the DevTools?** 
N/A

When performing an apt-get update, I receive a 403 Forbidden error from the Etcher Debian package repository.

> ...
> Err:18 https://dl.bintray.com/etcher/debian stable Release               
>   403  Forbidden [IP: 54.201.242.72 443]
> ...
> E: The repository 'https://deb.etcher.io stable Release' no longer has a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

There were previously no issues with the repository and the repository line and GPG key matches the [README](https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64).

`deb https://deb.etcher.io stable etcher`

**Comment by legolas-salogel** [comment]
hi, 
Debian and Ubuntu based Package Repository (GNU/Linux x86/x64) is down

**Comment by gratefulfrog** [comment]
Same for me ... XUbuntu 18.04

**Comment by Dude4Linux** [comment]
Same for me ...  Files are still listed at https://dl.bintray.com/etcher/debian/ but when I try to retrieve anything I get
```
Forbidden!
```
Either a permissions problem or a payment issue.

**Comment by cowboysmall** [comment]
Same for me - with rpm-based repository.

**Comment by CanonCan** [comment]
Same for me with Fedora workstation 30

**Comment by mboudreau** [comment]
Same here, getting a 403 when apt-get tries to get this file: https://dl.bintray.com/etcher/debian/dists/stable/Release

**Comment by ddt3** [comment]
Same here, but as this is not local that is not a surprise...

**Comment by tomreyn** [comment]
I think we have sufficiently established that this affects everyone trying to download files from URLs starting `https://dl.bintray.com/etcher/`.

**If you are also affected by this, please just subscribe to this bug. There is no need to post another "me too" comment.** Thanks.

**Comment by DinStamou** [comment]
Same here, Debian Testing:
`E: The repository 'https://deb.etcher.io stable Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.`
I believe it has to do with the Release file.

**Comment by thundron** [comment]
We're working on fixing the issue, I'll update this issue as soon as it's solved

**Comment by ToomaiO** [comment]
The central problem is pointed from 
https://github.com/balena-io/etcher/issues/3078#issuecomment-590128779
it looks as a rigth toi access problem.

**Comment by lurch** [comment]
BTW @thundron I just noticed that https://bintray.com/etcher/debian says "Resin.io Debian Packages" :eyes: 
Maybe it should be changed to "Etcher DEB Packages" to make it more in line with https://bintray.com/etcher/redhat ?

**Comment by CanonCan** [comment]
Is there any updates? it’s been more than two days since it’s been down

**Comment by thundron** [comment]
We're in touch with Bintray to get this solved, unfortunately we can't provide any ETA

**Comment by giupardeb** [comment]
in fedora 31 I have been the same problem for a few days

**Comment by Ninoh-FOX** [comment]
same error in debian 9/10:

Err:11 https://dl.bintray.com/etcher/debian stable Release   
  403  Forbidden

**Comment by siucdude** [comment]
Any update?

**Comment by ijash** [comment]
same problem

**Comment by enguerran-popup** [comment]
@thundron Could you lock this issue for contributors only? So we can avoid the "same here" spam.

**Comment by thundron** [comment]
@siucdude not yet, again we're in constant touch with Bintray (the download provider) to get this solved ASAP.
In the meantime, please update/install through the release page
Locking down for now, we'll update the issue as soon as this is solved. It's a matter of communication unfortunately so we can't give have an ETA on that

**Comment by thundron** [comment]
Solved, following on https://github.com/balena-io/etcher/issues/3133 for another issue
