### ISSUE TITLE
Can not find icon.png

### ISSUE THREAD

**Issue by NelDav** [balena-io/etcher#3080]
- **Etcher version:** 1.5.79
- **Operating system and architecture:** Windows 10
- **Image flashed:** 2020-02-13-raspbian-buster-lite
- **Do you see any meaningful error information in the DevTools?** 
> GET file:///C:/Users/DN/AppData/Local/Programs/balena-etcher/resources/app.asar/lib/assets/icon.png net::ERR_FILE_NOT_FOUND

I think etcher should not crash because of a missing image

**Comment by lurch** [comment]
Possibly a duplicate of #3039 ? I wonder why more people aren't getting this error? :man_shrugging:

**Comment by thundron** [comment]
When does this happen?

**Comment by NelDav** [comment]
It happens, directly bevore flashing.

I solved the problem by adding Balena as exception in "Allow an app through Controlled folder acces". (Settings->Update & Security->Windows Security->Virus & threat protection->Manage Settings->Controlled folder access->Allow an app through Controlled folder acces)

**Comment by lurch** [comment]
Ahhhh. Seems like tweaking that setting somehow fixes many Etcher problems? https://github.com/balena-io/etcher/search?q=controlled+folder+access&type=Issues

**Comment by wahyudwikrisnanto** [comment]
Im still had the problem even my setting on controlled folder access is turned off

**Comment by thundron** [comment]
@wahyudwikrisnanto have you tried opening as admin?

**Comment by zvin** [comment]
fixed in 1.5.84
