### ISSUE TITLE
PhysicalDrive2: UNKNOWN: unknown error, write

### ISSUE THREAD

**Issue by RoonMoonlight** [balena-io/etcher#3110]
- **Etcher version:** 1.5.80
- **Operating system and architecture:** Windows 10 Home
- **Image flashed:** hamonikr-sun-3.0-amd64.iso
http://invesume.com/linkfile/download_count.php?type=hamonikr-sun-3.0-amd64.iso
- **Do you see any meaningful error information in the DevTools?** No, it says error: null
![Etcher](https://user-images.githubusercontent.com/25527589/77501075-39164080-6e9a-11ea-9fa6-914912651941.png)

Hello when I try flash hamonikr OS, it display as success but it displays 1 Failed Devices. when I hover the error it displays 'PhysicalDrive2: UNKNOWN: unknown error, write'. Can you look what is happening? I'm using SanDisk Cruzer Blade USB.

**Comment by AhRoon** [comment]
![Etcher2](https://user-images.githubusercontent.com/25527589/77501254-cbb6df80-6e9a-11ea-9d37-63d3214daaf8.png)
Here is the DevTools screenshot. Sorry for forgetting this one.
