### ISSUE TITLE
Home Page MacOS download link unresponsive

### ISSUE THREAD

**Issue by dan003400** [balena-io/etcher#3111]
The homepage download link is not responding for MacOS on the top Hero.

**Comment by mrkapqa** [comment]
same goes for Linux Version

**Comment by mrkapqa** [comment]
downloads can be accessed however from here

https://github.com/balena-io/etcher/releases/

**Comment by lurch** [comment]
@zvin @thundron I'm seeing the same :confused: 
Clicking on the button at the top:
![image](https://user-images.githubusercontent.com/476186/77633774-da0f0500-6f47-11ea-8c00-54777000696f.png)
doesn't do anything.
However the download links further down the page:
![image](https://user-images.githubusercontent.com/476186/77633894-0591ef80-6f48-11ea-84f8-3982a8a15db2.png)
**do** all work correctly.
(i.e. it seems the download links are all okay, it's just the top-button which isn't working properly)

**Comment by zvin** [comment]
Thanks @lurch , it will be fixed quickly.

**Comment by lurch** [comment]
@zvin This is working (for me) again now :+1:
