### ISSUE TITLE
idea - rework the updates

### ISSUE THREAD

**Issue by aindriu80** [balena-io/etcher#3112]
Hi,
I am working remotely and I just noticed that I have Etcher 1.5.77, Etcher 1.5.79 and recently Etcher 1.5.80 added to a download list. Each download is about 134mb in size and there are only a few minor changes.  Is there no smaller patch option.  Re downloading seems inefficient.

**Comment by nainardev** [comment]
yeah same

**Comment by thundron** [comment]
Unfortunately, even the auto-update feature downloads the full package as it's simply how an electron application update works (unless custom-made for this purpose).
We will definitely consider a delta-update approach in the future but right now there are no plans for it
