### ISSUE TITLE
Issue of flashing image located on NAS (WD Mycloud)

### ISSUE THREAD

**Issue by ronwar** [balena-io/etcher#3122]
- 1.580-x64
-Ubuntu Mate desktop 1.20.1 on PC also same compiled for ARM4 
- 125 GB
- **Do you see any meaningful error information in the DevTools?** 

I've tried both machines (PC-dual core and RPI) both show the same result.
Works perfectly on local image file.

**Comment by lurch** [comment]
Yeah, that seems to be a common problem with trying to read an image from a NAS / network drive. See e.g. #2858 and #1436 for more details.
AFAIK the only workaround is to copy the image to a local drive first, before trying to flash it with Etcher.

**Comment by thundron** [comment]
better context in https://github.com/balena-io/etcher/issues/2858, closing
