### ISSUE TITLE
Etcher broke my USB

### ISSUE THREAD

**Issue by Andi7891** [balena-io/etcher#3124]
Etcher version: 1.5.76
Platform: Windows 10 64 bits
Image: Debian for raspberry pi

I tried to flash the latest Raspbian image, but in the end he told me 1 failed device, when i tried to format he gave me this:
![Screenshot_1](https://user-images.githubusercontent.com/64141416/79979933-fe102880-84aa-11ea-8fb4-cbaea595f764.png)
![Screenshot_2](https://user-images.githubusercontent.com/64141416/79979937-ff415580-84aa-11ea-86ad-b529baddeca7.png)
I also tried linux to format it.

**Comment by lurch** [comment]
Do any of the comments / suggestions in #2102 help?

**Comment by Andi7891** [comment]
I tried all

**Comment by thundron** [comment]
Your device either reached it's EOL or was defective in the first place.
Etcher doesn't (and can't, actually) compromise hardware in any way.
Please see [our docs](https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#windows) for some solutions available on different OSes (which I suggest trying, particularly a Linux one).
For a deeper explanation on the subject, there's also a nice post by Rufus [here](https://github.com/pbatard/rufus/wiki/FAQ#help-rufus-damaged-my-flash-drive)

**Comment by Andi7891** [comment]
I used sd card before with 3 minutes and he worked

**Comment by lurch** [comment]
@Andi7891 Possibly you've got a "fake" SD card - I've never had one myself, but from what I understand they work when you try writing a small amount of data to them, but as soon as you try writing a "big" amount of data to them (whether that's using Etcher or Windows Explorer) they then break. You should be able to return your SD card under warranty for a replacement.

**Comment by Andi7891** [comment]
No more warranty and he is hama from a official market
