### ISSUE TITLE
Debian

### ISSUE THREAD

**Issue by passinby** [balena-io/etcher#3136]
is there another name besides balena-etcher-electron that will work?

**Comment by alu18999959g** [comment]
https://github.com/balena-io/etcher/issues/3119#issuecomment-622989049

**Comment by jaedle** [comment]
Sorry for going off topic: @passinby Maybe think about using appropriate language.

**Comment by passinby** [comment]
Shut ur buttfucking dickhead retarded shithole up bitch fuck you
