### ISSUE TITLE
Checksum failed.

### ISSUE THREAD

**Issue by NicTanghe** [balena-io/etcher#3154]
![image](https://user-images.githubusercontent.com/13624265/82077844-5fa96880-96e0-11ea-88b6-4d615389f88c.png)

also windows not dtecting anything in explorer.
and bios is not detecting any usb.

**Comment by rocciuto** [comment]
same problem here, now usb is useless

**Comment by lcsvcn** [comment]
try this:
open cmd and run these commands
1) diskpart
2) list disk
3) select disk <number_of_your_disk>
4) clean
5) create partition primary
6) assign

The usb will appear again and will ask for format.

I am facing the same issue, the usb is not useless, but I cannot flash correctly :/

**Comment by lcsvcn** [comment]
I think this might be a bug, since I see a lots of report of people who tried several times in a row with same hardware, device and image and one time run successfully.

**Comment by rocciuto** [comment]
thanks for reply, unfortunately the metod you posted doesn't work in my case. 
when I type clean, enter
I get
Diskpart error: Access denied.

usb still dead

**Comment by NicTanghe** [comment]
Also, didn't work for me had to download a weird sketchy 3d party disk partitioner, That one worked.

**Comment by lurch** [comment]
Related to #3197 ?

**Comment by thundron** [comment]
@lurch yep
