### ISSUE TITLE
1.5.91 error installing component when recompiling

### ISSUE THREAD

**Issue by btwise** [balena-io/etcher#3172]
1.5.91  run `make electron-develop` error installing component when recompiling, prompt:
```
npm notice created a lockfile as npm-shrinkwrap.json. You should commit this file.
npm WARN lifecycle balena-etcher@1.5.91~postshrinkwrap: cannot run in wd balena-etcher@1.5.91 ts-node ./scripts/clean-shrinkwrap.ts (wd=/Users/btwise/etcher)
make: *** [electron-develop] Error 1
```
How to deal with this problem？

**Comment by thundron** [comment]
@btwise You just need to commit the new `npm-shrinkwrap.json` as the message says, it means there are changes that haven't been committed
