### ISSUE TITLE
UNKNOWN:unknown error read

### ISSUE THREAD

**Issue by Aronlele** [balena-io/etcher#3173]
- **Etcher version:** 1.5.91
- **Operating system and architecture:** windows10 64bit
- **Image flashed:** dmg
- **Do you see any meaningful error information in the DevTools?** 
![image](https://user-images.githubusercontent.com/7881859/82733989-5b1d2980-9d4a-11ea-9221-faf7167a7576.png)
![image](https://user-images.githubusercontent.com/7881859/82733689-1f816000-9d48-11ea-9e59-19253d003b5b.png)
[-1590246557846.log](https://github.com/balena-io/etcher/files/4672011/-1590246557846.log)

**Comment by lurch** [comment]
Sounds similar to #3110 ?

**Comment by Aronlele** [comment]
> Sounds similar to #3110 ?

i don`t know ，hope have a help

**Comment by Aronlele** [comment]
anyone else can help me？

**Comment by zvin** [comment]
@Aronlele this means we couldn't read from the flashed drive for verification.
In general it mean the drive isn't working properly. Try flashing another drive.

**Comment by Aronlele** [comment]
> @Aronlele this means we couldn't read from the flashed drive for verification.
> In general it mean the drive isn't working properly. Try flashing another drive.
I have changed several devices, the one I used at first was able to write normally, but now all devices are not allowed

**Comment by lurch** [comment]
I wonder if "it used to work but now it doesn't" means that a Windows security setting has been changed somewhere? I don't know the full details, but it seems that sometimes "blocks" part of Etcher? :shrug:  (and apologies if this comment is totally irrelevant!)

**Comment by Aronlele** [comment]
> @Aronlele what do you mean with "are not allowed"?

all devices failed

**Comment by Aronlele** [comment]
> I wonder if "it used to work but now it doesn't" means that a Windows security setting has been changed somewhere? I don't know the full details, but it seems that sometimes "blocks" part of Etcher? 🤷 (and apologies if this comment is totally irrelevant!)

Thank u ，but I I run Etcher with administrator rights ， @~@

**Comment by thundron** [comment]
@Aronlele can you try checking Windows's "Controlled folder access" setting?

**Comment by thundron** [comment]
Although it's unlikely because it *should* pop-up as an `EPERM` error iirc, it's worth checking since it worked before

**Comment by OutLore** [comment]
I know this thread is a couple of years old, but I just had the same issue. It was solved by re-installing Etcher with a rightclick-runas admin command. (User was logged on as an admin account, but not the Administrator)... 
When the OP says all devices failed I suspect they mean that when Etcher fails, it leaves the USB devices in an unusable state, not formatted or with a partition, so Windows cannot see them, they have to be manually re-partitioned.
