### ISSUE TITLE
Cannot build properly in a Windows environment

### ISSUE THREAD

**Issue by btwise** [balena-io/etcher#3183]
It works build on MACOS and Linux, but it doesn't build on Windows in all sorts of ways. There are all sorts of weird things that go wrong,Is there a complete tutorial on building in a Windows environment?

**Comment by zvin** [comment]
Same as #3184 
The master branch builds fine on Windows 10.
Remove the `node_modules` folder and run `make electron-develop` or `make electron-build`.
