### ISSUE TITLE
 Win10 build etcher 1.5.94 error

### ISSUE THREAD

**Issue by btwise** [balena-io/etcher#3184]
- **Etcher version:1.5.94 
- **Operating system and architecture:WIN10 1903
- **Image flashed:NONE 
- **Do you see any meaningful error information in the DevTools?NONE 

Win10 build etcher 1.9.54 error, can not build a component, how to solve?
![issues](https://user-images.githubusercontent.com/38809560/83242309-c2196300-a1ce-11ea-9be1-f88ec0d6dde6.PNG)

**Comment by zvin** [comment]
The `master` branch builds fine on Windows 10.
Remove the `node_modules` folder and run `make electron-develop`.
