### ISSUE TITLE
Minor issue: strange button colouring

### ISSUE THREAD

**Issue by lurch** [balena-io/etcher#3193]
- **Etcher version:** 1.5.94
- **Operating system and architecture:** Linux x64
- **Image flashed:** n/a
- **Do you see any meaningful error information in the DevTools?** n/a

If I click on "Flash from file" and then click on "Cancel" in the file-dialog, Etcher then displays "Flash from file" in dark blue text on top of a dark blue background, which looks very odd.
![image](https://user-images.githubusercontent.com/476186/83356750-fe2ffd80-a35f-11ea-9671-ef363f4b814b.png)

Might cause issues for users with low-contrast displays or with visual impairments? :eyeglasses:

**Comment by zvin** [comment]
Fixed in 1.5.96
