### ISSUE TITLE
Windows disc image | BIOS boot message: "No boot sector on USB device"

### ISSUE THREAD

**Issue by Ricky-Tigg** [balena-io/etcher#3211]
- **Etcher version:** balenaEtcher-1.5.98-x64.AppImage
- **Operating system and architecture:** Linux Fedora 32 x86_64
- **Download source of image:** https://www.microsoft.com/en-us/software-download/windows10ISO
- **Image flashed:** Win10_2004_Finnish_x64.iso
- **File properties:** 
```
$ file -b Win10_2004_Finnish_x64.iso 
ISO 9660 CD-ROM filesystem data 'CCCOMA_X64FRE_FI-FI_DV9' (bootable)
```
- **No meaningful error information in the DevTools** 

Run the application:
```
$ ./balenaEtcher-1.5.98-x64.AppImage 
{"stack":"Error: getaddrinfo ENOTFOUND balena.io\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)","message":"getaddrinfo ENOTFOUND balena.io","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"balena.io"}
{"stack":"Error: getaddrinfo ENOTFOUND balena.io\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)","message":"getaddrinfo ENOTFOUND balena.io","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"balena.io"}
ready-to-show: 2165.595ms
```
Those error messages are encountered be the windows server _Wayland_ or _X_.

Since the option _Continue_ is present, click it.

![balenaEtcher-1 5 98-x64_information_Window](https://user-images.githubusercontent.com/26058215/84505743-f4df5300-acc6-11ea-9678-97dafdce02dd.png)

Properties of created device's partition:
```
$ mount | fgrep /run/media/$USER
/dev/sdb on /run/media/yk/CCCOMA_X64FRE_FI-FI_DV9 type udf (ro,nosuid,nodev,relatime,uid=1000,gid=1000,iocharset=utf8,uhelper=udisks2)
```
- On BIOS the image will boot with message "_No boot sector on USB device_".
- On EFI system the device cannot be booted.

For comparison those issues are identical to the ones encountered when DD is used on Linux.

**Comment by thundron** [comment]
As the warning says, flashing windows with Etcher won't make it bootable and we suggest using tools designed for that purpose, such as WoeUSB since you're on Linux
