### ISSUE TITLE
Can't lunch etcher unless using compatibility modes

### ISSUE THREAD

**Issue by sky96111** [balena-io/etcher#3212]
- **Etcher version:** 
1.5.99
- **Operating system and architecture:** 
Windows10 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

Nothing happened when I run it unless I run it with compatibility modes of windows 8.
(1.5.88 works properly)

**Comment by jamincollins** [comment]
Seeing the exact same behavior.
