### ISSUE TITLE
Improve wording in macOS root prompt

### ISSUE THREAD

**Issue by OdysLam** [balena-io/etcher#3216]
FD discussion: https://www.flowdock.com/app/rulemotion/r-etcherprv/threads/dbXVLQSSL1HGayPKvi8oDUfO3-v
Description:  Be more specific on why the user must enter his/her password in order to use Etcher on macOS. This prompt is shown just before the flashing process starts.
![image](https://user-images.githubusercontent.com/13405632/84897734-c7235100-b0ae-11ea-8bfe-17efd303f9b4.png)

**Comment by lurch** [comment]
See also #3067
