### ISSUE TITLE
Checksums in YML don't Match

### ISSUE THREAD

**Issue by we-llsee** [balena-io/etcher#3219]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

Hi, 
I downloaded the last 2 Mac releases ( balenaEtcher-1.5.99-mac.zip and balenaEtcher-1.5.98-mac.zip) from the releases page and neither match with the sha512 in their respective 'latest-mac.yml' files. Please could someone help? 

Cheers

**Comment by lurch** [comment]
https://github.com/balena-io/etcher/issues/2826#issuecomment-500174949 ?

**Comment by we-llsee** [comment]
Thanks @lurch ! Just what I needed 👍
