### ISSUE TITLE
User needs Etcher on macOS to be able to ignore a failed HEAD request and proceed to GET

### ISSUE THREAD

**Issue by AlidaOdendaal** [balena-io/etcher#3223]
User is trying to use a signed AWS s3 link as a URL source for Etcher. However, this fails since the initial HEAD request by Etcher generates a 403. A GET request on the same url is valid and gives an OK 200. @zvin indicated that Etcher could be configured to ignore failed HEAD requests, and proceed to GET in order to flash the medium.

**Comment by alexgg** [comment]
The fix should be tested with a re-signed S3 URL as detailed for example in https://www.msp360.com/resources/blog/s3-pre-signed-url-guide/

**Comment by zvin** [comment]
Implemented in 1.5.101
