### ISSUE TITLE
I am not able to restore bootable usb

### ISSUE THREAD

**Issue by muneebGH** [balena-io/etcher#3224]
- **Etcher version:** 
1.5.100
- **Operating system and architecture:**
Mac OS 
- **Image flashed:** 
ubuntu 18.0
- **Do you see any meaningful error information in the DevTools?** 

it made my usb of 2.some mb. I tried formatting it on windows but it is the same, and on Mac OS it is not picking usb.

**Comment by lurch** [comment]
https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives ?

**Comment by thundron** [comment]
You can follow the guide linked above, there are plenty of other resources on the subject of formatting a drive so that the OS can read it. Closing

**Comment by AsteriskZuo** [comment]
thanks.
