### ISSUE TITLE
Unable to flash USB-C stick

### ISSUE THREAD

**Issue by th4fl4sh4** [balena-io/etcher#3258]
- **Etcher version 1.5.51:** 
- **Operating system and architecture: MacOS Catalina** 
- **Image flashed: tails-amd64-4.8** 
- **Do you see any meaningful error information in the DevTools? I have tried multiple USB sticks. Always the same issue.** 

![Screenshot 2020-07-21 at 18 02 32](https://user-images.githubusercontent.com/48756478/88078366-abfba380-cb7c-11ea-907c-62bb92be5c09.jpg)

**Comment by lurch** [comment]
> Etcher version 1.5.51

There's a much [newer version](https://github.com/balena-io/etcher/releases) available... ?

**Comment by th4fl4sh4** [comment]
Ok thanks, stupid me. It works now.
