### ISSUE TITLE
apt error

### ISSUE THREAD

**Issue by Adam-vk2pwr** [balena-io/etcher#3259]
- *github * 
- **linux mint 20** 
- **Image flashed:none** 
- **Do you see any meaningful error information in the DevTools?no ** 

Err:22 https://dl.bintray.com/etcher/debian stable Release       
  403  Forbidden [IP: 35.161.162.245 443]
Reading package lists... Done
E: The repository 'https://deb.etcher.io stable Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by lurch** [comment]
Another duplicate of #3244

**Comment by Adam-vk2pwr** [comment]
> Another duplicate of #3244

well is there a fix

**Comment by thundron** [comment]
Not yet, but we're working on it. In the meantime you can download through the github releases page here https://github.com/balena-io/etcher/tags
