### ISSUE TITLE
Etcher takes few minutes to start and show GUI on macOS

### ISSUE THREAD

**Issue by jiribrejcha** [balena-io/etcher#3262]
After starting Etcher app, it takes few minutes for its window to actually appear on the screen. After it appears, it then works fine.

- **Etcher version:** 
Version 1.5.101 (1.5.101)

- **Operating system and architecture:** 
macOS Catalina 10.15.6 (19G73)

- **Image flashed:** 
The GUI has not started yet and I can't get to the image flashing dialog

- **Do you see any meaningful error information in the DevTools?** 
No

**Comment by lurch** [comment]
Is this the same as #2740 ?

**Comment by jiribrejcha** [comment]
No, this is different. I see this issue only at startup of the app. After it starts (takes a few minutes), it then works fine and GUI works well and refreshes fast.

**Comment by jiribrejcha** [comment]
It suddenly started working after a few days.
