### ISSUE TITLE
Unable to package using electron-Build

### ISSUE THREAD

**Issue by btwise** [balena-io/etcher#3269]
- **Etcher version:1.5.102
- **Operating system and architecture:WIN10 

The latest 1.5.102 was constructed normally with ` **make electrone-develop**` under WINODWS10 and operated normally with `npm start`, but packaging could not be completed withe **`electrone-build`**. How can we solve the following errors?

![image](https://user-images.githubusercontent.com/38809560/89003639-e0b4eb00-d332-11ea-94f8-868cc1e0b8be.png)

**Comment by shawaj** [comment]
@btwise is there a reason you are compiling yourself rather than just downloading the installer?

And are you using electron-build? Was the extra e at the end of electron in the above comment?

**Comment by lurch** [comment]
Looking at the screenshot, I wonder why it's trying to run `bash` on Windows? :shrug:
