### ISSUE TITLE
balenaEtcher connects to external servers without asking the user

### ISSUE THREAD

**Issue by ISCEIRVEREPLEC** [balena-io/etcher#3271]
- **Etcher version: 1.5.102 https://github.com/balena-io/etcher/releases/tag/v1.5.102** 
- **Operating system and architecture: Windows 7** 

Hello,

I noticed when I used the portable version, this software connected automatically to external servers without any hint. I have also disabled 2 options under settings: 

- Anonymously report errors and usage statistics to balena.io

- Auto-updates enabled

Nevertheless it connects to external servers automatically in the background for example when starting the software or the flashing is finished. 

Create a portable version where it is an offline tool immediately after first starting. You can also add a setup, where the users can decide.

**Comment by thundron** [comment]
@ISCEIRVEREPLEC We make some connections to our own servers to provide the online content that you see while flashing & at the success screen. You'll still see those connections regardless of analytics/auto-updates as we're not considering a stand-alone offline version of Etcher yet, though it works even when there's no connectivity just as well.
