### ISSUE TITLE
Etcher not showing up on macOS Catalina

### ISSUE THREAD

**Issue by t0mm4rx** [balena-io/etcher#3278]
- **Etcher version:** 1.5.102
- **Operating system and architecture:** macOS Catalina 10.15.3
- **Image flashed:** None
- **Do you see any meaningful error information in the DevTools?** DevTools are blank

Hello,
I'm trying to use Etcher on macOS, but when I launch the app nothing happen.
I've checked devtools, it's blank.
I've tried running the app as sudo, nothing happen, the terminal is blank too.
When I click on "Show all windows", it says there is none.
Other Electron apps are working well on my computer.

Edit: I can't quit the app, it's unresponsive so I need to kill it manually or via force quit.

**Comment by shawaj** [comment]
Could you try with the latest version v1.5.112 @t0mm4rx ?

https://www.balena.io/etcher/

**Comment by t0mm4rx** [comment]
It's working !

**Comment by shawaj** [comment]
@t0mm4rx awesome thanks for the update!
