### ISSUE TITLE
Cannot select drive.

### ISSUE THREAD

**Issue by DawiDMAJAJA3** [balena-io/etcher#3280]
- **Etcher version:** v1.5.103
- **Operating system and architecture:** Win10 (64)
- **Image flashed:** I did not flash image. 
- **Do you see any meaningful error information in the DevTools?** No

So basically, when I want to boot up with Kaspersky Rescue Tool, I cannot select drive (Screenshot). Help would be appreciated.

![image](https://user-images.githubusercontent.com/69955940/90726362-e06c9780-e2c1-11ea-9a15-8b7414308ad6.png)

**Comment by thundron** [comment]
You're trying to flash your system drive, which is dangerous unless *you know what you're doing*, and in this case it's the source of your image so you can't use it as a target.

**Comment by sajolida** [comment]
Let's see if we can fix the root cause of bad feedback on #3662.
