### ISSUE TITLE
Windows 10 - Settings can‘t be changed

### ISSUE THREAD

**Issue by Mr-ph422** [balena-io/etcher#3282]
balea etcher version: 1.5.103 installer
Windows 10: 2004/19041.450

Hey I can't change any settings.

![image](https://user-images.githubusercontent.com/46573822/90801357-19365c00-e316-11ea-8438-949e3fe613cc.jpeg)

When you need information from me, let me know it :)

**Comment by thundron** [comment]
Thanks for the quick report, we have a PR to fix the issue [here](https://github.com/balena-io/etcher/pull/3281/commits/a24be20e952ac041755b8e29c84cd72d1149d6c9) and another issue to track for completion -> https://github.com/balena-io/etcher/issues/3279#issuecomment-677433840
Closing this one
