### ISSUE TITLE
deletes volume

### ISSUE THREAD

**Issue by ckugel** [balena-io/etcher#3294]
- **version: 1.5:107** 
- **OS and arhitecture: Windows 10 on zen 2 x86** 
- **image(s): Manjaro-Kde also on XFCE** 
- **Do you see any meaningful error information in the DevTools?: no** 

It deletes the volume of the device I try to flash and then says there was an unexpected error

**Comment by shawaj** [comment]
@ckugel were you trying to clone a device or flash an image to it from file?

Can you try with v1.5.112 the latest version and see if you still have the same issue?
