### ISSUE TITLE
Add storage device reading to create image file

### ISSUE THREAD

**Issue by fralbo** [balena-io/etcher#3298]
That will prevent to also have Win32DiskImager to read a device.

**Comment by thundron** [comment]
This is something that is being actively worked on, we *just* released a new functionality (in the form of a handy button) to clone a drive into another drive and the same principle will be used to create a "Backup" functionality to copy a drive's content into a file.
Please follow [the original issue](https://github.com/balena-io/etcher/issues/266) to know when we will be done
