### ISSUE TITLE
Native support for Apple silicon (without using Rosetta)

### ISSUE THREAD

**Issue by sradevski** [balena-io/etcher#3300]
This is a placeholder issue for all the things that we might need to change to support Apple silicon natively once it's released.

**Comment by thundron** [comment]
Electron devs are already on track with it https://github.com/electron/electron/issues/24319 so hopefully we won't need to change too many things, I think we haven't got many dependencies other than maybe `drivelist` which *could* need an upgrade, *if* some native calls change.
We'll see how it evolves, keeping this issue open for tracking purposes

**Comment by thebitstick** [comment]
Apple Silicon Macs released a week ago, and Electron updated with support as well.

**Comment by fluxtransistor** [comment]
It's been a little while, any word on the progress here?

**Comment by thundron** [comment]
@fluxtransistor there are some bugs on electron 11 that prevent us upgrading, so it will need some more time until those issues are resolved (see e.g. https://github.com/electron/electron/issues/25425 )

**Comment by fluxtransistor** [comment]
Alright, thanks!

**Comment by thedocbwarren** [comment]
Seems like they have a workaround.  Is this something that can be implemented or part of an alpha to test this out?  My concern is running through rosetta that has device access.

**Comment by lurch** [comment]
Apparently this is being added in #3432

**Comment by fishcharlie** [comment]
@thundron Why was this closed? It was **not** fixed in #3432. As of v1.6.0 the build is still Intel only. Can we reopen it to draw attention to the fact that this is not resolved?

**Comment by thundron** [comment]
There was likely a regression which we are trying to figure out in the latest build so the issue is definitely not the same, @fishcharlie could you please check v1.5.122 for that matter? We also have reports of 1.6.0 still working with rosetta without emulation, despite not being tagged as so in the file information and I'm trying to gather as much information as possible

**Comment by fishcharlie** [comment]
@thundron Still Intel only.

<img width="252" alt="Screen Shot 2021-11-08 at 8 15 41 AM" src="https://user-images.githubusercontent.com/860375/140767764-8737dea5-81de-4b51-a7ac-07aead9a2070.png">

**Comment by lurch** [comment]
Links to #3593

**Comment by gandalfwfh** [comment]
2023 still rosetta rocks, users with no rosetta can use only stock apple software

**Comment by trigger2k20** [comment]
July 2023 still rosetta, why ?

**Comment by shareef777** [comment]
The latest Apple Silicon supported version is 1.5.121. Support seems to have been dropped after that.

**Comment by trigger2k20** [comment]
But why ? this is not very logical.

Mit freundlichen Grüßen
Sascha Afkhampour

***@***.***
