### ISSUE TITLE
Add Ability In-App Updates

### ISSUE THREAD

**Issue by TurannUl** [balena-io/etcher#3302]
- **Etcher version:** 1.5.102
- **Operating system and architecture:** MacOS 11.0 x86_64
- **Image flashed:** yes
- **Do you see any meaningful error information in the DevTools?** there no error Just request I like your Project

**Comment by lurch** [comment]
Duplicate of #336 ?

**Comment by TurannUl** [comment]
Maybe I'dont readed #336, Only Askin

**Comment by thundron** [comment]
Yep @lurch , closing
