### ISSUE TITLE
microSD has lowered capacity

### ISSUE THREAD

**Issue by TerWebz** [balena-io/etcher#3308]
- **Etcher version:** 1.5.109
- **Operating system and architecture:** Windows 10 64-bit
- **Image flashed:** Pop_OS! (NVIDIA)
- **Do you see any meaningful error information in the DevTools?** No

My 32GB microSD drops to 4 GB after flashing the card, is there any way to make it full capacity or is this a Pop!_OS issue?

**Comment by thundron** [comment]
The 4GB partition is the only partition your OS can read. There *may* be other partitions your OS is unable to read, you should see the full size if you check the drive with the drive management application
