### ISSUE TITLE
Why aren't you using the system password dialog?

### ISSUE THREAD

**Issue by aaronraimist** [balena-io/etcher#3309]
- **Etcher version:** 1.5.109
- **Operating system and architecture:** macOS 10.15.6

I just upgraded to version 1.5.109 from a version several months old and now the password dialog has changed from:

<img width="555" alt="Screen Shot" src="https://user-images.githubusercontent.com/5855073/94214574-8736eb80-fe9f-11ea-9efd-15e28768fdd5.png">

to this nonstandard password dialog:
<img width="532" alt="Screen Shot" src="https://user-images.githubusercontent.com/5855073/94213139-bea39900-fe9b-11ea-9800-f34ba516891e.png">

It feels **very sketchy**. Why aren't you using the system password dialog?

**Comment by lurch** [comment]
It's a Catalina thing - see https://github.com/balena-io/etcher/issues/3107#issuecomment-602047807

**Comment by thundron** [comment]
Correct, see the other issues for more info. Closing
