### ISSUE TITLE
Loosing data while copy from one SD card to another

### ISSUE THREAD

**Issue by adasiko** [balena-io/etcher#3314]
- **Etcher version: v1.5.109** 
- **Operating system and architecture: Windows 10 64 bit** 
- **Image flashed: Ubuntu Server for Raspberry Pi** 
- **Do you see any meaningful error information in the DevTools?: no**

Source SD card size is 16 GB and destination SD card is 32 GB.
Cloning process and verification successfully anded and source SD card partition is empty and destination SD is too...

**Comment by JoschaHemlep** [comment]
I have the same problem, with the same Etcher version, same Operating system. On the source SD Card 16gb was/is raspbian (buster), the target 128gb card was empty. Source card doesn't boot anymore :-( 
No errors/warning during cloning and validation process.

Is there a chance to recover the source card without formatting?

**Comment by zvin** [comment]
@adasiko @JoschaHemlep there was a bug in Etcher 1.5.106 - 1.5.110 that remove the partition table on Windows.
If you know how your SD card was partitioned, you can recover the data by recreating the partition table.

**Comment by lurch** [comment]
> there was a bug in Etcher 1.5.106 - 1.5.110 that removed the partition table on Windows.

Ooops! :cry:  I guess that explains a few of the "ranty" bug-reports that have been seen.

**Comment by adasiko** [comment]
Version 1.5.111: works as expected.
