### ISSUE TITLE
I just downloaded etcher on my desktop . Devuan linux . 3 , from etcher.io today. Ran the setup and tried to open the software. Nothing happens

### ISSUE THREAD

**Issue by sad1234** [balena-io/etcher#3318]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment]
I don't work on Etcher myself, but it would probably be useful if you clarified exactly which file you downloaded, and exactly how you "ran the setup" ?

**Comment by sad1234** [comment]
Etcher 1.5.1 09 - x 64
Devuan linux 3.0
No. It juist extract it. It asks with wich software can open it, but i can not find unzip.

**Comment by shawaj** [comment]
@sad1234 so you are having trouble unzipping the file?

**Comment by sad1234** [comment]
Not any more . Thanks.23.11.2020, 17:01, "Aaron Shaw" <notifications@github.com>:
@sad1234 so you are having trouble unzipping the file?

**Comment by shawaj** [comment]
@sad1234 so you have managed to get it installed ok? We can close the issue?

**Comment by sad1234** [comment]
Yes. Thanks.23.11.2020, 22:19, "Aaron Shaw" <notifications@github.com>:
@sad1234 so you have managed to get it installed ok? We can close the issue?
