### ISSUE TITLE
stuck on W10 on Starting...

### ISSUE THREAD

**Issue by firexx** [balena-io/etcher#3328]
- **Etcher version:** 1.5.109
- **Operating system and architecture:** Win 10 pro
- **Image flashed:** *.wic
- **Do you see any meaningful error information in the DevTools?** no

![image](https://user-images.githubusercontent.com/16118459/96419344-4c04af80-11f4-11eb-8716-625604811815.png)

**Comment by dragonDScript** [comment]
Have you tried to reload the window/app and try again? Do you see any uncaught promise in the devtools? Have you tried to start as Admin?

**Comment by firexx** [comment]
I tried it more times, and also as admin.

dragon script <notifications@github.com> schrieb am Sa., 24. Okt. 2020,
22:42:

**Comment by dragonDScript** [comment]
Ok, so these programs fail sometimes.
Try to use dd

**Comment by BarryOCathain** [comment]
For info, I was stuck on this issue as well. Ran as admin, and it worked first day.

**Comment by 1435thundercloud** [comment]
1. hangs for ever lol so i exacted the portable 1.5.115 into a folder. 
2. then portable 1.5.45 into another 
3. 3.then copied all api.dlls from the portable 1.5.45 ver into the 1.5.115 directory.
4. now 1.5.115 starts instantly.
