### ISSUE TITLE
Balena Etcher can't access USB and says it's locked ChromeOS

### ISSUE THREAD

**Issue by dragonDScript** [balena-io/etcher#3332]
- **Etcher version:** 1.5.109
- **Operating system and architecture:** ChromeOS x64 Running Linux
- **Image flashed:** Ubuntu 20.04.1 LTS
- **Do you see any meaningful error information in the DevTools?** No 

Ok, so I have a chromebook and my main PC with Windows was corrupted, so I want to install it Linux. But when trying to select a device, it says that my USB is "locked" like the following image:
![image](https://user-images.githubusercontent.com/46191980/97093073-779af600-1649-11eb-9b94-573b751bc169.png)
Linux has access to the image, like you see in the following:
![image](https://user-images.githubusercontent.com/46191980/97093109-a9ac5800-1649-11eb-8622-4f714ce04e70.png)
What can I do?
Thank you

**Comment by dragonDScript** [comment]
Sorry if you've seen typos, I don't talk a lot of english. Please correct me if you see anything!

**Comment by lurch** [comment]
See #1643 and https://github.com/raspberrypi/rpi-imager/issues/92

**Comment by dragonDScript** [comment]
Ok, so I've fixed this by renaming hte .iso to .bin and by using the default Chrome OS program to to this. Thank you.

**Comment by Kentrelle** [comment]
I also have the same problem. Balenaetcher can only read the USB flash drive and cannot find the USB device.in chromebook
