### ISSUE TITLE
tails-amd64-4.12.iso unsupported

### ISSUE THREAD

**Issue by skulldealer** [balena-io/etcher#3334]
- **Etcher version:*latest* 
- **Operating system and architecture:*windiws 10 home 64 bit* 
- **Image flashed:*tails-amd64-4.12.iso*  
- **Do you see any meaningful error information in the DevTools?*no* 

### 

please check tails-amd64-4.12.iso not recognizing on bios.

**Comment by thundron** [comment]
If the flash was successful, it likely means that the image is not bootable by itself and you need to do something else (outside of Etcher) to make it bootable, assuming that's what you're trying to do.
If you were following a guide, please check it again to confirm that Etcher is the right tool to use for flashing tailsOS.
