### ISSUE TITLE
Publish SHA/MD5 sums for all versions of the downloads, including portable.

### ISSUE THREAD

**Issue by richbayliss** [balena-io/etcher#3341]
Users keep notifying us that the portable Etcher download is getting flagged as infected by some AV software.

We should publish the SHA/MD5 hashes for all versions (portable is not published) so that users can confirm them and give them confidence to disregard the AV warning.

**Comment by ealmonte32** [comment]
and I thought this was already listed on the `latest.yml` file for each platform... i tried to base64 decode the sha512 hash because that string is not sha512, and I get gibberish when doing so..

**Comment by lurch** [comment]
See https://github.com/balena-io/etcher/issues/2826#issuecomment-500174949
