### ISSUE TITLE
I am not able to unistall

### ISSUE THREAD

**Issue by Thegamer24-7** [balena-io/etcher#3344]
- **Etcher version:** 
- **Operating system and architecture:** windows 10
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by shawaj** [comment]
Have you tried uninstalling from [the windows uninstall or remove programs dialogue](https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98#:~:text=In%20the%20search%20box%20on,the%20directions%20on%20the%20screen.)

If you are using the "portable" version of Etcher then you can just delete the file - as it is not "installed" anywhere.

**Comment by shawaj** [comment]
@Thegamer24-7 not heard back in 2 weeks so closing now.

Feel free to reply if you're still having issues.
