### ISSUE TITLE
Empty window

### ISSUE THREAD

**Issue by LubomirKovalcik** [balena-io/etcher#3349]
- **Etcher version: 1.5.109** 
- **Operating system and architecture: Windows 7 x64** 
- **Image flashed: any** 
- **Do you see any meaningful error information in the DevTools? DevTools is empty** 

Freshly installed etcher, after opening only shows empty window. DevTools is also empty.

**Comment by lurch** [comment]
Possibly related to #1866 ?

**Comment by zvin** [comment]
@LubomirKovalcik try installing this https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by thundron** [comment]
please see https://github.com/balena-io/etcher/issues/1866
