### ISSUE TITLE
Tails Balena etcher cant select flash drive 

### ISSUE THREAD

**Issue by BidenLovesMinors** [balena-io/etcher#3357]
- **Etcher version:1.5.105 macOS

- **Image flashed: tails-amd64-4.13.img 

Whenever i go and try and select the drive it wont let me even select it i dont know if im just dumb or what.

<img width="784" alt="Screen Shot 2020-11-23 at 1 13 03 AM" src="https://user-images.githubusercontent.com/74898100/99940288-c1b7ea00-2d63-11eb-9790-798109b5fff3.png">

 `Cmd+Opt+I` if you're on macOS. -->

**Comment by lurch** [comment]
I'm not an Etcher developer, but I think the "Source drive" label might mean that the `tails-amd64-4.13.img` image you're trying to flash is stored on your "Lexar USB Flash Drive Media"? You can't read from the drive at the same time you're overwriting it :wink:  If my guess is correct, the problem should go away if you copy the image file to your HardDrive and select it from there instead?

**Comment by thundron** [comment]
That means you're trying to select a target that contains the source image that you selected.
As @lurch mentioned, try copying the image on a different drive so you can select the target you need to flash.
Just keep in mind that the content of the target will be entirely replaced by the content of the image

**Comment by sajolida** [comment]
Let's see if we can fix the root cause of bad feedback on #3662.
