### ISSUE TITLE
Privilege Elevation Fails with Non-Admin Account on MacOS

### ISSUE THREAD

**Issue by pahowes** [balena-io/etcher#3369]
Very simply, I log into my Mac with an unprivileged account. it does not have sudo access or administrative rights at all. the new balenaEtcher UI only asks for a password, but not a username. This is in stark contrast to every other macOS application which prompts for both when elevating. The only way I can use this application is by switching over to another user that does have admin rights. This is an unacceptable oversight.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/56945/100469129-b5a19480-30a3-11eb-946f-6ae10b7699f5.png">

**Comment by lurch** [comment]
I believe it's a "known problem" with Catalina, see e.g. https://github.com/balena-io/etcher/issues/3107#issuecomment-602047807

**Comment by thundron** [comment]
We're aware of the discrepancy, but are currently unable to work on it. For more info please look at https://github.com/balena-io/etcher/issues/3321#issuecomment-707352408

As stated there, PRs are welcome!
