### ISSUE TITLE
Unable to flash to USB Sandisk Cruzer Glide 2.0 16GB Flash Drive

### ISSUE THREAD

**Issue by Erobles23** [balena-io/etcher#3378]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment]
>     * **Etcher version:**

???

>     * **Operating system and architecture:**

???

>     * **Image flashed:**

???

>     * **Do you see any meaningful error information in the DevTools?**

???

**Comment by Erobles23** [comment]
I actually got passed all of that and I just shut down my computer, then held Command and chose "no security" and allowed booting from external media but after that I'm stuck. my computer just keeps going back to my usual account and starting up normally. What am I doing wrong?

**Comment by shawaj** [comment]
@Erobles23 you haven't provided any of the requested information so it's very difficult to answer you.

Can you provide the requested information:
Etcher version:
Operating system and architecture:
Image flashed:
Do you see any meaningful error information in the DevTools?

**Comment by shawaj** [comment]
@Erobles23 any update here?

**Comment by lurch** [comment]
Perhaps @Erobles23 is just looking for https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#why-is-my-drive-not-bootable ? :wink:  (perhaps trying a different image-flashing tool will create a USB disk that his BIOS is actually able to boot?)

**Comment by autumnadagio** [comment]
@Erobles23 I just flashed this exact USB drive with no issues, so I don't think it's the USB...

**Comment by shawaj** [comment]
Will close this issue as no reply from @Erobles23
