### ISSUE TITLE
I can't Flash the "jetson-nano-4gb-jp441-sd-card-image" to the drive

### ISSUE THREAD

**Issue by Flyooofly** [balena-io/etcher#3387]
- **Etcher version:** the most new version 1.5.45
- **Operating system and architecture:** windows10
- **Image flashed:** jetson-nano-4gb-jp441-sd-card-image
- **Do you see any meaningful error information in the DevTools?** No
I have checked the interfate is usb3.0 and I don't know why I can't success

![image](https://user-images.githubusercontent.com/31236750/102707425-c37abc00-42d5-11eb-936d-f5f1472c210b.png)
![image](https://user-images.githubusercontent.com/31236750/102707523-bf9b6980-42d6-11eb-8f2d-fe047022a556.png)

**Comment by lurch** [comment]
> Etcher version: the most new version 1.5.45

You're only "seeing" that as the newest version because you've got javascript turned off! Either turn on JavaScript for the Etcher website, or download the latest version from https://github.com/balena-io/etcher/releases

**Comment by Flyooofly** [comment]
> > Etcher version: the most new version 1.5.45
> 
> You're only "seeing" that as the newest version because you've got javascript turned off! Either turn on JavaScript for the Etcher website, or download the latest version from https://github.com/balena-io/etcher/releases

Oh my god..I'm stupid..It works ,thank you!

**Comment by lurch** [comment]
@thundron @zvin @shawaj There have been several times this has happened now... perhaps it's either worth updating the Etcher version displayed on the no-javascript version of the Etcher website to a more recent version; or maybe add some wording to the no-javascript version of the website to say that it's probably an old version, and if users are having problems they should see if there's a later version available at https://github.com/balena-io/etcher/releases ? (or maybe just add some text telling users that they should turn on javascript to see the latest Etcher version??)

According to https://github.com/balena-io/etcher/blob/master/CHANGELOG.md Etcher v1.5.45 was released over 18 months ago!!!

**Comment by shawaj** [comment]
@lurch good idea - only issue is I don't know how the etcher.io page is updated with a default version.

@zvin @thundron any idea about this?

**Comment by shawaj** [comment]
See #3380

**Comment by thundron** [comment]
we have a PR that updates the fallback version to one more recent, but maybe an additional message is better so that we also instruct the user that it's an old version regardless

**Comment by shawaj** [comment]
@thundron is that page generated in a different repo?

Definitely think that would be good about mentioning it may be an old version.
