### ISSUE TITLE
etcher causing windows to become unresponsive and requires reboot

### ISSUE THREAD

**Issue by sabotagebeats** [balena-io/etcher#3391]
- **Etcher version:** 1.5.113
- **Operating system and architecture:** windows 10, i5 processor, 32gb ram
- **Image flashed:** ubuntu pi LTS server from official ubuntu site
- **Do you see any meaningful error information in the DevTools?** devtools doesn't open

**Comment by shawaj** [comment]
@sabotagebeats are you using the portable or the installed .exe?

**Comment by sabotagebeats** [comment]
I had this problem for both. I think this was connected to issue I was having with detected as ransomware
