### ISSUE TITLE
Unable to scroll drive list

### ISSUE THREAD

**Issue by mauricev** [balena-io/etcher#3395]
- **Etcher version:** 
- 1.5.113
- **Operating system and architecture:** 
- 10.14.6
- **Image flashed:** 
- affects all images

This bug has been reported twice before 
https://github.com/balena-io/etcher/issues/789
https://github.com/balena-io/etcher/issues/202

So it apparently had been fixed at one point, but now it's back.

See this picture:

![Screen Shot 2020-12-24 at 10 32 50 PM](https://user-images.githubusercontent.com/417110/103117411-471b0c80-4638-11eb-866f-9cbd11f34b4e.jpg)

It's actually three bugs. There is no scroll bar. Up and down arrows don't work and it shows drives that we never use, even labeling them "large drives".

**Comment by thundron** [comment]
You can use the mouse wheel or a touch screen to scroll the list

**Comment by thundron** [comment]
As for the large drives, we can't possibly know if you use them or not. Etcher shows all available drives

**Comment by lurch** [comment]
"You can use the mouse wheel or a touch screen to scroll the list" - I guess that doesn't help people who have neither a touch screen nor a mouse wheel? :thinking:

**Comment by thundron** [comment]
Is it actually possible to have a mouse without a wheel? 🤔  I just assumed it's a standard feature nowaday, isn't it?

**Comment by mauricev** [comment]
Ah, it’s a broken interface. I would have never guessed to use the scroll on the mouse.
