### ISSUE TITLE
Attempting to write boot-able usb, program can not recognise Linux Mint.iso!

### ISSUE THREAD

**Issue by Wolfy169** [balena-io/etcher#3401]
- **15.113** 
- **Linux Mint 19.3,amd64** 
- **NO, THAT IS WHY I'M HERE!** 
- **Again, I'm reporting the issue!**

**Comment by lurch** [comment]
I suspect you'll need to provide a more detailed description of your problem, if the Etcher developers are going to be able to help you?

**Comment by Wolfy169** [comment]
Please explain, why all other versions of "Etcher", I have used say "SELECT IMAGE", this one says "SELECT FILE"!!!! Therefore "PROGRAM HAS NO HOPE", OF CREATING :BOOT-ABLE USB"!!! My "Complaint, ALL ALONG"!!!!!!!!!!!!!!!!!!!!!!

**Comment by Wolfy169** [comment]
I BELIEVE "DEVELOPERS", HAVE "SCREWED UP"!!!!!
