### ISSUE TITLE
Balena-Etcher no longer working on fresh Debian Bullseye install, missing libappindicator1

### ISSUE THREAD

**Issue by sammycda** [balena-io/etcher#3406]
I tried to install BalenaEtcher from the .deb on Debian Bullseye and get the following error message: “The following packages have unmet dependencies:
balena-etcher-electron : Depends: libappindicator1 but it is not installable”.

“libappindicator1” is no longer available in the Debian Bullseye repositories.

A "sudo apt -f install" doesn't find and install it either.

Thanks for your help!

Sam

**Comment by markcorbinuk** [comment]
Looks like Debian has dropped `libappindicator` in favour of `libayatana-appindicator`. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037
