### ISSUE TITLE
E: The repository 'https://deb.etcher.io stable Release' is not signed.

### ISSUE THREAD

**Issue by swipswaps** [balena-io/etcher#3422]
- **Etcher version:** 
- **Operating system and architecture:** 
MX Linux
Linux mx 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+mx17+1 (2019-11-17) x86_64 GNU/Linux
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by Tim-Hobbes** [comment]
You probably forgot to trust Bintray.com's GPG key. This can be done by running this command: `sudo apt-key adv --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys 379CE192D401AB61`

**Comment by thundron** [comment]
correct, duplicate of https://github.com/balena-io/etcher/issues/2187, closing

**Comment by Bkroland19** [comment]
didnt get a solution

**Comment by lurch** [comment]
@Bkroland19 AFAIK https://deb.etcher.io shouldn't be used any more. See #3501
