### ISSUE TITLE
UI not updated/displayed

### ISSUE THREAD

**Issue by VolkerBartheld** [balena-io/etcher#3443]
- **Etcher version: 1.5.116 (Portable)** 
- **Operating system and architecture: Windows 7x64 SP1 Windows Classic Theme** 
- **Image flashed: linuxmint-19.1-mate-64bit.iso** 
- **Do you see any meaningful error information in the DevTools? DevTools shows no UI either** 

After starting etcher, I just see the bare Window frame with title bar, minimize and close buttons. The client area just shows what was on the desktop before. If I click around blindly in the client area, eventually the "Open image file" dialog is displayed, where I selected my image (linuxmint-19.1-mate-64bit.iso). But of course, I'm stuck there, unable to see any other UI items. Might have something to do with the Windows Classic theme. Etcher seems quite fine though: 5 processes, no excessive CPU consumption. Might similar to #3431, just a different description.

This is probably a duplicate of #1866. Feel free to close this issue if necessary.

See attached screenshots:
![20210225_084312_capture](https://user-images.githubusercontent.com/12848904/109119892-8ef80600-7745-11eb-9e4d-b00d9397cb48.png)
![20210225_084700_capture](https://user-images.githubusercontent.com/12848904/109120304-12195c00-7746-11eb-8c96-423b1b104330.png)

**Comment by thundron** [comment]
please see https://github.com/balena-io/etcher/issues/1866
