### ISSUE TITLE
Feature Request: Flash hybrid image using cdrom ISO

### ISSUE THREAD

**Issue by kmcm0** [balena-io/etcher#3450]
When detecting a non-bootable ISO, attempt to hybridize the iso image to make it bootable via usb.

**Comment by lurch** [comment]
Doesn't that depend on the OS in the ISO though? :shrug:  See https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#why-is-my-drive-not-bootable and https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos

**Comment by thundron** [comment]
Etcher by design doesn't modify images, it just flashes byte-to-byte whatever the content of the image is and then verifies it. We have plans to configure images but that's unrelated to making hybrid ISOs
