### ISSUE TITLE
mu4e in emacs loads emails in Etcher instead of web browser

### ISSUE THREAD

**Issue by kenna-smith** [balena-io/etcher#3453]
- **Etcher version:** unknown
- **Operating system and architecture:** unknown 

Originally reported in Forums:
https://forums.balena.io/t/typing-a-then-v-in-mu4e-plain-text-email-to-view-email-in-html-tries-to-load-the-html-file-in-balena-etcher-rather-than-default-web-browser/266418

When running mu4e within emacs (v28.5 org-mode), if customer tries to use the keybinding `a + V` (to view his email in plain text instead of HTML), the email attempts to load in Etcher instead of their default web browser. 

There appear to be other reported issues of this, initiated by other programs though:
* https://github.com/balena-io/etcher/issues/3404
* https://github.com/balena-io/etcher/issues/3374

It also appears to occur with other Electron-based apps, so does not appear to be an Etcher-specific issue:
* https://github.com/electron/electron/issues/20382
* https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/180

**Comment by thundron** [comment]
There's not much we can do unfortunately, it's up to either Electron to use a different package or xdg-utils to fix the issue. We can reopen in the future if we need
