### ISSUE TITLE
Different version specified in download compared to application

### ISSUE THREAD

**Issue by danPudwellUK** [balena-io/etcher#3455]
Downloaded the latest version from the website, v1.5.116 for MacOS
However after installing it says I have 1.4.4
<img width="625" alt="Screenshot 2021-03-11 at 15 51 15" src="https://user-images.githubusercontent.com/12623808/110814749-a8d73400-8281-11eb-9acc-5438ce38474f.png">
<img width="784" alt="Screenshot 2021-03-11 at 15 51 53" src="https://user-images.githubusercontent.com/12623808/110814816-b8ef1380-8281-11eb-8e30-a1fe37422aee.png">

**Comment by lurch** [comment]
You must have both the old version and the new version installed, and somehow you're still running the old version. Note that the old version was "resin.io Etcher" but the new version is "balenaEtcher".

**Comment by thundron** [comment]
as @lurch said, please check for old versions on your system and remove them if necessary
