### ISSUE TITLE
l'avvio si ferma e mi chiede la password di home assistant. ancora devo configurare home assistant, che password devo dare?

### ISSUE THREAD

**Issue by sergio19021953** [balena-io/etcher#3461]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by thundron** [comment]
Buongiorno, non saprei cosa sia home assistant ma non è correlato a Etcher, mi spiace.
Provi a vedere su https://www.home-assistant.io/
