### ISSUE TITLE
etcher not installing on Arch Linux

### ISSUE THREAD

**Issue by Enjoy-Maity** [balena-io/etcher#3462]
- **Etcher version:**  latest
- **Operating system and architecture:**  Arch Linux 2021
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

It takes forever and then the package build fails. It shows

[0:03:00] Still working on:
[0:03:00]   src/third_party/electron_node
[0:03:00]   src/chrome/test/data/xr/webvr_info
[0:03:00]   src/third_party/angle
[0:03:00]   src/third_party/boringssl/src
[0:03:00]   src/third_party/breakpad/breakpad
[0:03:00]   src/third_party/catapult
[0:03:00]   src/third_party/chromite
[0:03:00]   src/third_party/cld_3/src
 and keeps on going
and does not finish making the build.

**Comment by lurch** [comment]
Sounds like a problem with the ArchLinux etcher-build-script, which IIRC is maintained by a 3rd party?

**Comment by Enjoy-Maity** [comment]
> Sounds like a problem with the ArchLinux etcher-build-script, which IIRC is maintained by a 3rd party?

i actually don't know, I have tried installing balena etcher using yay , git clone 
and even tried installing different dependencies one by one before making the build, but every time it returns something like this.

**Comment by lurch** [comment]
Have you tried using the AppImage instead?

**Comment by Enjoy-Maity** [comment]
appimage is working fine

**Comment by thundron** [comment]
If using the AppImage isn't feasible for any reason, I would suggest to refer to the owner of the distribution channel that you installed Etcher from as Arch is supported by the community
