### ISSUE TITLE
Bintray is shutting down- need to migrate Deb and RPM repos

### ISSUE THREAD

**Issue by mattfox** [balena-io/etcher#3466]
Bintray, [hosting the Deb and RPM repos](https://bintray.com/etcher), is [shutting down on May 1st](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

The repos are still referenced in the docs here: https://github.com/balena-io/etcher#installers .

Is there a plan to migrate to new repository hosting?

If there's not already a plan, I'd like to discuss offering my service [Balto Repo](https://www.getbalto.com/), which offers Debian repos now and I'll be adding RPM in the very near future (before May 1). My only concern is the network transfer- I can't realistically offer unlimited transfer so it would be useful to get a ballpark downloads/month from the existing Bintray repos. The [Bintray repos](https://bintray.com/etcher/debian/etcher#statistics) publish stats about the mix of download versions but nothing about the total numbers. (Or of course Balena could get a paid plan.)

I threw together a quick example Debian repo here: https://balena.baltorepo.com/etcher/debian/

**Comment by thundron** [comment]
please see https://github.com/balena-io/etcher/issues/3501
