### ISSUE TITLE
failed to flash ubuntu drive even when using URL (checked USB space)

### ISSUE THREAD

**Issue by Guy-with-p0tato-pc** [balena-io/etcher#3470]
- **Etcher version:** 1.5.116
- **Operating system and architecture:** Windows 10 x64
- **Image flashed:** ubuntu-20.04.2.0-desktop-amd64.iso
- **Do you see any meaningful error information in the DevTools?** No.

**Comment by Nmatt1** [comment]
HI there. 

Other then using a different version of Ubuntu (20.04.3LTS for example) I don't really know what to say. Download the ISO and run it locally instead of trying clone from URL.
