### ISSUE TITLE
Why Does Etcher Keep Associating Itself With HTML and HTM files!?

### ISSUE THREAD

**Issue by rebeltaz** [balena-io/etcher#3487]
- **Etcher version:** v1.5.100
- **Operating system and architecture:** Ubuntu 18.04 LTS 64-bit

Every time I run etcher, it makes itself the default program for HTML and HTM files. WHY?! I can reset that in system settings and everything is fine until I run etcher again, then I have to go back in and reset the program again.,

**Comment by lurch** [comment]
Duplicate of #3374
