### ISSUE TITLE
only v1.5.116 (not latest 1.5.119) is available for download

### ISSUE THREAD

**Issue by ksdomino** [balena-io/etcher#3505]
How can I get the latest version, or is it not available for mac?

**Comment by lurch** [comment]
Looks like v1.5.117 is the latest version for which binaries are available: https://github.com/balena-io/etcher/releases

**Comment by luckman212** [comment]
Came to ask the same, seems something is wrong with the build pipeline since 117...

**Comment by lurch** [comment]
Perhaps none of the changes in v1.5.118 and v1.5.119 would actually affect the binaries that people download? :man_shrugging: 
https://github.com/balena-io/etcher/blob/master/CHANGELOG.md

**Comment by ksdomino** [comment]
Old version on website (116 vs 119) so that's quite a bit of disparity: As of today, the version available for download is 3 months old and it looks like there have been quite a lot of changes since then so it really needs fixing but can't make demands, just pointing out the disparity.

**Comment by thundron** [comment]
thanks for reporting, indeed there seems to be an issue on our CI when publishing the file that we then use to check the version on the website, we're investigating

**Comment by thundron** [comment]
@lurch correct, closing!
