### ISSUE TITLE
how to find the target

### ISSUE THREAD

**Issue by bazghandizahra** [balena-io/etcher#3515]
- **Etcher version:** v1.5.120
- **Operating system and architecture:**  windows10
- **Image flashed:** ubuntu-20.04.2.0-desktop-amd64.iso 
Hi everyone. I am trying to flash the above iso image in Etcher but I don't know how to find the USB drive to enter as my target. I attached the following image to show what I see when clicking on the target drive here. could you help me with this plz?
![Target](https://user-images.githubusercontent.com/58359089/117966141-d3547480-b338-11eb-8795-5e547a09e4b2.png)

**Comment by lurch** [comment]
Looks like Etcher can see your internal hard-drive, but can't "see" your USB drive. Does your USB drive show up in Windows Explorer and/or Device Manager?

**Comment by bazghandizahra** [comment]
Thank you for response. The problem was my USB device.thanks for your time

در تاریخ ۱۲ مهٔ ۲۰۲۱ ۱۵:۵۰، "Andrew Scheller" ***@***.***>
نوشت:
