### ISSUE TITLE
README should explain the need for a whole app

### ISSUE THREAD

**Issue by eyalroz** [balena-io/etcher#3518]
On Linux, one can write an OS image to a flash disk using, say:
```
dd if=/path/to/my.iso of=/dev/sdX bs=4M
```
for an appropriate value of X.

Looking at the README.md, it's not quite clear what Etcher does beyond this. I mean, it's not a 96MB executable just to make sure you don't overwrite your own hard disks, right?

**Comment by lurch** [comment]
Isn't that kinda what the website does? https://www.balena.io/etcher/
:shrug:

**Comment by thundron** [comment]
The general purpose of Etcher is already written in the first lines of the README
