### ISSUE TITLE
Can't boot from RELAX-AND-RECOVER (REAR) ISO 9660 (Rockridge)

### ISSUE THREAD

**Issue by mywp** [balena-io/etcher#3522]
- **Etcher version:1.5.120 (1.5.120)** 
- **Operating system and architecture:Mac OS 11.4 (20F71)** 
- **Image flashed:RELAX-AND-RECOVER (REAR) ISO 9660 (Rockridge)** 
RedHat 8 rear backup file ISO Can't boot , only boot from DVD

**Comment by thundron** [comment]
Hi, Etcher is currently unable to make images bootable unless they're already hybrid; I would suggest asking in the image's support channels for more information on how to make the image bootable
