### ISSUE TITLE
"Etcher" Knockoff?

### ISSUE THREAD

**Issue by McNeight** [balena-io/etcher#3525]
Not a problem report per se, but are you aware of an extremely similar website calling itself Etcher?

https://www.etcher.net/

By typing just "etcher" into Google, they currently come up as the second hit. If I were the paranoid type (of course I am...), I would be concerned about them using the name of this project to lure in unsuspecting users and propagate spyware/malware.

**Comment by thundron** [comment]
We're aware of it but unfortunately there's little we can do other than report the website to the authorities (which I think we already did quite some time ago).
Thanks for the report nonetheless and indeed avoid downloading from untrusted sources 👀
