### ISSUE TITLE
Flash fails

### ISSUE THREAD

**Issue by counterdutch** [balena-io/etcher#3530]
`-` **Etcher version:** 1.5.120
- **Operating system and architecture:**  WIN10 home (all updates)
- **Image flashed:**  OpenSuse Leap 15.3 -Netinstaller 153 MB
- **Do you see any meaningful error information in the DevTools?**  NO

Tue Jun 08 2021 03:57:00 GMT+0200 (Central European Summer Time) Done ({"image":{"size":153092096,"name":"openSUSE-Leap-15.3-NET-x86_64.iso","hasMBR":true,"partitions":[{"offset":141312,"size":3612672,"type":239,"index":1},{"offset":3753984,"size":149338112,"type":23,"index":2}],"extension":"iso","path":"C:\\Users\\alex\\Desktop\\openSUSE-Leap-15.3-NET-x86_64.iso"},"drives":[{"size":16095641600,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive3","error":null,"isReadOnly":false,"displayName":"F:\\","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive3","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[{"path":"F:\\"}],"description":"USB Device","isUAS":false,"partitionTableType":"mbr"}],"driveCount":1,"uuid":"3e71d4d8-1835-46f7-aea8-c08453d8321d","status":"finished","flashInstanceUuid":"3e71d4d8-1835-46f7-aea8-c08453d8321d","errors":[{"name":"Error","description":"USB Device","device":"\\\\.\\PhysicalDrive3"}],"devices":{"failed":1,"successful":0},"bytesWritten":0,"sourceMetadata":{"size":153092096,"name":"openSUSE-Leap-15.3-NET-x86_64.iso","blocks":[{"blocks":[{"offset":0,"length":153092096}]}],"blockmappedSize":153092096},"sample":0.1,"applicationSessionUuid":"bcaaa42a-ec46-4a29-9779-f52ee24e7b21","flashingWorkflowUuid":"c0c7e327-74f4-4e34-964c-ab199b7367b6"})

**Comment by thundron** [comment]
That line is the end of the flash, what does the completion screen say in the failure logs? You should see a link to inspect the errors on the last screen
