### ISSUE TITLE
Application not opening

### ISSUE THREAD

**Issue by MasterDiggi** [balena-io/etcher#3537]
I installed Etcher normally, but when I try to execute it nothing happens even tho it's an active process

**Comment by diablos6p** [comment]
can you post the terminal output of those two commands.
ls -l | grep balena
sudo ls -l /opt | grep balena
I had the same problem and it turned out that there was a problem with the shortcut link.

**Comment by lurch** [comment]
@MasterDiggi What OS are you running on? What version of Etcher are you using?

**Comment by MasterDiggi** [comment]
> can you post the terminal output of those two commands.
> ls -l | grep balena
> sudo ls -l /opt | grep balena
> I had the same problem and it turned out that there was a problem with the shortcut link.

I'm not using Linux, I'm using windows

**Comment by MasterDiggi** [comment]
> @MasterDiggi What OS are you running on? What version of Etcher are you using?

I'm using Windows 10 Pro and I'm using the latest version of Etcher

**Comment by MasterDiggi** [comment]
this is how the app stays - https://imgur.com/a/GuFCBvd

**Comment by lurch** [comment]
Sounds very similar to #3088 ?

**Comment by diablos6p** [comment]
did you try to use an older version of the app?
you can find them here: https://github.com/balena-io/etcher/releases

**Comment by MasterDiggi** [comment]
> did you try to use an older version of the app?
> you can find them here: https://github.com/balena-io/etcher/releases

ok yes I've tried using old versions and the only place I could use it was on my Linux laptop and when I restart my pc trying to open the app as fast as possible

**Comment by thundron** [comment]
sounds like a duplicate of #3088 as mentioned, closing this one
