### ISSUE TITLE
Unmount/Auto Eject Issue

### ISSUE THREAD

**Issue by Magnetom82** [balena-io/etcher#3542]
- **Etcher version:** 1.5.120
- **Operating system and architecture:** Windows 10 64bit 
- **Image flashed:** Own Raspi Image
- **Do you see any meaningful error information in the DevTools?** Unmount Failed every time:

Wed Jun 30 2021 08:28:54 GMT+0200 (Mitteleuropäische Sommerzeit) Flash error ({"image":{"size":15986589696,"name":"rpi_image_V2_3_2_1.img","hasMBR":true,"partitions":[{"offset":4194304,"size":44979712,"type":12,"index":1},{"offset":50331648,"size":15936258048,"type":131,"index":2}],"extension":"img","path":"C:\\Users\\USM-iOT\\Documents\\LD2.0\\rpi_image_V2_3_2_1.img"},"drives":[{"size":31914983424,"isVirtual":false,"enumerator":"SD","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive1","error":null,"isReadOnly":false,"displayName":"E:\\","blockSize":4096,"isSCSI":true,"isRemovable":true,"device":"\\\\.\\PhysicalDrive1","busVersion":"1.0","isSystem":false,"busType":"SD","isCard":true,"isUSB":false,"devicePath":null,"mountpoints":[{"path":"E:\\"}],"description":"Generic SM32G SD Card","isUAS":false,"partitionTableType":"mbr"}],"driveCount":1,"uuid":"cc621376-8f84-487c-b57c-cc29fe4a5d44","flashInstanceUuid":"cc621376-8f84-487c-b57c-cc29fe4a5d44","error":{"name":"Error","message":"Unmount failed","stack":"Error: Unmount failed"},"sample":0.1,"applicationSessionUuid":"26813861-db8d-4633-8acd-00ce2a10b0dc","flashingWorkflowUuid":"168a0dbc-516d-4600-8da0-88cdb7173e4c"})

This is a combined Error from Issue #3516 and Issue #1370
 
Drive Error shows automatically from Windows shortly before Etcher reports the Error
![Drive Error](https://user-images.githubusercontent.com/30377681/123913046-0e107b80-d97e-11eb-9e77-fbf0a7474194.png)

Etcher Error 
![etcher Error](https://user-images.githubusercontent.com/30377681/123913066-15d02000-d97e-11eb-8a3a-2e4b288045e6.png)

**Comment by thundron** [comment]
will be solved with https://github.com/balena-io/etcher/issues/3197 , closing this one
