### ISSUE TITLE
1 tb to 1 tb, target drive too small

### ISSUE THREAD

**Issue by Narick9** [balena-io/etcher#3547]
- **Etcher version:** v1.5.120
- **Operating system and architecture:** Linux fedora 5.11.12-300.fc34.x86_64
- **Image flashed:** cloning drive WDC WD10EZEX-60W
- **Do you see any meaningful error information in the DevTools?** no

![Screenshot from 2021-07-03 23-16-18](https://user-images.githubusercontent.com/58558002/124366065-9e3c1280-dc55-11eb-85c0-10f6d936080c.png)
Target drive is missing several kib, so I can't clone to it.
Sorry, if it's not really cloning already

**Comment by thundron** [comment]
There's not much we can do if the target is smaller than the source. 1TB of a certain brand *can* be different than 1TB of another brand, it depends on how much the size has been rounded up
