### ISSUE TITLE
Etcher just started hanging

### ISSUE THREAD

**Issue by xmas670** [balena-io/etcher#3553]
- **Etcher version:** 1.5.120
- **Operating system and architecture:** x86 windows
- **Image flashed:** kali linux
Etcher just started hanging at 75%.

**Comment by thundron** [comment]
@xmas670 have you tried changing target and/or reader/slot ?

**Comment by xmas670** [comment]
Yes but the problem was something like url management. At first I tried to pass the image as a link but that did not work so I downloaded the image instead
