### ISSUE TITLE
White screen on Balena Etcher

### ISSUE THREAD

**Issue by Captain-Kirin** [balena-io/etcher#3558]
- Balena-Etcher-2:1.5.120-1
- Arch Linux, amd64 

I've updated to the newest edition of Balena Etcher and when doing so, all I get is a white screen for the application and nothing else. When opening Devtools and looking at the application, it looks like this and.
While I may be no HTML expert, I know this is off.

Can anyone please help?
![Screenshot from 2021-07-14 13-21-14](https://user-images.githubusercontent.com/64995043/125672957-cd3b4b9b-a54d-44d9-ae26-10193e741bd5.png)
![Screenshot from 2021-07-14 13-14-29](https://user-images.githubusercontent.com/64995043/125672996-18206341-0c8e-49c5-b43b-ce64ad1076dd.png)

**Comment by thundron** [comment]
can you check if there's any error in the Console tab of the DevTools ?

**Comment by lurch** [comment]
Similar to #2866 (amongst others) ?

**Comment by alexclaydon** [comment]
I'm experiencing this on an M1 Mac.  Reverting to v1.5.114 (an Intel build) resolved the issue.

**Comment by lilithium-hydride** [comment]
Getting this on Artix with aur/balena-etcher 2:1.5.120-1. @thundron OP seems to have disappeared, but mine is exhibiting the same behavior with the following in the console:
```
index.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
```
```
electron/js2c/asar_bundle.js:5 Uncaught Error: /usr/lib/balena-etcher/generated/modules/xxhash/build/Release/hash.node: undefined symbol: _ZN2v86Object18InternalFieldCountEv
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5)
    at Module.load (internal/modules/cjs/loader.js:935)
    at Module._load (internal/modules/cjs/loader.js:776)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:33)
    at Module.require (internal/modules/cjs/loader.js:959)
    at require (internal/modules/cjs/helpers.js:88)
    at Object.defineProperty.value (gui.js:4216)
```
```
electron/js2c/renderer_init.js:113 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ electron/js2c/renderer_init.js:113
```

**Comment by thundron** [comment]
See https://github.com/balena-io/etcher/issues/3536 for arch

**Comment by thundron** [comment]
thanks @lilithium-hydride for the extra context!
