### ISSUE TITLE
Error in 'https://dl.cloudsmith.io/public/balena/etcher/setup.rpm.sh' for OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by egigoka** [balena-io/etcher#3565]
Because Tumbleweed version is changing rapidly, I suppose, you can strip version and codename from download link in function "config_url"

not working url, that generating now: "https://dl.cloudsmith.io/public/balena/etcher/config.rpm.txt?distro=opensuse-tumbleweed&codename=&version=20210721&arch=x86_64"

working url: "https://dl.cloudsmith.io/public/balena/etcher/config.rpm.txt?distro=opensuse-tumbleweed&arch=x86_64"

**Comment by lurch** [comment]
I wonder if this might be something you need to report to Cloudsmith, rather than Balena? :man_shrugging:
