### ISSUE TITLE
[suggestion] Use Tauri instead of Electron

### ISSUE THREAD

**Issue by eleius** [balena-io/etcher#3568]
Thanks for your work with Etcher. If possible consider switching to [Tauri](https://github.com/tauri-apps/tauri): has a much smaller memory & binary footprint vs Electron.

**Comment by thundron** [comment]
we were considering using other frameworks, but given the massive amount of electron APIs we use right now it's something that will probably come in the far, far future. closing for now, will re-open accordingly when we get our hands on it
