### ISSUE TITLE
Flash failed error

### ISSUE THREAD

**Issue by ganda2021** [balena-io/etcher#3587]
- **Etcher version:** 1.5.121
- **Operating system and architecture:** windows 10 x64 bit
- **Image flashed:** iwifi portal opi v4.4.1
- **Do you see any meaningful error information in the DevTools?** yes

Wed Sep 01 2021 17:36:29 GMT+0800 (Taipei Standard Time) Validation error ({"image":{"size":2989183488,"compressedSize":1100196178,"hasMBR":true,"path":"C:\\Users\\PC\\Downloads\\iwifi-portal-opi-v4.4.1-nic-teaming.zip","partitions":[{"offset":4194304,"size":2984989184,"type":131,"index":1}],"isCompressed":true,"name":"iwifi-portal-opi-v4.4.1-nic-teaming.img","extension":"zip"},"drives":[{"size":16631463936,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive1","error":null,"isReadOnly":false,"displayName":"D:\\","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive1","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[{"path":"D:\\"}],"description":"SDHC Card","isUAS":false,"partitionTableType":"mbr"}],"driveCount":1,"uuid":"234bcab1-4082-455f-9c1e-5794de3155c0","flashInstanceUuid":"234bcab1-4082-455f-9c1e-5794de3155c0","sample":0.1,"applicationSessionUuid":"40b1c60c-1bf1-4015-8a44-d2ed46a2f444","flashingWorkflowUuid":"cde8d729-9250-4f1a-a867-e4e05aead562"})
gui.js:38464 Verifying 1 device, 74% at 9.70 MB/s (total 9.70 MB/s) eta in 77s with 0 failed devices
gui.js:51120 Finish: 2168455168
gui.js:51120 Terminating IPC server
gui.js:51120 Flash results {results: {…}, cancelled: false, skip: false}
gui.js:51120 Wed Sep 01 2021 17:36:33 GMT+0800 (Taipei Standard Time) Done ({"image":{"size":2989183488,"compressedSize":1100196178,"hasMBR":true,"path":"C:\\Users\\PC\\Downloads\\iwifi-portal-opi-v4.4.1-nic-teaming.zip","partitions":[{"offset":4194304,"size":2984989184,"type":131,"index":1}],"isCompressed":true,"name":"iwifi-portal-opi-v4.4.1-nic-teaming.img","extension":"zip"},"drives":[{"size":16631463936,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive1","error":null,"isReadOnly":false,"displayName":"D:\\","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive1","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[{"path":"D:\\"}],"description":"SDHC Card","isUAS":false,"partitionTableType":"mbr"}],"driveCount":1,"uuid":"234bcab1-4082-455f-9c1e-5794de3155c0","status":"finished","flashInstanceUuid":"234bcab1-4082-455f-9c1e-5794de3155c0","errors":[{"name":"Error","description":"SDHC Card","code":"EVALIDATION","device":"\\\\.\\PhysicalDrive1"}],"devices":{"failed":1,"successful":0},"bytesWritten":2168455168,"sourceMetadata":{"size":2989183488,"name":"decompressed-image-f501434825fe.tmp","blocks":[{"blocks":[{"offset":0,"length":2170552320}]},{"blocks":[{"offset":2171600896,"length":46137344}]},{"blocks":[{"offset":2218786816,"length":2097152}]},{"blocks":[{"offset":2227175424,"length":8388608}]},{"blocks":[{"offset":2285895680,"length":18874368}]},{"blocks":[{"offset":2305818624,"length":2097152}]},{"blocks":[{"offset":2308964352,"length":3145728}]},{"blocks":[{"offset":2313158656,"length":1048576}]},{"blocks":[{"offset":2315255808,"length":193986560}]},{"blocks":[{"offset":2510290944,"length":7340032}]},{"blocks":[{"offset":2518679552,"length":34603008}]},{"blocks":[{"offset":2554331136,"length":126877696}]},{"blocks":[{"offset":2682257408,"length":210763776}]},{"blocks":[{"offset":2894069760,"length":91226112}]},{"blocks":[{"offset":2986344448,"length":1048576}]},{"blocks":[{"offset":2988441600,"length":741888}]}],"blockmappedSize":2918928896},"sample":0.1,"applicationSessionUuid":"40b1c60c-1bf1-4015-8a44-d2ed46a2f444","flashingWorkflowUuid":"cde8d729-9250-4f1a-a867-e4e05aead562"})
gui.js:51120 Wed Sep 01 2021 17:36:34 GMT+0800 (Taipei Standard Time) SafeWebview loaded ({"event":{"id":18,"url":"https://www.balena.io/etcher/success-banner/?borderTop=false&darkBackground=true&etcher-version=1.5.121&api-version=2&optOutAnalytics=true","method":"GET","timestamp":1630488994526.0989,"resourceType":"mainFrame","ip":"18.140.226.100","fromCache":false,"statusLine":"HTTP/1.1 200","statusCode":200,"responseHeaders":{"age":["453090"],"cache-control":["public, max-age=0, must-revalidate"],"content-encoding":["br"],"content-length":["6110"],"content-type":["text/html; charset=UTF-8"],"date":["Fri, 27 Aug 2021 03:45:03 GMT"],"etag":["\"56e98ced4e3c1c45190c990c74598528-ssl-df\""],"link":["</webpack-runtime-138c6a38d080d53e7705.js>; rel=preload; as=script, </styles-c4fa86dfd4ad05097eee.js>; rel=preload; as=script, </framework-149d8dfa392460762009.js>; rel=preload; as=script, </50c25a04-efe577ee14c9c53bed03.js>; rel=preload; as=script, </73ad3401-e112b47ad7a992b91ac8.js>; rel=preload; as=script, </532a2f07-16f3498dd087ee7288d4.js>; rel=preload; as=script, </app-581b723d314e1659aee8.js>; rel=preload; as=script, </c943faba-f859f80ceb7f4f7eab31.js>; rel=preload; as=script, </af13d906-36fdbc23fc7dd2f2b2e7.js>; rel=preload; as=script, </ec1189df-4ae9e03f4545d4f1d61b.js>; rel=preload; as=script, </a9a7754c-29508ff4045f1f93a5f6.js>; rel=preload; as=script, </commons-8fcc2f56d20b76e33299.js>; rel=preload; as=script, </edad6859a763f5239c0343c48608d154b87713d6-282649cf8ac0a71046b8.js>; rel=preload; as=script, </component---src-pages-etcher-success-banner-js-6efe4d4fdc9d35955b7f.js>; rel=preload; as=script, </page-data/app-data.json>; rel=preload; as=fetch; crossorigin, </page-data/etcher/success-banner/page-data.json>; rel=preload; as=fetch; crossorigin"],"referrer-policy":["strict-origin-when-cross-origin"],"server":["Netlify"],"strict-transport-security":["max-age=31536000"],"vary":["Accept-Encoding"],"x-content-type-options":["nosniff"],"x-frame-options":["DENY"],"x-nf-request-id":["01FEGBF77BKQKB5FHMED6GJ1PC"],"x-xss-protection":["1; mode=block"]},"referrer":"","error":"net::OK"},"sample":0.1,"applicationSessionUuid":"40b1c60c-1bf1-4015-8a44-d2ed46a2f444","flashingWorkflowUuid":"cde8d729-9250-4f1a-a867-e4e05aead562"})
gui.js:51120 Message from SafeWebview: Error: Not supported

**Comment by thundron** [comment]
what you see there is a validation error; just to double-check we don't have regressions in the UI, didn't you see that also in the final screen of the flash?
