### ISSUE TITLE
balenaEtcher window shows "Etcher" instead of "balenaEtcher" on windows version

### ISSUE THREAD

**Issue by danthegoodman1** [balena-io/etcher#3592]
See attached screenshot, the header shows `Etcher` instead of `balenaEtcher`, should show `balenaEtcher`.

macOS already shows `balenaEtcher`, so this is isolated to Windows.

![image](https://user-images.githubusercontent.com/17806508/132023476-30c52e00-1b68-438c-afdd-f8908f6c7cb1.png)

**Comment by sergiotca** [comment]
I'm not sure it is "isolated" to Windows...
This is 1.5.117 running on Ubuntu 21.04:
![imagen](https://user-images.githubusercontent.com/41351896/132755165-c73b93a6-5d75-48f8-a733-b4f0542edb72.png)

**Comment by danthegoodman1** [comment]
Good find!

**Comment by sergiotca** [comment]
TBH I suspect this title is by design. I could be mistaken but I believe "Etcher" is the application's actual name.
Balena would be kind of like its ecosystem.

**Comment by danthegoodman1** [comment]
On one of the Friday all hands Alex mentioned that it should be
balenaEtcher so I made the pr.

**Comment by sergiotca** [comment]
Oh, I was not aware of that.
In any case, I guess naming consistency among its deployments would be desired.

**Comment by lurch** [comment]
Tangentially related to #3209

There's also a bunch of places in `README.md` which say "Etcher" which should perhaps be "balenaEtcher"?
And I see `package.json` says `"author": "Balena Inc. <hello@etcher.io>",` but I dunno if you're still using the etcher.io domain?

Ahh, in fact:
```
$ git grep 'etcher\.io'|grep -v CHANGELOG
SUPPORT.md:[faq]: https://etcher.io
docs/MAINTAINERS.md:  - **E-mail address:** hello@etcher.io
lib/gui/menu.ts:							'https://etcher.io/pro?utm_source=etcher_menu&ref=etcher_menu',
lib/gui/menu.ts:						electron.shell.openExternal('https://etcher.io?ref=etcher_menu');
package.json:  "author": "Balena Inc. <hello@etcher.io>",
```
and also:
```
$ git grep 'balenaEtcher'|grep -v CHANGELOG|wc -l
10
$ git grep 'BalenaEtcher'|grep -v CHANGELOG|wc -l
3
$ git grep '\bEtcher\b'|grep -v CHANGELOG|wc -l
83
```
