### ISSUE TITLE
Balena Etcher wont flash Fin on Ubunutu 21.04

### ISSUE THREAD

**Issue by batesenergy** [balena-io/etcher#3596]
- **Etcher version: 1.5.122** 
- **Operating system and architecture: Ubuntu 21.04** 
- **Image flashed: Pi_OS Lite** 
- **Do you see any meaningful error information in the DevTools? None** 

We are trying to use Etcher to flash a BalenaFin board with CM3+ LIte module. Under "Select Target" we are unable to ever find the compute module. We have tried plugging and unplugging as well as restarts to no avail. 

Does anyone else have this issue?

**Comment by thundron** [comment]
@batesenergy you need to start etcher with `sudo` in order to be able to flash usbboot devices (e.g. the compute module)
