### ISSUE TITLE
I am getting this error when trying to add the repo in terminal kindly help me out i want to remove etcher i am unable to update "sudo apt update" it is giving error 

### ISSUE THREAD

**Issue by Akhil9982** [balena-io/etcher#3597]
akhil@akhil:~$ curl -1sLf \
>    'https://dl.cloudsmith.io/public/balena/etcher/setup.deb.sh' \
>    | sudo -E bash
Executing the  setup script for the 'balena/etcher' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=20.04  codename=focal  arch=x86_64  
 >>>>:
 NOPE: Checking for apt dependency 'apt-transport-https' ...
 NOPE: Updating apt repository metadata cache ...
Failed to update via apt-get update
Ign:2 http://ppa.launchpad.net/plushuang-tw/uget-stable/ubuntu focal InRelease
Hit:3 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:4 http://archive.canonical.com/ubuntu focal InRelease
Err:5 http://ppa.launchpad.net/plushuang-tw/uget-stable/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:1 https://dl.bintray.com/etcher/debian stable InRelease
  403  Forbidden [IP: 34.211.43.146 443]
Reading package lists...
E: The repository 'http://ppa.launchpad.net/plushuang-tw/uget-stable/ubuntu focal Release' does not have a Release file.
E: Failed to fetch https://deb.etcher.io/dists/stable/InRelease  403  Forbidden [IP: 34.211.43.146 443]
E: The repository 'https://deb.etcher.io stable InRelease' is not signed.
 ^^^^: ... Failed to update via apt-get update - Context above.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact balena for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/balena-io/etcher
 !!!!:

**Comment by lurch** [comment]
See #3501 
You need to remove https://dl.bintray.com/etcher/debian and https://deb.etcher.io/ from your software sources - have a look in `/etc/apt/sources.list` and/or `/etc/apt/sources.list.d/`

@thundron There have been several people that have encountered this error - maybe it's worth adding "How to remove the old repo" to the instructions in #3501 ?

**Comment by Akhil9982** [comment]
Thanks...
