### ISSUE TITLE
Flash drive disappeared

### ISSUE THREAD

**Issue by h1tech** [balena-io/etcher#3609]
- **Etcher version:** 1.5.122
- **Operating system and architecture:** Windows 10 x64
- **Image flashed:** Pop OS 21.04 Nvidia

After flashing the image, the flash drive disappeared from the file explorer on my pc. Tried to insert the flash drive on another pc. saw it in the file explorer, but it had only 3 MB of memory instead of 4 GB and had two files on it

**Comment by thundron** [comment]
The image was flashed correctly, it's just Windows not able to read it properly. If you need to use it to store other stuff, you'll have to format it again using another tool of your choice.

**Comment by h1tech** [comment]
Got it, thanks
