### ISSUE TITLE
password prompt disappears right away on manjaro/kde

### ISSUE THREAD

**Issue by ralyodio** [balena-io/etcher#3620]
Packages (2) electron12-12.2.1-1  etcher-1.6.0-1

WHen flashing a thumb drive password prompt loses focus right away on KDE/Manjaro. I managed to get to it by alt=tabbing but I restarted a few times.

also it looks like the window stays on top while flashing which is kind of annoying.

**Comment by dfunckt** [comment]
Closing in favor of #4030
