### ISSUE TITLE
Error: User did not grant permission

### ISSUE THREAD

**Issue by Lion0416** [balena-io/etcher#3621]
- **Etcher version:1.5.122
- **Operating system and architecture: window 10
- **Image flashed: 2020-12-13-qut-v35-raspbian-buster
- **Do you see any meaningful error information in the DevTools? 
I cant flash the img to the sd card

<!-- You can open DevTools by pressing `Ctrl+Shift+I` (`Ctrl+Alt+I` for Etcher before v1.3.x), or `Cmd+Opt+I` if you're on macOS. --
![1](https://user-images.githubusercontent.com/86363967/138990181-b4f213df-0b98-4f8a-9c3d-daa9729554a0.JPG)
>
![2](https://user-images.githubusercontent.com/86363967/138990194-28ad94ab-2228-4b08-b613-dd3dbe741d58.JPG)

**Comment by lpartan** [comment]
getting the same refusal.  elevated Etcher, shared USB device to Everyone, tried different ISO images, ran out of imaginative things to do.

**Comment by thundron** [comment]
Have you checked that you have Controlled Folder Access disabled or put Etcher in whitelist?

**Comment by liqdfire** [comment]
Add these 2 items back to your Path environment variable

`C:\Windows\System32\WindowsPowerShell\v1.0
C:\Windows\System32`

Courtesy of: 
https://forums.balena.io/t/win-10-user-did-not-grant-permission/207435/57

**Comment by CapoElMate** [comment]
[liqdfire](https://github.com/liqdfire), thanks man, you just saved me! i was triyng to install linux mint in my usb, i got stuck with that error hours ago.

**Comment by chickysnail** [comment]
[liqdfire](https://github.com/liqdfire) thanks a lot. I was trying to flash on system drive, don't know if that was the issue, but with your solution it worked

**Comment by MaxRondelli** [comment]
@liqdfire I've added the items into path environment variable, but I still have the same problem. 

![Immagine 2023-03-31 181235](https://user-images.githubusercontent.com/83310259/229174519-4735b5c2-ba02-4491-b195-80f376a3b80c.jpg)

I'm trying to flash ubuntu-22.04.2 and balenaEtcher's version is 1.18.4.

**Comment by lurch** [comment]
@MaxRondelli Rather than add those values as **new** variables, I believe the suggestion is to add them to the **existing** `PATH` variable? i.e. you'd want to append
```
;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32
```
onto the end of the values for `PATH`?
(although it's been a long time since I've used Windows myself, so be careful when changing these system-variables)

**Comment by Jakilator** [comment]
> C:\Windows\System32\WindowsPowerShell\v1.0

uff this helped finally its flashing

**Comment by Bhavaniplays** [comment]
@liqdfire bro thankyou vey much i tried yourube for an hr and finnakly got solution

**Comment by Bumross** [comment]
> Add these 2 items back to your Path environment variable
> 
> ```
> C:\Windows\System32\WindowsPowerShell\v1.0
> C:\Windows\System32
> ```
> 
> Courtesy of: https://forums.balena.io/t/win-10-user-did-not-grant-permission/207435/57

This helped me.
Also if you have this problem, run the app as an administrator.
