### ISSUE TITLE
creating image from sd or cloning enhancement request

### ISSUE THREAD

**Issue by blacknell** [balena-io/etcher#3624]
I'm using the latest 1.5.122 and when cloning, there is no way to select the same SD drive as the target. I only have one SD card slot on my Mac.

So either it could be enhanced to allow this, or could it be enhanced to save the resulting image (relates #3232) which I need anyway since I will be cloning this drive to others in the unforeseen future.

I'm capable of using ```dd``` command but this taking what looks like 2 hours so etcher must be cleverer than that or I'm missing a trick

```sudo dd if=/dev/disk5 of=~/raspberrypi-bullseye-20211101.dmg bs=1m```

**Comment by lurch** [comment]
Perhaps the easiest "workaround" for now is to just buy a USB SD card-reader? :wink:

**Comment by alex-ssom** [comment]
Just increase the block size to something like 4 Mb `bs=4M`. You can also use the `status=progress` argument to get some feedback on the progress of the copy operation.

**Comment by ReanimationXP** [comment]
This request was closed as completed without being completed also, as I cannot select the same source drive as a destination, which would provoke the saving of an image file, even if it's to a location I can't designate.
