### ISSUE TITLE
Flash from URL fails with "Error: certificate has expired"

### ISSUE THREAD

**Issue by steev** [balena-io/etcher#3626]
- **Etcher version:** 1.6.0
- **Operating system and architecture:** Windows 10 x86_64
- **Image flashed:** kali-linux-2021-W43-rpi0w-armel.img.xz
- **Do you see any meaningful error information in the DevTools?** 

gui.js:51281 {"message":"certificate has expired","stack":"Error: certificate has expired\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)","config":{"url":"https://balena.io/etcher/static/config.json","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/1.6.0"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}},"code":"CERT_HAS_EXPIRED"}

{"message":"certificate has expired","stack":"Error: certificate has expired\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)","config":{"url":"https://arm.kali.org/kali-weekly/kali-linux-2021-W43-rpi0w-armel.img.xz","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/1.6.0"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"stream","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}},"code":"CERT_HAS_EXPIRED"}

I believe this has to do with the LetsEncrypt root certificate expiration as the server I am using uses a LetsEncrypt cert, however the site works fine in browsers, and I can download the file over https just fine.

**Comment by thundron** [comment]
We're working towards resolving this issue but it will require a bit more time unfortunately!

**Comment by Tortoise17** [comment]
I am also facing it. Now no version of etcher is working apparently.

**Comment by richardwellerson** [comment]
Same problem at version 1.7.1 on Ubuntu 20.04 x64.

**Comment by richardwellerson** [comment]
![image](https://user-images.githubusercontent.com/54604053/143865863-9dbe201a-ac71-4183-a24b-0aa6ec02832d.png)

Well, my devTools shows a error about "message"... But apparently my flash disk works perfectly...

**Comment by orayb** [comment]
Same problem with 1.7.3-x64, running on Cent OS 7

**Comment by cascadeorca** [comment]
Issue is happening with some IMGs, but not all.

`gui.js:46 {"message":"certificate has expired","stack":"Error: certificate has expired\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)","config":{"url":"https://balena.io/etcher/static/config.json","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/1.7.3"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}},"code":"CERT_HAS_EXPIRED"}`

**Comment by Danahi** [comment]
I am faced with the same issue on windows 10.
One time I could flash an image. After that it failed.
```
{"message":"certificate has expired","stack":"Error: certificate has expired\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)","config":{"url":"https://balena.io/etcher/static/config.json","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/1.7.3"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}},"code":"CERT_HAS_EXPIRED"}
console.<computed> @ gui.js:46
```

**Comment by Tank1334** [comment]
Also having this problem

**Comment by FirstWhiteHacker** [comment]
If you change https to http, it will succeed.

**Comment by steev** [comment]
> If you change https to http, it will succeed.

Well yes, because then it's not trying to verify the certificate, because it's not a *s*ecure connection.  Not all web servers expose http these days however.

**Comment by RodBarnes** [comment]
I get these same errors but it doesn't appear to have any affect on the operation.  The flashed drives I've created seem to work fine.
