### ISSUE TITLE
node_modules in the binary deb?

### ISSUE THREAD

**Issue by molaeiali** [balena-io/etcher#3629]
- **Etcher version:** 1.7
- **Operating system and architecture:** Linux

There is ```/opt/balenaEtcher/resources/app/node_modules``` included in the [.deb](https://github.com/balena-io/etcher/releases/download/v1.7.0/balena-etcher-electron_1.7.0_amd64.deb) released file causing it's size to be almost doubled since 1.6, is that intentional?

**Comment by thundron** [comment]
yes and no: while of course the intention was not to have a bigger package, this was unfortunately a necessary step to have proper bundling in webpack and remove a lot of custom glue code

**Comment by molaeiali** [comment]
Ok then ✌
