### ISSUE TITLE
I downloaded etcher. What is its MD5 hash so I can verify the installer exe?

### ISSUE THREAD

**Issue by FlexMcMurphy** [balena-io/etcher#3637]
I don't see MD5 hashes alongside the Balena etcher installer .exe downloads on the site anywhere.

How can I confirm the installers are legit and safe to use? Normally I would use certutil from Windows command line to compute an md5 hash of the downloaded .exe and compare with a hash on the website.

Cheers,

Flex

**Comment by lurch** [comment]
See #2826
