### ISSUE TITLE
A technical problem

### ISSUE THREAD

**Issue by hamadasal** [balena-io/etcher#3645]
Can not complete downloading this application. it requires me a login and password after completing 80-88% of downloading and then stops. im using IDM on my browsers.. 
It takes until now about 5 times and i failed to fix this. please help!

**Comment by hamadasal** [comment]
> Can not complete downloading this application. it requires me a login and password after completing 80-88% of downloading and then stops. im using IDM on my browsers.. It takes until now about 5 times and i fail to fix this. please help!

**Comment by thundron** [comment]
That is super weird: where did you download Etcher from? We never ask for login/password anywhere; we just ask the password to enable the child-process to write to the selected targets.

**Comment by hamadasal** [comment]
Yes.. so weird to me too.. IDM only asks me logins and passwords even after 80% completing the free downlaoding from the main open source website here: https://www.balena.io/etcher/ 

I have screenshoted the situation so that i want you share this hoping to get an explanation.
I dont use anothe rdownloading application than IDM with all my browsers.

the pictures belwo show what happened with me during 2 days while i start normally and after 60-80-88% of completing of my downlaod: 

(uploaded pictures in JPEG and PNG extentions)


![Untitled](https://user-images.githubusercontent.com/95202473/143962007-f9b48cb9-87ef-4be7-80d8-9997998e3b7c.jpg)
![Untitledddd](https://user-images.githubusercontent.com/95202473/143962012-5f0d0dcb-e2ca-463b-805a-31f12195bd4d.jpg)
![Untitleddfgdfg](https://user-images.githubusercontent.com/95202473/143962020-bd9508e2-01bc-4925-9c83-1e2401042d77.jpg)



![Untitledddd](https://user-images.githubusercontent.com/95202473/143961544-581a696c-fa4d-44c1-a256-1f39feab1fc9.png)
![Untitleddfgdfg](https://user-images.githubusercontent.com/95202473/143961724-5323dc56-6a61-4ccf-96da-b30bcf3b029b.png)
![Untitled](https://user-images.githubusercontent.com/95202473/143961772-5eb3f72b-86f1-42f8-a3ce-4d0562e10a81.png)

**Comment by hamadasal** [comment]
Hello there. i have replied your comment there. thank you. 

    On Monday, November 29, 2021, 11:05:18 AM GMT+2, Lorenzo Alberto Maria Ambrosi ***@***.***> wrote:  
 
 


That is super weird: where did you download Etcher from? We never ask for login/password anywhere; we just ask the password to enable the child-process to write to the selected targets.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lurch** [comment]
I wonder if "IDM" is trying to download the file in "multiple parts", and perhaps that's hitting some kind of API-rate-limit in GitHub? :shrug:
