### ISSUE TITLE
Incorrect SHA512 checksum in latest.yml

### ISSUE THREAD

**Issue by allywilson** [balena-io/etcher#3653]
- **Etcher version: 1.7.1** 
- **Operating system and architecture: NA** 
- **Image flashed: NA** 
- **Do you see any meaningful error information in the DevTools?** 

**latest.yml** file contains incorrect SHA512 checksum for the latest **balenaEtcher-Setup-1.7.1.exe** download.

Contains: **byitThHrH8eTAwIGVi9IMxBEtfJe+tO4XOE9eREds6S12GiWuIA9TFNFsQg1yEsoDbNdWKKXd2dF8Ug8394RUQ==**
Download is: **6f28ad4e11eb1fc793030206562f48331044b5f25efad3b85ce13d79111db3a4b5d86896b8803d4c5345b10835c84b280db35d58a297776745f1483cdfde1151**

It doesn't actually look like a SHA512 checksum, it looks like something has been base64 encoded, but I got gibberish when decoding it.

**Comment by lurch** [comment]
See also #2826

**Comment by allywilson** [comment]
2 years and not fixed or addressed? Why?
