### ISSUE TITLE
 The capacity of Micro SD card is displayed incorrectly

### ISSUE THREAD

**Issue by BahuangShanren** [balena-io/etcher#3687]
- **Etcher version:** v1.7.3
- **Operating system and architecture:** Windows11,amd64
- **Image flashed:** [FydeOS_for_PC_v13.1-stable.img.xz](https://fydeos.com/download/pc/intel-hd) 
- **Do you see any meaningful error information in the DevTools?** None

This is just a Micro SD card with 32GB capacity (actually only 29.1GB). 

<img src="https://user-images.githubusercontent.com/48022216/150955567-f3a95726-0059-44ef-a695-d15db5b6b6e9.png" height=400px />

But etcher indicates that it has a capacity of 2.2TB, which is puzzling.

<img src="https://user-images.githubusercontent.com/48022216/150955517-ab2d3baa-8fe3-45f3-9fc5-43c28af5f24a.png" height=300px />

I still perform flash operations to see what happens.As a result, etcher prompts that the flash failed, and then the capacity of Micro SD becomes 2045.12GB.

![](https://user-images.githubusercontent.com/48022216/150955909-758b9e12-1fe1-440d-8c5c-2dba71b63b03.png)

I tried micro SD cards of different brands and capacities. I also tried to replace the card reader, and even tried to load different system images. But everything is correct. It seems that only this Kingston 32GB micro SD card has a problem. But I have only one. I don't know if this is a special case.

**Comment by lurch** [comment]
It might be worth trying a different USB card-reader, in case there's some kind of incompatibility with your new SD-card and your old card-reader? :shrug:

**Comment by BahuangShanren** [comment]
> It might be worth trying a different USB card-reader, in case there's some kind of incompatibility with your new SD-card and your old card-reader? 🤷

Maybe you're right. I have tried to use the card reader to carry other SD cards, and their capacity is displayed correctly.
But the capacity of this Kingston 32GB micro SD card has been changed, and I can't restore it. So I can't verify whether the cause of the problem is what you said.

**Comment by lurch** [comment]
I was assuming that perhaps a different card-reader would be able to read the "correct" size? :shrug:

**Comment by BahuangShanren** [comment]
> I was assuming that perhaps a different card-reader would be able to read the "correct" size? 🤷
