### ISSUE TITLE
ubuntu-budgie-20.04.3-desktop-amd64.iso flash failed

### ISSUE THREAD

**Issue by ahmedayman4a** [balena-io/etcher#3702]
- **Etcher version: v1.7.3** 
- **Operating system and architecture: Windows 10 64 bit** 
- **Image flashed: ubuntu-budgie-20.04.3-desktop-amd64.iso from the official torrent** 
- **Errors in DevTools:** 

![Screenshot 2022-02-14 140423](https://user-images.githubusercontent.com/55313946/153861931-74587e45-c4c9-4a8f-afb5-20317cb6f00f.png)

I retried multiple times but it gives the same error. Something goes wrong when validating.

**Comment by lurch** [comment]
What's a "VendorCo ProductCode USB Device"? :thinking:  Perhaps it's a "fake" USB flash drive?
