### ISSUE TITLE
Website Download link directs to an old version

### ISSUE THREAD

**Issue by ovz93br43v7** [balena-io/etcher#3705]
On you Website https://www.balena.io/etcher/, the download links at the end of the page direct me to https://github.com/balena-io/etcher/releases/download/v1.5.115/balena-etcher-electron-1.5.115-linux-x64.zip?

So to 1.5.115 and not to the latest version 1.7.3 from https://github.com/balena-io/etcher/releases.

**Comment by mcraa** [comment]
Shows 1.7.3 for me. Can you try to clear the browser cache and check again?

**Comment by ovz93br43v7** [comment]
sorry you are right, my mistake.
