### ISSUE TITLE
MacOS download button does not work

### ISSUE THREAD

**Issue by justinlawrence** [balena-io/etcher#3707]
See [www.balena.io/etcher/](https://www.balena.io/etcher/). If you click on "Download for MacOS", it shows a 404 page. Thanks.

**Comment by mcraa** [comment]
@justinlawrence thanks, we know, the CI for the last version uploaded only the windows files as mentioned [here](https://github.com/balena-io/etcher/pull/3697#issuecomment-1046796235) probably due to network errors.
We are working on it.

**Comment by justinlawrence** [comment]
> We are working on it.

@mcraa brilliant, thanks for the speedy response!

**Comment by mcraa** [comment]
until the site is fixed, the latest version is available directly by github releases
https://github.com/balena-io/etcher/releases/tag/v1.7.6

**Comment by mcraa** [comment]
with version 1.7.7 the site is updated correctly

**Comment by justinlawrence** [comment]
Thanks guys!
