### ISSUE TITLE
Balena etcher official site download button for linux doesnt work (.zip file from github not found)

### ISSUE THREAD

**Issue by GiorgosAthanasopoulos** [balena-io/etcher#3709]
- **Etcher version:** 
- **Operating system and architecture:** 
- linux 64bit
- **Image flashed:** 
- **What do you think should have happened:** 
- should have downloaded balena etcher app image
- **What happened:**
- nothing happened lol
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment]
Probably the same issue as #3707 ?
