### ISSUE TITLE
etcher not working 

### ISSUE THREAD

**Issue by m4x15** [balena-io/etcher#3715]
- etcher 1.7.7
- **windows 11 operating system
- **VOLUMIO:** 
- **What do you think should have happened:** it should have actually flashed 
- **What happened:* i have tried many many many times to flash volumio onto a 8gb and a 32gb micro sd for my raspberry pi as an audio player no matter what i do it will not flash i have tried re installing i have tried restating,looking up if anyone else has has this problem i have been trying for 4 days now and nothing is working. it gets to 100% on decompressing then says it has failed it said it worked one time after it failed 100 times but it didn't actually flash onto the sd 
I'm not sure what to do I have no other info that's it

**Comment by mcraa** [comment]
duplicated in #3720
