### ISSUE TITLE
Etcher says successful but USB is blank

### ISSUE THREAD

**Issue by KTkabo0m** [balena-io/etcher#3717]
- **Etcher version:**  1.7.7.0
- **Operating system and architecture:**  Windows 10 Pro
- **Image flashed:** lubuntu-16.04.6-desktop-i386.iso
- **What do you think should have happened:**  It should have Flashed the ISO file to USB Flash Drive so that it would be bootable to install on my old NetBook which the wiki said it would be compatible for. 
- **What happened:** Etcher said Flash complete and 1 Successful target and Effective speed: 5.2MB/s but the target which was the USB Flash Stick drive is empty and no longer reads and Windows says it has to be formatted. Why is nothing on there if the Flash was successful? I am confused.
- **Do you see any meaningful error information in the DevTools?** I don't have the DevTools. Will that fix it or tell me what is wrong? Where do I get these DevTools?
![Etcher did NOT Flash the ISO to the USB](https://user-images.githubusercontent.com/15949416/156713329-316fc68f-e479-47ff-b27f-744db69f16a6.jpg)
![Attempt at Making a Lubuntu bootable USB installer stick](https://user-images.githubusercontent.com/15949416/156713715-37e824fa-0c01-450f-a3d4-e223fe383b2e.jpg)
![Looks easy but USB target blank after supposed success](https://user-images.githubusercontent.com/15949416/156713799-9e5c7dce-0dc1-4eee-bc69-f8d8ffdc4d40.jpg)
![Now how USB drive looks](https://user-images.githubusercontent.com/15949416/156714106-607fd855-695a-4c00-8766-8fad87f3e235.jpg)
![Nothing on the USB after Flashing TWICE](https://user-images.githubusercontent.com/15949416/156714128-907d5a76-decc-4fd0-9237-a0eabc206aef.jpg)
![ISO looks fine](https://user-images.githubusercontent.com/15949416/156714636-b40c2133-78c9-4feb-8c9a-2be6f6dcf471.jpg)

**Comment by mcraa** [comment]
Of course you have dev tools @KTkabo0m It is built into the browser. Just read the issue template carefully.
![image](https://user-images.githubusercontent.com/6892971/156752491-205e113e-3029-4932-9699-0a90848598ec.png)

Linux partitions are not necessarily visible on windows.
Did you try to boot from the drive or just assumed something is wrong because windows is not showing it?

**Comment by lurch** [comment]
@mcraa 

> Linux partitions are not necessarily visible on windows.

That seems to confuse people on a regular basis - it might be worth adding something to https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md ?

**Comment by KTkabo0m** [comment]
> Of course you have dev tools @KTkabo0m It is built into the browser. Just read the issue template carefully. ![image](https://user-images.githubusercontent.com/6892971/156752491-205e113e-3029-4932-9699-0a90848598ec.png)
> 
> Linux partitions are not necessarily visible on windows. Did you try to boot from the drive or just assumed something is wrong because windows is not showing it?

Well I stopped using Etcher after trying it 4 times. I then switched to Rufus which worked on the first try. The same ISO and I could see that the USB flash drive had content when I used Rufus but nothing was on it with Etcher. 

So now that I have the work done using Rufus I guess this can now be closed. 

Thank you.

**Comment by lurch** [comment]
Rufus works in a slightly different manner than Etcher does #413
(which means that Rufus only works with disk images that it explicitly supports, whereas Etcher works with _any_ disk image)
