### ISSUE TITLE
contains the image you chose to flash

### ISSUE THREAD

**Issue by mauricev** [balena-io/etcher#3734]
Etcher 1.7.8
Monterey 12.3, Intel
Linux Mint iso
It should let me choose the target drive.
Instead, it claims bizarrely that I'm selecting the “source” drive and further claims crazily that my freshly formatted target flash drive contains the image I’m trying to flash.

**Comment by gstand** [comment]
I have this issue as well. Even inserting the flash drive after the image is selected causes the image to get deselected.

Etcher 1.7.9
macOS Ventura 13 Beta 8
Windows Server 2019 and 2022 evaluation ISOs

**Comment by dfunckt** [comment]
Closing in favor of #4051
