### ISSUE TITLE
Feature: Option to Inject SSH info into Raspberry Pi OS (and maybe other OSes)

### ISSUE THREAD

**Issue by fnfontana** [balena-io/etcher#3746]
Recently, the Raspberry Pi OS have the default login credentials (user: PI, password: raspberry) removed, so we no longer can build a headless setup just by adding the ssh file to boot partition, now it's necessary to configure the login credentials previously.
The Raspberry Pi Imager offers an option to insert the login data, and I think would be very handy if the Balena Etcher offers it too.

**Comment by lurch** [comment]
See also #718
