### ISSUE TITLE
no partition table

### ISSUE THREAD

**Issue by wildhi** [balena-io/etcher#3757]
- **Etcher version:** 1.5.115
- **Operating system and architecture:** macOS Monterey
- **Image flashed:** VMWare ESXi Image
- **What do you think should have happened:** 
- **What happened:**
No partition table are inside the image
- **Do you see any meaningful error information in the DevTools?** 
after the flash no booting from usb is possible

I test an other image and this works.

**Comment by lurch** [comment]
See https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#why-is-my-drive-not-bootable and #553
