### ISSUE TITLE
stuck at 33 percent dont know what todo if i close it it ill leave my card in an unusable state please someone help

### ISSUE THREAD

**Issue by ARCHIE123098** [balena-io/etcher#3773]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **What do you think should have happened:** 
- **What happened:**
- **Do you see any meaningful error information in the DevTools?**

**Comment by mcraa** [comment]
Your card won't be permanently unusable, check :
https://www.balena.io/blog/did-etcher-break-my-usb-sd-card/
