### ISSUE TITLE
Afrer flashing the iso file of ubuntu 22.xx into my pendrive. My pendrive is not working. It is showing write disabled in this drive and while formating it is not formating and I need to pay my friend that cost for him .please help me to recover his pendrive😭😭😭😭

### ISSUE THREAD

**Issue by cool-tree-27** [balena-io/etcher#3775]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **What do you think should have happened:** 
- **What happened:**
- **Do you see any meaningful error information in the DevTools?**

**Comment by cool-tree-27** [comment]
Hello everyone after that I went to rufus and tried  to boot it again it worked 
It worked well it formatted and booted my pendrive well

**Comment by lurch** [comment]
https://www.balena.io/blog/did-etcher-break-my-usb-sd-card/

**Comment by IbraRouisDev** [comment]
balena etcher could never break your friend's drive permentaly. If it was broke permentaly then the fault is with the pendrive.

**Comment by omarabdelaz1z** [comment]
Delete balena etcher, use rufus instead.
