### ISSUE TITLE
Unable to install on LinuxMint Elsie (Debian version amd64)

### ISSUE THREAD

**Issue by matthannan1** [balena-io/etcher#3783]
$ sudo curl -1sLf 'https://dl.cloudsmith.io/public/balena/etcher/setup.deb.sh' | sudo -E bash
Executing the  setup script for the 'balena/etcher' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=linuxmint  version=5  codename=elsie  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
  RUN: Importing 'balena/etcher' repository GPG key ...gpg: WARNING: unsafe ownership on homedir '/home/hannamj/.gnupg'
   OK: Checking for apt signed-by key support ...
   OK: Importing 'balena/etcher' repository GPG key ...
 NOPE: Checking if upstream install config is OK ...
 ^^^^: ... Failed to fetch configuration for your OS distribution release/version.
 >>>>:
 >>>>: It looks like we don't currently support your distribution release and
 >>>>: version. This is something that we can fix by adding it to our list of
 >>>>: supported versions (see contact us below), or you can manually override
 >>>>: the values below to an equivalent distribution that we do support:
 >>>>:
 >>>>: ... distro=linuxmint  version=5  codename=elsie  arch=x86_64  
 >>>>:
 >>>>: You can force this script to use a particular value by specifying distro,
 >>>>: version, or codename via environment variable. E.g., to specify a distro
 >>>>: such as Ubuntu/Xenial (16.04), use the following:
 >>>>:
 >>>>:   <curl command> | distro=ubuntu version=16.04 codename=xenial sudo -E bash
 >>>>:
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact balena for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/balena-io/etcher
 !!!!: 
 !!!!: Last 20 log lines from .csm_setup_qWle0QDiQ (might not be errors, nor even relevant):
 !!!!:
 !!!!: > ii  gnupg                                         2.2.27-2+deb11u2
 !!!!: > all          GNU privacy guard - a free PGP replacement
 !!!!: > ii  gnupg-l10n                                    2.2.27-2+deb11u2
 !!!!: > all          GNU privacy guard - localization files
 !!!!: > ii  gnupg-utils                                   2.2.27-2+deb11u2
 !!!!: > amd64        GNU privacy guard - utility programs

**Comment by mcraa** [comment]
your answer is in the error message

> You can force this script to use a particular value by specifying distro,
> : version, or codename via environment variable. E.g., to specify a distro
> : such as Ubuntu/Xenial (16.04), use the following:
> :
> : | distro=ubuntu version=16.04 codename=xenial sudo -E bash
(in your case `distro=debian` etc)

and in many other duplicates like #3776
