### ISSUE TITLE
etcher does not close it's GUI password dialogue on close

### ISSUE THREAD

**Issue by rebio** [balena-io/etcher#3789]
- **Etcher version:** 1.7.9
- **Operating system and architecture:** Operating System: KDE neon 5.25
KDE Plasma Version: 5.25.2
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.13.0-52-generic (64-bit)
Graphics Platform: X11
- **Image flashed:** lubuntu-22.04-desktop-amd64.iso
- **What do you think should have happened:** The dialogue is closed when etcher is closed
- **What happened:** The dialogue stays open
- **Do you see any meaningful error information in the DevTools?** no

What happened:<br/>
I tried to write the ISO to my USB stick. The dialogue to enter my password popped up. I started typing and it vanished (I didn't notice that it was just moved to the background). Since I thought that I already typed my password I was wondering why etcher wouldn't start writing the ISO. I closed and reopened etcher. I could not write an image because the dialogue stayed open in the background.

Easy fix: Close the dialogue box yourself. Though you have to notice it first and know that you can right click + close the window.

An alternative would be that the window of the password dialogue is flagged with 'always on top' so that the window can not be pushed into the background.

**Comment by dfunckt** [comment]
Closing in favor of #4030
