### ISSUE TITLE
New Pi Compute Modules Not Initializing

### ISSUE THREAD

**Issue by bhjelstrom** [balena-io/etcher#3792]
- 1.7.9
- Ubuntu 20.04, Win10
- No Dev Tools output

I have tested 7 new CM4s with HW revision ```c03141``` and new bootloaders. The progress bar appears for the cm, but the cm is never mounted as a storage device and the progress bar remains at 0%.
![image](https://user-images.githubusercontent.com/13728935/182279034-6efc91de-558a-495c-aec3-5500bcbf8cd6.png)

The new CM4s function as expected only when I run the latest rpiboot manually. Assuming https://github.com/balena-io-modules/node-raspberrypi-usbboot needs an update.

lsusb:
```Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0a5c Broadcom Corp.
  idProduct          0x2711 
  bcdDevice            0.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0020
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
```

**Comment by mcraa** [comment]
Thanks for sharing, we are working on it already.

**Comment by aessig** [comment]
@mcraa What should we do in the meantime?

**Comment by mcraa** [comment]
Sorry for the long reply, I don't know what you should do I only know what workaround is possible, similar to what we are working on.
The CM4s should be a 2711 device. So you can clone the repos and hardcode it in 
[node-raspberrypi-usbboot](https://github.com/balena-io-modules/node-raspberrypi-usbboot/blob/85941a6b64f7ac86070fdb53e0ff866950737a46/lib/index.ts#L525) to always detect 2711.
Then update it (locally) in the etcher-sdk, and update the etcher-sdk in etcher and build etcher for yourself.
This version of etcher then would work only work with cm4 and cm4s.
Or you can run your updated sdk directly like [ts-node examples/usb-boot.ts <..args>](https://github.com/balena-io-modules/etcher-sdk/blob/master/examples/usbboot.ts) without the struggle of building etcher.

It will probably take us this or the next week at least to test everything and make sure we don't break the support of any already supported devices.

**Comment by aessig** [comment]
@mcraa Thanks for your reply. Will try it.

**Comment by tosuns** [comment]
What is the current status of this issue? Do you guys have an idea when you will release a new version which contains a fix this issue ?

**Comment by fix3000** [comment]
Also here to poke. I can use rpiboot to work around the issue for now, but would be good to have the direct route back. It might be worth mentioning that "older" CM4s with a 2020 manufacturing date are directly recognized by balenaEtcher 1.7.9. It's the newer ones with a 2021 mfg date that I'm seeing the issue with. Suspecting there may be a newer bootloader when they roll off the line that's causing the issue. 

This may not be the right place for this, but would any update also be usable on Etcher Pro? 

I can do some limited testing if that's helpful; feel free to reach out.

**Comment by bhjelstrom** [comment]
I can confirm what @fix3000 is saying. To be clear, we are seeing this with 2021 and newer "CM4" units. There is a new "CM4-s" model that may or may not be detected, but I haven't tested the "CM4-s".

Shipping CM4 based products now so bumping again.

**Comment by mcraa** [comment]
Well, that name is confusing. CM4s meaning plural CM4, and CM4S as the new small format devices.
Seeing "New Pi" and "CM4s" I thought about the new small devices, it is good to point out there are "normal" size devices which have the issue.
cc @zwhitchcox

**Comment by lurch** [comment]
We've not added it to our [general documentation](https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#new-style-revision-codes) (because CM4S is a [limited-distribution product](https://github.com/raspberrypi/documentation/pull/2608#issuecomment-1219469656)), but the CM4S has a `Type` code of 0x15 https://github.com/raspberrypi/documentation/pull/2557 (regular CM4 has `Type` code 0x14).

https://forums.raspberrypi.com/viewtopic.php?t=339279 has more info about the CM4 with revision code `c03141`.

**Comment by tosuns** [comment]
@lurch What is the meaning of "limited-distribution product" and what kind of implication does it have with lifetime and support ?

**Comment by lurch** [comment]
As it says on the [CM4S product page](https://www.raspberrypi.com/products/compute-module-4s/):
> Based on the Raspberry Pi 4 Model B architecture, Compute Module 4S is intended for specific industrial customers migrating from Compute Module 3 or Compute Module 3+ and is not for general sale. For new customers who are designing products, we recommend using Raspberry Pi Compute Module 4.

**Comment by fix3000** [comment]
I haven't seen any recent update here on this issue, but is it something that's being worked on? Or planned to be worked on?

We're reaching a decision point on how we're going to flash all these new CM4 devices we'll soon be getting. If we need to work out an alternate plan, that's ok, just want to get ahead of it.

**Comment by zwhitchcox** [comment]
Hey, we think we have identified the problem, but still needs more testing. I will post an update here hopefully very soon.

**Comment by fix3000** [comment]
That's good to hear, hope it progresses well. Thanks.

**Comment by iamk3** [comment]
> Hey, we think we have identified the problem, but still needs more testing. I will post an update here hopefully very soon.

If you have a beta, I'd love to test it out. I'm bummed at the moment not being able to flash my two 32GB CM4.

**Comment by fix3000** [comment]
> > Hey, we think we have identified the problem, but still needs more testing. I will post an update here hopefully very soon.
> 
> If you have a beta, I'd love to test it out. I'm bummed at the moment not being able to flash my two 32GB CM4.

FYI, you can use rpiboot first to get the module mounted as storage and then use balenaEtcher to flash it.

I'd also be open to testing a beta if one is available.

**Comment by bhjelstrom** [comment]
Also applies to a03141 units

**Comment by iamk3** [comment]
> > > Hey, we think we have identified the problem, but still needs more testing. I will post an update here hopefully very soon.
> > 
> > 
> > If you have a beta, I'd love to test it out. I'm bummed at the moment not being able to flash my two 32GB CM4.
> 
> FYI, you can use rpiboot first to get the module mounted as storage and then use balenaEtcher to flash it.
> 
> I'd also be open to testing a beta if one is available.

Would you mind listing the steps to do this? I can't seem to figure it out. I have tried both running rpiboot and then plugging in the cm4 and plugging in the cm4 then running rpiboot.

**Comment by lurch** [comment]
AFAIK it _should_ just be a case of following the instructions [here](https://www.raspberrypi.com/documentation/computers/compute-module.html#setting-up-the-cmio-board), but then using balenaEtcher instead of `dd` or Raspberry Pi Imager? :man_shrugging:

**Comment by zwhitchcox** [comment]
Hey, thanks for the community support and willingness to test. We actually have an internal tester with the required hardware, so that won't be necessary. We have a working version of the low level model. Working on getting an Etcher release right now. Just wanted to give an update.

Thank you for your patience!!

**Comment by fix3000** [comment]
That's fantastic news, thanks so much for looking at this.

Relatedly, when the release is, well... released, would it also be
available for those of us that have Etcher Pro?

Thanks again.

**Comment by zwhitchcox** [comment]
Great question @fix3000 We are currently working on automating the process, but for now, I can go ahead and just manually change push the changes to EtcherPro repo.

**Comment by zwhitchcox** [comment]
Oops, didn't mean to close this yet.

**Comment by iamk3** [comment]
Just out of curiosity, is there any update on expected release timeframe?

**Comment by bhjelstrom** [comment]
https://github.com/balena-io/etcher/actions/runs/3423085558
Watching this PR in real time but has failed a few times now :)

**Comment by vrajesh-patel03** [comment]
I am waiting for this fix too.

**Comment by zwhitchcox** [comment]
You can try this out now in version [`1.10.0`](https://github.com/balena-io/etcher/releases/tag/v1.10.0) I do not have a CM4, so I haven't been able to test it myself though. Would someone mind letting me know if it is working?

**Comment by bhjelstrom** [comment]
@zwhitchcox Not working, but I'm pretty sure etcher-sdk needs to be updated to 7.4.2. The PR which upgrades etcher-sdk to 7.4.2 is still failing

https://github.com/balena-io/etcher/pull/3848

https://github.com/balena-io-modules/etcher-sdk/commits/master

**Comment by vrajesh-patel03** [comment]
I can also confirm that it is still not working.

**Comment by iamk3** [comment]
I downloaded and installed 1.10.0. I was able to flash a CM4 with 32GB emmc once I opened rpiboot. I opened etcher, loaded the image to flash, started rpiboot, plugged in the CM4, and it initialized and flashed the image. It never successfully verified, but the flash was successful.

**Comment by vrajesh-patel03** [comment]
@iamk3 Using rpiboot works fine if you're imaging one module at a time. It's when you initialize/mount as USB drive using Etcher that doesn't work with new CM4 modules. I have been using Etcher to image multiple CM4 modules. With the new CM4 modules, I have to run rpitool and can only image one module at a time. I don't know any other imager that can mount multiple CM4 modules and image multiple targets at same time.

**Comment by lurch** [comment]
I don't work on Etcher myself, but I just noticed that https://github.com/balena-io/etcher/releases/tag/v1.13.0 claims to (finally?) fix the CM4 issues in Etcher.

**Comment by mcraa** [comment]
> I don't work on Etcher myself, but I just noticed that https://github.com/balena-io/etcher/releases/tag/v1.13.0 claims to (finally?) fix the CM4 issues in Etcher.

~~claims~~ intends to
but yes that build has the latest etcher-sdk

**Comment by mcraa** [comment]
https://github.com/balena-io/etcher/releases/tag/v1.13.3
Tested with cm4 on windows and mac.
(just to be quicker once than @lurch 😅 )

**Comment by timg236** [comment]
The embedded start4.elf is out of date and won't work on the updated CM4. Patching the files post-install resolves this.

The update was released to Github Jul2021 so I'd recommend modifying the Etcher build-flow to pull in the usbboot as a Git submodule
https://github.com/raspberrypi/usbboot/tree/master/msd

Raspberry Pi provide a tag for each APT release so Etcher can track that.

**Comment by vrajesh-patel03** [comment]
Tested by swapping start4.elf and I can see new CM4 modules mounted as a USB drive. 👍  Would be nice to have it incorporated in the next release.

**Comment by lurch** [comment]
I'm **not** going to steal @mcraa 's thunder this time... :laughing:

**Comment by mcraa** [comment]
No problem @lurch my 3 seconds of fame was enough.
https://github.com/balena-io/etcher/pull/3980 is already there

**Comment by mcraa** [comment]
merged => https://github.com/balena-io/etcher/releases/tag/v1.14.2

**Comment by mcraa** [comment]
It was added to EtcherPro https://github.com/balena-io-hardware/etcherPro-fleet-sw/pull/32#pullrequestreview-1251958682
Release `ccda501` version 1.3.0 is already finalized, and 16 EtcherPros already updated to it.

**Comment by mcraa** [comment]
Thanks for the heads up @bhjelstrom must have been cached, made a new release it has 1.14.3 now.

**Comment by fix3000** [comment]
I can also confirm success of detecting and flashing CM4 and CM3+
(simultaneously, no less) on Etcher Pro. V1.14.3, sn S000079.

Thank you very much for getting this nailed down, my quality of life is
about to improve significantly.

**Comment by mcraa** [comment]
Thanks for confirming again.

The EtcherPro specific issue could go in its repo https://github.com/balena-io-hardware/etcherPro-fleet-sw/issues
Or somewhere in the forums https://forums.balena.io/t/etcherpro-progress-updates/23741/82

**Comment by timetraveler90** [comment]
I still have this issue on Windows 11, what are the options to work around it ?
