### ISSUE TITLE
Does not work on OSX with non admin user

### ISSUE THREAD

**Issue by gradha** [balena-io/etcher#3798]
- **Etcher version:** 1.7.9
- **Operating system and architecture:** osx monterey 12.4.
- **Image flashed:** Clonezila
- **What do you think should have happened:** Flash
- **What happened:** Nothing.
- **Do you see any meaningful error information in the DevTools?** 

When the dialog opens asking for permission, it doesn't allow one to specify a different user than the current one. Thus, if you are trying to flash something with a non admin user, even if you know the user/pass of the admin account the software won't do anything.

![no admin no fun](https://user-images.githubusercontent.com/101927/183512116-70b6e335-e3b6-49aa-a9e8-f1adeb18d1e5.gif)

**Comment by thedocbwarren** [comment]
macOS in general will always work this way from here on.  This is a feature of the OS to manage access to devices.  Writing to a device is privileged access.

**Comment by gradha** [comment]
> macOS in general will always work this way from here on. This is a feature of the OS to manage access to devices. Writing to a device is privileged access.

And that's why macOS in general asks you for the user name of the admin account and does not presume you are on. Or at least that's how it's been for the last 15 years I've been using it as a non admin user.

**Comment by maclm** [comment]
A common example of expected behaviour is updating an app from a standard (non-admin) account: macOS will prompt for username & password.
My hunch is _balenaEtcher_ asks the system for drive access, while it should ask for admin permissions.

**Comment by dfunckt** [comment]
Closing in favor of #3321
