### ISSUE TITLE
Cannot install on Mint 21

### ISSUE THREAD

**Issue by cdaher78** [balena-io/etcher#3803]
- **Etcher version:*latest* 
- **Operating system and architecture:*Linux Mint 21 (vanessa) arch=x86_64* 

Terminal reproducttion:

curl -1sLf \
   'https://dl.cloudsmith.io/public/balena/etcher/setup.deb.sh' \
   | sudo -E bash
Executing the  setup script for the 'balena/etcher' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=linuxmint  version=21  codename=vanessa  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Checking for apt signed-by key support ...
   OK: Importing 'balena/etcher' repository GPG key ...
 NOPE: Checking if upstream install config is OK ...
 ^^^^: ... Failed to fetch configuration for your OS distribution release/version.
 >>>>:
 >>>>: It looks like we don't currently support your distribution release and
 >>>>: version. This is something that we can fix by adding it to our list of
 >>>>: supported versions (see contact us below), or you can manually override
 >>>>: the values below to an equivalent distribution that we do support:
 >>>>:
 >>>>: ... distro=linuxmint  version=21  codename=vanessa  arch=x86_64  
 >>>>:
 >>>>: You can force this script to use a particular value by specifying distro,
 >>>>: version, or codename via environment variable. E.g., to specify a distro
 >>>>: such as Ubuntu/Xenial (16.04), use the following:
 >>>>:
 >>>>:   <curl command> | distro=ubuntu version=16.04 codename=xenial sudo -E bash
 >>>>:
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact balena for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/balena-io/etcher
 !!!!: 
 !!!!: Last 20 log lines from .csm_setup_bp1rtpyL8 (might not be errors, nor even relevant):
 !!!!:
 !!!!: > ii  gnupg                                      2.2.27-3ubuntu2.1
 !!!!: > all          GNU privacy guard - a free PGP replacement
 !!!!: > ii  gnupg-l10n                                 2.2.27-3ubuntu2.1
 !!!!: > all          GNU privacy guard - localization files
 !!!!: > ii  gnupg-utils                                2.2.27-3ubuntu2.1
 !!!!: > amd64        GNU privacy guard - utility programs

**Comment by mcraa** [comment]
your solution is in the error message

> You can force this script to use a particular value by specifying distro,
: version, or codename via environment variable. E.g., to specify a distro
: such as Ubuntu/Xenial (16.04), use the following:
:
: | distro=ubuntu version=16.04 codename=xenial sudo -E bash

and in many duplicates (like #3663), or the setup guides on cloudsmith.
