### ISSUE TITLE
couldn't download of github

### ISSUE THREAD

**Issue by FinGutte** [balena-io/etcher#3816]
- **Etcher version:** 1.7.9
- **Operating system and architecture:** Ubuntu 22.04.1 LTS gnome 42.4
- **Image flashed:**  couldn't download / failed
- **What do you think should have happened:**  restore objects/githudusercontent.com
- **What happened:** unable to download via website https://www.balena.io/etcher/ , tried ppa: clouwdsmith didn't work either
- **Do you see any meaningful error information in the DevTools?**

**Comment by FinGutte** [comment]
probebly my own system ...

**Comment by lurch** [comment]
See https://github.com/balena-io/etcher/releases/tag/v1.7.9 for the direct download links.
