### ISSUE TITLE
usb drive randomly stop being able to flashed

### ISSUE THREAD

**Issue by maxtraxv3** [balena-io/etcher#3818]
- **Etcher version:** 1.7.9
- **Operating system and architecture:** windows 11 22h2 update
- **Image flashed:** ubuntu, 22.04 ubuntu server 22.04, fedora 36, cent os 9, void, antix
- **What do you think should have happened:**  flashed the usb.
- **What happened:** error? this has happend 2 usb driver, but they formant and work fine, after a few flashes etcher become unable to flash that usb drive? why i dont know, they work fine.
- **Do you see any meaningful error information in the DevTools?** 

gui.js:46 Mon Oct 03 2022 04:20:09 GMT+1000 (Australian Eastern Standard Time) Flash error ({"image":{"size":2076180480,"name":"freelnxinstaller_20120308.iso","hasMBR":true,"partitions":[{"offset":0,"size":2076180480,"type":23,"index":1}],"extension":"iso","path":"C:\\Users\\maxtr\\Downloads\\freelnxinstaller_20120308.iso"},"drives":[{"size":123060879360,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive2","error":null,"isReadOnly":false,"displayName":"E:\\","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive2","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[{"path":"E:\\"}],"description":" USB  SanDisk 3.2Gen1 USB Device","isUAS":false,"partitionTableType":"mbr"}],"driveCount":1,"uuid":"912243d6-56a5-40d5-b249-4dc20ac53e95","flashInstanceUuid":"912243d6-56a5-40d5-b249-4dc20ac53e95","error":{"name":"Error","message":"Couldn't clean the drive, Command failed: diskpart s n (code 2147942405)","stack":"Error: Couldn't clean the drive, Command failed: diskpart s n (code 2147942405)\n    at clean (C:\\Users\\maxtr\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:1:51429)\n    at async BlockDevice._open (C:\\Users\\maxtr\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:1:12058)\n    at async BlockDevice.open (C:\\Users\\maxtr\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:1:107090)\n    at async n    at async Promise.all (index 0)\n    at async MultiDestination._open (C:\\Users\\maxtr\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:35:149778)\n    at async MultiDestination.open (C:\\Users\\maxtr\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:1:107090)\n    at async Promise.all (index 1)\n    at async pipeSourceToDestinations (C:\\Users\\maxtr\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:35:407810)\n    at async decompressThenFlash (C:\\Users\\maxtr\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:35:406199)"},"sample":0.1,"applicationSessionUuid":"3c45cb75-ae77-4fa3-9e49-5bfe4ec2649b","flashingWorkflowUuid":"c7564e3d-d0cd-4d1b-89dc-5bf2645fae41"})

this was me trying to flash to a usb that had been flash by it 2 time before.

normal user, pluged into usb3 front port, programs open VLC, vivaldi (chrome based web browser), steam, discord.

**Comment by mcraa** [comment]
Hi,

thanks for the info, the randomness is indeed interesting.
Can you try the failing part manually with the same device?

> Open `cmd.exe`
Execute `diskpart.exe`, it gives you diskpart's command line prompt
Execute `list disk` inside diskpart to show the available drives. Take note of the `id` of the drive in question
Execute `select disk N`, where `N` is the id of the removable drive obtained above (make sure you select the right one, otherwise you might wipe out another drive unintentionally)
Execute `clean`
check the result then exit from diskpart and cmd

Does it give any error or it cleans the drive?

**Comment by maxtraxv3** [comment]
no it does not, works fine, on all 3 usb drives that are all different brands, one is usb 2 and the others usb 3.

**Comment by laymanstake** [comment]
The same issue broken two of my usb drives in attempts to flash centos images while rufus can do the same and so is dd.  OS is Windows 11 22H2. Version is latest
