### ISSUE TITLE
I can't Install Balena Etcher on my Ubuntu

### ISSUE THREAD

**Issue by Antonio-Urso** [balena-io/etcher#3820]
- **Etcher version:** 
- I use the latest version of Ubuntu
- I wanted to install Balena Etcher, but I can't do it using the terminal, couldn't even add the repository from Terminal
- I can't install the program 

The command I used and doesn't work was the following: curl -1sLf \
   'https://dl.cloudsmith.io/public/balena/etcher/setup.deb.sh' \
   | sudo -E bash

I've used similar commands which also don't work

The terminal said it "Failed to update via apt-get update" and Idk what to do next

**Comment by lurch** [comment]
Do you get any errors if you run `sudo apt-get update` by itself?
