### ISSUE TITLE
Half Presentation

### ISSUE THREAD

**Issue by Chamier** [balena-io/etcher#3872]
- **Etcher version:** 3.7.9
- **Operating system and architecture:** MacOS 13.0.1
- **Image flashed:** 
- **What do you think should have happened:** 
- **What happened:** At open app only half is shown
- **Do you see any meaningful error information in the DevTools?** 

![Captura de pantalla 2022-11-11 a la(s) 09 57 07](https://user-images.githubusercontent.com/10067626/201380156-88acbfa1-d08d-4fe5-a8d7-641993bf967d.png)

**Comment by mcraa** [comment]
You mean 1.7.9 is the version?
Please share if there is any errors in the devtools (pressing cmd + shift + i )
