### ISSUE TITLE
Website version is not updated

### ISSUE THREAD

**Issue by XLixl4snSU** [balena-io/etcher#3879]
The latest version on https://www.balena.io/etcher is shown and downloaded as 1.7.9, while the newest version on Github is 1.10.0

**Comment by JohnTHaller** [comment]
I'd wager this is because 1.7.9 is still considered the stable version. The build process was recently automated and has gone a little haywire with sometimes hourly releases since: https://github.com/balena-io/etcher/issues/3853

**Comment by XLixl4snSU** [comment]
Seems "fixed" now even if the new release integration is just ....

**Comment by JohnTHaller** [comment]
It's outdated by two versions already. I don't think this will be fixed until this is implemented: https://github.com/product-os/flowzone/pull/355
