### ISSUE TITLE
App doesn't install on Linux(Ubuntu 22.04)

### ISSUE THREAD

**Issue by saki-osive** [balena-io/etcher#3885]
- **Etcher version:** : v1.10.1
- **Operating system and architecture:** : x86_64 Ubuntu 22.04 LTS
- **Image flashed:**  : None
- **What do you think should have happened:**  : App doesn't start
- **What happened:** : App doesn't install via AppImage or .deb package installation methods.
- **Do you see any meaningful error information in the DevTools?**  : Nope

**Comment by gurashish1singh** [comment]
Can confirm this error. Followed the README steps to add ppa and install the app through the terminal. It fails while assigning permissions:
![image](https://user-images.githubusercontent.com/51451177/204379742-9751a5e4-7308-488a-b918-651b23ecc79d.png)

**Comment by prissypants** [comment]
W: Failed to fetch https://deb.etcher.io/dists/stable/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 52.41.41.147 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
merrill@merrill-HP-Pavilion-Laptop-17-ar0xx:~$ sudo apt install balena-etcher-electron
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package balena-etcher-electron

**Comment by lurch** [comment]
`deb.etcher.io` was the old BinTray repository, not the new CloudSmith repository? Perhaps one of the Etcher developers ought to update #3501 with instructions for disabling the old BinTray repository (if the user had previously enabled it) ?

**Comment by prissypants** [comment]
Finally got it up after going round and round it both on my laptop and pc. No problems before with etcher until I changed both systems to 22.04

Thx for reply

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by ja7833** [comment]
balenaEtcher also does not install on Zorin 16.2/Ubuntu 20.04.3

I downloaded the .AppImage, enabled the “Allow executing file as program” option in permissions, and it just opens an empty window.

See also https://forums.balena.io/t/balenaetcher-not-working-on-zorin-os/365919/5

**Comment by lurch** [comment]
See https://github.com/balena-io/etcher/issues/3884#issuecomment-1335324287 ?

**Comment by aethernet** [comment]
This is fixed in 1.10.6 (just manually tested the 3 latest Ubuntu LTS 18.04, 20.04 and 22.04 to be sure)

**Comment by lurch** [comment]
Just out of curiosity, do versions of Etcher after #3935 still run on Ubuntu 18.04 LTS?
