### ISSUE TITLE
Blank screen when launching etcher

### ISSUE THREAD

**Issue by lgwds** [balena-io/etcher#3898]
- **Etcher version:** 1.10.2-x64
- **Operating system and architecture:** Ubuntu 20.04.5 LTS
- **Image flashed:** None
- **What do you think should have happened:** open etcher with GUI elements visible after launch from terminal
- **What happened:** blank screen similar to  #3558
- **Do you see any meaningful error information in the DevTools?** 
![image](https://user-images.githubusercontent.com/67753842/205440503-425c7793-2da6-4c02-8449-2c2c6b403b57.png)

I have tried to change the TMPDIR as mentioned in #3558 as follows:
TMPDIR=/home/$user/tmp/ ./balenaEtcher-1.10.2-x64.AppImage

However, this yielded the same result - a blank screen with the error message seen in the image above (Uncaught Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found)

**Comment by lurch** [comment]
#3893 suggests that this ought to be fixed in a [newer version](https://github.com/balena-io/etcher/releases) ?

**Comment by lgwds** [comment]
the newest version (1.10.6) solves the issue. Thanks @lurch!
