### ISSUE TITLE
Error: Cannot read property '0' of undefined on Windows 11 with Version 1.10.6

### ISSUE THREAD

**Issue by brysonboettger** [balena-io/etcher#3900]
- Etcher version: 1.10.6 
- Windows 11 on an ASUS VivoBook -- see image for computer specs
- SD Card bootable image (.bz2 Firmware file)

When trying to "Flash from file," it gave me the error: 'Error Opening Source:... Error: Cannot read property '0' of undefined.' I reverted back to V1.7.0 (After reading a [forum](https://forums.balena.io/t/flash-failed-cannot-read-property/350420) from december '21) and the error did not occur. I was able to flash my image as desired after reverting back. 

If this could be fixed on the latest Balena Version that would be great. 

Please see the attached screenshots for the computer specs/error information.
![Screenshot (24)](https://user-images.githubusercontent.com/87095364/205694828-a91fc090-a227-47ee-90ca-d5e6344c7777.png)
![Screenshot (25)](https://user-images.githubusercontent.com/87095364/205694887-27fcc140-988b-4f7b-9093-8b0699de5a0b.png)

**Comment by Seigiard** [comment]
have same issue on macos with versions 1.10.x and  v1.11.10

v. 1.7.0 works well

**Comment by lurch** [comment]
Looks to be related to #3901 which is also using a `.bz2` file :thinking:   Does it work if you manually decompress the image before trying to flash it with Etcher?

**Comment by visualnaut** [comment]
> Looks to be related to #3901 which is also using a `.bz2` file 🤔 Does it work if you manually decompress the image before trying to flash it with Etcher?

Happened also to me. And yes I think choosing `.bz2` file is the issue. If you decompress the file first, it worked.

**Comment by mcraa** [comment]
same as https://github.com/balena-io/etcher/issues/3901#issuecomment-1369173626
