### ISSUE TITLE
USB stick unusable after flashing with Balena

### ISSUE THREAD

**Issue by ZippoLag** [balena-io/etcher#3902]
- **Etcher version:** 1.10.2
- **Operating system and architecture:** Windows 10 Home x64
- **Image flashed:** linuxmint-21-cinnamon-64bit.iso
- **What do you think should have happened:** I wanted to have Linux Mint's ISO flashed into a USB stick, instead now I have an unusable USB stick which can't be formatted.
- **What happened:**
I inserted an 8gb USB stick into the port and ran Balena Etcher, flashing the latest linux mint ISO into it. The process claimed to finish successfully, however the drive stopped being recognized by Windows and asked for a format, now reporting that the size is around 2gb, instead of 8gb, and saying that it can't be formatted due to write protection:
![image](https://user-images.githubusercontent.com/755062/206007581-e63dd0f6-1163-47e4-b4fa-cc35780908f7.png)
I tried plugging the stick on a Linux machine and it's not recognized either. Nor can I use it to boot as intended.
Curiously, though, if I start Balena again the program still recognizes the drive as 8gb!
![image](https://user-images.githubusercontent.com/755062/206008396-e3343084-0267-4471-a54c-047609a1458c.png)

- **Do you see any meaningful error information in the DevTools?** 
The only error I see in the dev tools is regarding a "disable screensaver" event:
`{"stack":"Error: Error invoking remote method 'disable-screensaver': No handler registered for 'disable-screensaver'\n    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73:529)","message":"Error invoking remote method 'disable-screensaver': No handler registered for 'disable-screensaver'"}`

This may be related to [3241](https://github.com/balena-io/etcher/issues/3241), but I don't use bitlocker or any encryption software.

Is there any way I may recover this device?

**Comment by lurch** [comment]
See https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives and https://www.balena.io/blog/did-etcher-break-my-usb-sd-card/

**Comment by RV-Levi** [comment]
Me too, but flashing bodhi Linux on Windows 8.1.

**Comment by RV-Levi** [comment]
Me too, but flashing bodhi Linux on Windows 8.1.

**Comment by aethernet** [comment]
See lurch links.
