### ISSUE TITLE
myself

### ISSUE THREAD

**Issue by jbaryy708** [balena-io/etcher#3958]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **What do you think should have happened:** 
- **What happened:**
- **Do you see any meaningful error information in the DevTools?** 

`[log_2022-12-24_14-54-06.log](https://github.com/balena-io/etcher/files/10299045/log_2022-12-24_14-54-06.log[)](### url)`

**Comment by aethernet** [comment]
Hello @jbaryy708 
There's nothing we can do with so little infos.
I'll close the issue, but feel free to reopen with new infos.
