### ISSUE TITLE
Website version is n-4

### ISSUE THREAD

**Issue by binkleyz2** [balena-io/etcher#3963]
Current version is 1.10.6 but the website is still on 1.10.2.

This may be purposeful, but wanted to point it out in case it was an oversight.

![Screenshot 2022-12-30 081656](https://user-images.githubusercontent.com/68412862/210074217-e86edd51-573f-4fbf-8897-0789146d1f66.jpg)

**Comment by mcraa** [comment]
Thanks, we know
the CI update and the recent storm of releases produced some regression and we don't want to update it everywhere until it looks stable.
You can already find 1.13.0 prerelease on github, compared to 1.10.6 marked latest, and 1.7.9 latest on linux ppa-s.
