### ISSUE TITLE
bag in windows

### ISSUE THREAD

**Issue by nikolay-mansas** [balena-io/etcher#3975]
- **1.13.1** 
- **windows x64** 
- **all** 
- **start flashing random iso**
[IMG] https://drive.google.com/file/d/1z6c050euT2fpZvJUwOiiuw2-eocGhh7u/view?usp=share_link [IMG]

**Comment by aethernet** [comment]
oh that's a weird one!

Thanks for reporting

**Comment by mcraa** [comment]
duplicate to more detailed #3981
