### ISSUE TITLE
Balena Etcher Design crashed...

### ISSUE THREAD

**Issue by blcklptn** [balena-io/etcher#3983]
- **Etcher version:**  1.13.1
- **Operating system and architecture:** Exodia OS, KDE, x86-64
- **Image flashed:**  Crystal Linux
- **What do you think should have happened:** Normal design
- **What happened:**

![2023-01-20_14-14](https://user-images.githubusercontent.com/73552143/213659400-9dec146b-72ac-4428-9bb1-2e002ff12473.png)

**Comment by mcraa** [comment]
thanks for the feedback, tracking it in #3981
