### ISSUE TITLE
setup.rpm.sh asks for yum-utils, which fails on F37

### ISSUE THREAD

**Issue by opohorel** [balena-io/etcher#4015]
Tested on Fedora 37

On line 521 of setup.rpm.sh script, there is a `check_rpm_tool "yum-utils"`.
"yum-utils" can't be currently installed on F37, as it is a retired package.
There is a "dnf-utils" package that provides the same functionality.

Simply switching to `check_rpm_tool "dnf-utils"`, makes this script work flawlessly.

Please consider changing condition to something like:
```

    if test "$manager" == "yum"; then
        check_rpm_tool "yum-utils"
    fi

    if test "$manager" == "dnf"; then
        check_rpm_tool "dnf-plugins-core"
    fi
```
"dnf-plugins-core" provides both "dnf-utils" and "dnf-plugin-config-manager"

**Comment by mcraa** [comment]
Thanks for the feedback, and the proposed solution
as shown in the readme 
>[![Hosted By: Cloudsmith](https://img.shields.io/badge/OSS%20hosting%20by-cloudsmith-blue?logo=cloudsmith&style=for-the-badge)](https://cloudsmith.com) \
Package repository hosting is graciously provided by  [Cloudsmith](https://cloudsmith.com)

 the setup sh is maintained by them.
If you can raise the issue to them that would be helpful, we will check and ping them as well.

**Comment by opohorel** [comment]
I pinged them on their support mail. Thanks for pointing it out

**Comment by opohorel** [comment]
Cloudsmith has resolved this issue now with an updated setup.rpm.sh
