### ISSUE TITLE
DNF etcher black when opening

### ISSUE THREAD

**Issue by intresti** [balena-io/etcher#4017]
When i open etcher:

![Screenshot from 2023-02-17 14-09-40](https://user-images.githubusercontent.com/125667224/219677946-5bff27a6-edf9-412f-9fee-a557675e0c30.png)

**Comment by ctyfrank** [comment]
是不支持win7了吗？我打开白屏。
![image](https://user-images.githubusercontent.com/91655350/222164945-7122b1ff-4f51-4a83-be5e-9e4eb3d7dee1.png)
我不知道如何补充更多信息？就是打开，白屏，没有然后了。哦，试了管理员与非管理员都不行。V1.14.3
