### ISSUE TITLE
Archlinux install ISO image issue, unable to trim unallocated disk space

### ISSUE THREAD

**Issue by nt74** [balena-io/etcher#4020]
- **Etcher version:** 
_1.18.4_
- **Operating system and architecture:** 
_Arch Linux 6.1.15-1-lts x86_64_
- **Image flashed:** 
_https://geo.mirror.pkgbuild.com/iso/2023.03.01/archlinux-2023.03.01-x86_64.iso_
- **What do you think should have happened:** 
_Flash USB-stick and trim unallocated space not to have unused disk space._
- **What happened:**
1. _Flash image successfully, but doesn't trim the unallocated disk space to full USB-stick capacity (in my case 8GB stick)._
2. _Results in issues when trying to install Arch Linux `archinstall` install script which detects the unallocated USB-stick disk space. This makes the `archinstall` automated install script exit with an error._
3. _I tried via Linux with dd method with the same results._
4. _Only working method is using Rufus tool on Windows (10/11) OS._
- **Do you see any meaningful error information in the DevTools?** 
_No_

**Comment by lurch** [comment]
https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#how-can-i-configure-persistent-storage
