### ISSUE TITLE
ads interupt password prompt

### ISSUE THREAD

**Issue by ghost** [balena-io/etcher#4030]
- **Etcher version:1.18.6** 
- **Operating system and architecture:*Linux Mint 21.1 x64** 
the problem is when you get password prompt you enter maybe the first two character, then it looses the focus and you have to click in the password prompt to complete the password

**Comment by aethernet** [comment]
This is weird, you mean the main windows catch back the focus when it loads the community featured project or the etcher pro page?

**Comment by aethernet** [comment]
Note that 1.8.5 is quite old, and won't be fixed. If the issue still exists with the latest version I might check it.

**Comment by Chipsum** [comment]
> Note that 1.8.5 is quite old, and won't be fixed. If the issue still exists with the latest version I might check it.

rly ? what's the latest version up to date ? and where to get it from ?

**Comment by ax4** [comment]
@Chipsum Probably you can get from GitHub latest release page at https://github.com/balena-io/etcher/releases/tag/v1.18.4

**Comment by Chipsum** [comment]
Oh sorry my version is 1.18.5 not 1.8.5 my bad :pray:

**Comment by aethernet** [comment]
:D Thanks for clarifying

**Comment by dfunckt** [comment]
Fixed by #4075.
