### ISSUE TITLE
Help button directs to wrong link

### ISSUE THREAD

**Issue by Latgardi** [balena-io/etcher#4039]
- **Etcher version: 1.18.4** 
- **Operating system and architecture: Linux Mint 21.1 amd64** 
- **Image flashed: none** 
- **What happened: error 404**
- **Do you see any meaningful error information in the DevTools?** 
- (let it be here) Failed to load resource: net::ERR_FILE_NOT_FOUND index.css:1

Help button directs to wrong link. Got 404 error.

**Comment by lurch** [comment]
See #4021 ?

**Comment by aethernet** [comment]
fixed by https://github.com/balena-io/etcher/pull/4056
