### ISSUE TITLE
How do I run etcher-electron from CLI after install?? Can't seem to find a straight answer other than it was deprecated in 2019. I don't have a GUI as I'm using Chrostini Debian Bullseye 11 on Chromebook and all I'm trying to do make a live USB boot. PLEASE HELP ME!!!!

### ISSUE THREAD

**Issue by haxzor420** [balena-io/etcher#4040]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **What do you think should have happened:** 
- **What happened:**
- **Do you see any meaningful error information in the DevTools?**

**Comment by aethernet** [comment]
Hello, 

There's not any official CLI for etcher atm.

Nonetheless you can use the etcher-sdk multi-destination example to do what you need (but keep in mind it's not officially supported so use at your own risks): https://github.com/balena-io-modules/etcher-sdk/blob/master/examples/multi-destination.ts

You can call it as `node-ts multi-destination.ts /path/to/source /path/to/destination`
