### ISSUE TITLE
Writing Failed

### ISSUE THREAD

**Issue by Boca-NeedM** [balena-io/etcher#4042]
- **Etcher version:** 1.18.4
- **Operating system and architecture:** W11 64Bit
- **Image flashed:** Debian-Buster-Server-Odroidc4-20210301.img.xz
- **What do you think should have happened:** 
- **What happened:** Writing fails
- **Do you see any meaningful error information in the DevTools?** No

Error: Error invoking remote method 'enable-screensaver': No handler registered for 'enable-screensaver'
    at o.invoke (node:electron/js2c/renderer_init:57:526)

**Comment by dfunckt** [comment]
That error is innocuous, doesn't have any effect on flashing.

If flashing indeed failed, try unpacking the img file and flash that instead.
