### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by zckman** [balena-io/etcher#4043]
- **Etcher version:** 
1.18.4  

- **Operating system and architecture:** 
Windows 10 x64

- **Image flashed:** 
None, happens on start

- **What happened:**
![image](https://user-images.githubusercontent.com/18466068/229631282-04f6fc45-4647-4bf4-9bb8-36c29f6fed1d.png)

- **Do you see any meaningful error information in the DevTools?** 

```
Uncaught ReferenceError: require is not defined
    at Object.<anonymous> (external "electron":1:1)
    at __webpack_require__ (bootstrap:19:1)
    at Object.<anonymous> (app.ts:18:18)
    at __webpack_require__ (bootstrap:19:1)
    at bootstrap:83:1
    at bootstrap:83:1
```

If you need additional information please ask.

**Comment by dfunckt** [comment]
Can you please try v1.18.9?

I'm closing the issue. Just reopen it if you still get the same error on the new version.
