### ISSUE TITLE
ibm: ppc64le: Etcher for power pc.

### ISSUE THREAD

**Issue by carlosgonz0** [balena-io/etcher#4044]
It would be nice a balenaEtcher-1.1*.*-ppc64le.AppImage

**Comment by lurch** [comment]
https://www.electronjs.org/docs/latest/development/build-instructions-linux#cross-compilation :thinking:

**Comment by dfunckt** [comment]
I appreciate the request and it would be great for Etcher to run on every conceivable platform but time and resources are not infinite hence we must prioritize what platforms we support.

This is where the community can step in and provide forks with platform-specific support and we'd be extremely happy to accept PRs removing blockers on the way.
