### ISSUE TITLE
Unable to locate package balena-etcher-electron :(

### ISSUE THREAD

**Issue by wildchamo** [balena-io/etcher#4045]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **What do you think should have happened:** 
- **What happened:**
- **Do you see any meaningful error information in the DevTools?**

**Comment by aethernet** [comment]
this package has been deprecated a while ago.

the new package is `balena-etcher`, note that we currently don't provide repositories for .deb or .rpm and we recommend you get the package from the GH release page.
