### ISSUE TITLE
Wrong link in (?) button in windows version

### ISSUE THREAD

**Issue by SegoItCh** [balena-io/etcher#4049]
The 'balena-io/etcher' repository doesn't contain the 'SUPPORT.md' path in 'master'.

**Comment by lurch** [comment]
See #4021 ?

**Comment by SegoItCh** [comment]
I'm on latest Release version(1.18.4)

**Comment by aethernet** [comment]
Fixed by https://github.com/balena-io/etcher/pull/4056
