### ISSUE TITLE
Lost Source and target drive after computer goes to sleep

### ISSUE THREAD

**Issue by ReinerKrause** [balena-io/etcher#4054]
- **Etcher version: 1.5.109** 
- **Operating system and architecture: Win11 64bit** 
- **Image flashed: M2 SSD with USB adapter to USB Disk** 
- **What do you think should have happened: 
- Selected Source and target
- After that i started cloning which runs normally
- I've expected that the proces runs untile the end.
- **What happened:**
- The computer (Laptop connected to Power) goes into StandBy after 40% of the copy process
- After waking up the laptop, Balena Etcher remains blank and did not recover** 
- Both Disks remain disconnected from windows. Even after reboot the target (and especially) the source are no more visible in Windows Explorer.
- Also in disk management it is not possible to assign a drive letter.

--> Is there a way to get the Source drive back to work?

- **Do you see any meaningful error information in the DevTools? ** 
No informations!

**Comment by aethernet** [comment]
Did you plug it out and back in? 

Etcher is only reading the source, there's no write action on it, whatever windows does to a disk when going to sleep is not controlled by etcher.

**Comment by ReinerKrause** [comment]
That doesn't seem quite right to me.As soon as I connect the two drives to the computer, they get a drive letter.When I start the clone process, both drives are unmounted from the file system.This is the state that both the target and the source are now in after Balena Etcher crashed due to the standby.-- Am 25.04.2023 um 14:35 schrieb Edwin Joassart ***@***.***>:﻿
Closed #4054 as completed.
