### ISSUE TITLE
sudo apt-get update terminal cmd results in balena-etcher error msgs

### ISSUE THREAD

**Issue by thecag** [balena-io/etcher#4063]
- **Etcher version - 1.18.4** 
- **Operating system and architecture: - Ubuntu 22.04.2 LTS** 
- **Expected cmd to complete successfully** 
- **What happened: - Error msgs generated for balena-etcher**
- **Do you see any meaningful error information in the DevTools? - not applicable** 

[failed to download repository information.txt](https://github.com/balena-io/etcher/files/11400687/failed.to.download.repository.information.txt)

I attached a file containing the cmd I issued and the msgs I received.

**Comment by lurch** [comment]
See #4059
