### ISSUE TITLE
Request: Feature to format devices

### ISSUE THREAD

**Issue by sonik-br** [balena-io/etcher#4071]
Hi,

Not a issue but a feature request.

Would be handy to have a feature on the app to let the user format a device with the option the select the file system.

This can be useful specially under windows as it limits the file system selection for some devices (ie: can't select FAT32 on 128GB SD/USB device).

I know that this is not the main focus of the app and I understand if it's not a planned feature.

**Comment by dfunckt** [comment]
Thanks for the suggestion, but that feels quite beyond the scope of Etcher.
