### ISSUE TITLE
Flash drive dissapears after flashing via BalenaEtcher

### ISSUE THREAD

**Issue by winguy452** [balena-io/etcher#4078]
- **Etcher version: 1.18.8** 
- **Windows 11 22H2** 
- **Image flashed: Olarila High Serria** 
- **What happened: I flashed a High Serrria .raw file, but when it was done, it couldn't be seen on Explorer! It also wasnt visible on diskpart either.**
- **Do you see any meaningful error information in the DevTools?** Nope. None

Please help me, I have been searching for days!

**Comment by dfunckt** [comment]
The image likely does not contain partitions in a filesystem supported by Windows. Try inspecting the drive in a Linux-y OS.

**Comment by winguy452** [comment]
Ok thank you, I will try that.

**Comment by winguy452** [comment]
> The image likely does not contain partitions in a filesystem supported by Windows. Try inspecting the drive in a Linux-y OS.

Ok thqnk you, i will try that.
