### ISSUE TITLE
Clicking the Get EtcherPro button doesn't do anything

### ISSUE THREAD

**Issue by arikmaor** [balena-io/etcher#4084]
- **Etcher version:** 1.18.4
- **Operating system and architecture:** OSx M1
- **Image flashed:** Pop!_OS
- **What do you think should have happened:** When clicking the _get EthcherPro_ button, something should happen
- **What happened:** nothing

Just thought you should know...

**Comment by dfunckt** [comment]
Hey, thanks for reaching out. Seems like this is another victim of the recent updates of Electron and its new versions aggressively sandboxing the process.

**Comment by dfunckt** [comment]
Fixed in [v.1.18.9](https://github.com/balena-io/etcher/releases/tag/v1.18.9)
