### ISSUE TITLE
Problem In Ubuntu...

### ISSUE THREAD

**Issue by Maydo-x** [balena-io/etcher#4095]
Opreation System Ubuntu 22.04 
Comand Line Not Working
its says E: Unsupported file ./balena-etcher_******_amd64.deb given on commandline

**Comment by lurch** [comment]
I think where the stars / asterisks are, it means "type in the filename of the file that you actually downloaded" ?

**Comment by Maydo-x** [comment]
No the command they type

**Comment by dfunckt** [comment]
You just need to replace the asterisks with the version you downloaded, eg. `[balena-etcher_1.18.12_amd64.deb](https://github.com/balena-io/etcher/releases/download/v1.18.12/balena-etcher_1.18.12_amd64.deb)`.

**Comment by Maydo-x** [comment]
Alr
