### ISSUE TITLE
BalenaEtcher requests userpassword instead of PIN when native smart card is present

### ISSUE THREAD

**Issue by atjbramley** [balena-io/etcher#4117]
**Etcher version:** 
1.18.11

**Operating system and architecture:** 
macOS Sonoma / ARM

**Image flashed:** 
N/A

**What do you think should have happened:**
- configure Yubikey in PIV mode (to replace passwords with the PIN of the Yubikey) (https://www.yubico.com/works-with-yubikey/catalog/macos/)
- configure Yubikey so that a PIN is required before they it be used
- attempt to flash any image to a disk

**What happened:**
- a prompt appears asking for the user's *password*
- when the user password is entered, the prompt silently fails, and replaces itself

**What should happen:**
- the prompt should be asking for the PIN of the Yubikey.  Entering the PIN allows the flashing to continue successfully.

**Do you see any meaningful error information in the DevTools?** 
N.A

**Comment by atjbramley** [comment]
<img width="861" alt="Screenshot 2023-10-12 at 17 20 59" src="https://github.com/balena-io/etcher/assets/71517198/c33afb20-99a5-458a-93fd-9fd6d78701e8">

A screenshot of the dialogue box that requests a password instead of a PIN as it should.

**Comment by pushshift** [comment]
Just out of curiosity, did you you try putting in your PIN for this dialog box? I'm wondering if it is just a dialog issue but you said in your original post that you tried your user password -- I'm wondering if you try putting in your PIN instead if it succeeds or not.

**Comment by lurch** [comment]
See the comments in #3627

**Comment by atjbramley** [comment]
@lurch agreed - #3627 and related covers this well.  Thank you!

@pushshift - yes, it works with the PIN.  #3627 gives a detailed breakdown - it's a prompt emulating a system prompt, which ends up passing the wrong credentials (password instead of PIN).
