### ISSUE TITLE
v1.18.13 on Kubuntu 23.10: "Error: requestMetadata is not a function" when opening image

### ISSUE THREAD

**Issue by NotizMe** [balena-io/etcher#4138]
- **Etcher version:** v1.18.13
- **Operating system and architecture:**  Kubuntu 23.10 x64
- **Image flashed:** debian-12.2.0-i386-netinst.iso (https://cdimage.debian.org/debian-cd/current/i386/iso-cd/debian-12.2.0-i386-netinst.iso)
- **Reproduction process:**
1. Build and install Etcher
```bash
git clone git@github.com:balena-io/etcher.git
cd etcher
# Getting .resinci.json, see issue #4136 
git checkout 292f86d6f5b0e8dd34cb3dd6e008517f9a066cd0 .resinci.json
make electron-develop
# Removing gconf dependencies, see issue #4137
sed -i '/gconf/d' electron-builder.yml
sed -i '/gconf/d' docs/USER-DOCUMENTATION.md
sed -i '/gconf/d' scripts/resin/electron/electron-builder.json
make electron-build
sudo apt install ./dist/balena-etcher-electron_1.18.13+e9697359_amd64.deb
```
2. Open Etcher
3. Pick file
- **What do you think should have happened:** I can continue
- **What happened:**
Message box: Error opening source
```
Something went wrong while opening /home/pieter/downloads/debian-12.2.0-i386-netinst.iso.

Error: requestMetadata is not a function
```
![Error message](https://i.imgur.com/ZKcEmMyl.png)

- **Do you see any meaningful error information in the DevTools?** Nothing in the dev console
# Extra info
v1.18.12 works perfectly when using the same workarounds for:
- #4136
- #4137

**Comment by anubhavjha0812** [comment]
Why this issue is closed it's still not resolved???
