### ISSUE TITLE
Unable to get executable file 

### ISSUE THREAD

**Issue by MirzayevFarid** [balena-io/etcher#4153]
- **Etcher version:** 1.18.13
- **Operating system and architecture:** Mac OS m1
- **Image flashed:** -
- **What do you think should have happened:**  Generate executable file (.dmg or exe)
- **What happened:** I don't see any executable file. Even do not know where should it appear
- **Do you see any meaningful error information in the DevTools?** 

When I run npm run build command, I see following output and when I npm start, program works as expected. I want to generate my own version of the etcher with some changes that I made. Unfortunately I am not able to get executable file by using following command. I saw that some people used make electron-build command but I am not sure whether it is right command or not. If I try that I get following error:

********************************************************************************************************************************

make electron-build
./scripts/resin/electron/build.sh \
		-b /Users/faridmirzayev/Desktop/Files/Dev/etcher \
		-r x64 \
		-s darwin \
		-v production \
		-n dist/.tmp/npm
make: ./scripts/resin/electron/build.sh: No such file or directory
make: *** [electron-build] Error 1

********************************************************************************************************************************

npm run build

> balena-etcher@1.18.13 build
> npm run webpack && npm run build:sidecar

> balena-etcher@1.18.13 webpack
> webpack

[06:36:36] Webpack: Starting ...

[06:36:36] Webpack (0%) - Compile modules
[06:36:36] Webpack (1%) - Compile modules
[06:36:36] Webpack (1%) - Compile modules
[06:36:36] Webpack (1%) - Compile modules
...
[06:36:36] Webpack (9%) - Compile modules
...
[06:36:42] Webpack (70%) - Build modules
[06:36:42] Webpack (71%) - Optimize modules (sealing)
...
[06:36:46] Webpack (99%) - Emit files

[06:36:46] Webpack: Finished after 9.431 seconds.

[06:36:46] Webpack (24%) - Build modules
...
[06:36:47] Webpack (70%) - Build modules
[06:36:47] Webpack (71%) - Optimize modules (sealing)
...
[06:36:50] Webpack (94%) - Optimize modules (sealing)
[06:36:50] Webpack (95%) - Emit files
...
[06:36:50] Webpack (99%) - Emit files

[06:36:50] Webpack: Finished after 3.685 seconds.

[06:36:50] Webpack (99%) - Emit files
[06:36:50] Webpack (99%) - Emit files

[06:36:50] Webpack: Finished after 0.000 seconds.

[06:36:50] Webpack (99%) - Emit files
[06:36:50] Webpack (99%) - Emit files

[06:36:50] Webpack: Finished after 0.000 seconds.

assets by path lib/gui/app/css/fonts/*.ttf 525 KiB
  asset lib/gui/app/css/fonts/SourceSansPro-Regular.ttf 263 KiB [compared for emit] [from: lib/gui/app/css/fonts/SourceSansPro-Regular.ttf] (auxiliary name: gui)
  asset lib/gui/app/css/fonts/SourceSansPro-SemiBold.ttf 262 KiB [compared for emit] [from: lib/gui/app/css/fonts/SourceSansPro-SemiBold.ttf] (auxiliary name: gui)
asset gui.js 1.71 MiB [compared for emit] [minimized] (name: gui)
asset media/icon.png 5.4 KiB [compared for emit] [from: assets/icon.png] [copied]
asset index.html 252 bytes [compared for emit] [from: lib/gui/app/index.html] [copied]
orphan modules 6.34 MiB [orphan] 1853 modules
runtime modules 2.5 KiB 10 modules
built modules 2.89 MiB [built]
  modules by path ./node_modules/ 1.76 MiB 413 modules
  modules by path ./lib/ 1.13 MiB
    modules by path ./lib/gui/app/ 1.12 MiB
      modules by path ./lib/gui/app/models/*.ts 48.4 KiB 5 modules
      modules by path ./lib/gui/app/css/ 2.51 KiB 3 modules
      modules by path ./lib/gui/app/*.ts 1.07 MiB 2 modules
    modules by path ./lib/shared/*.ts 10.3 KiB
      ./lib/shared/messages.ts 3.57 KiB [built] [code generated]
      ./lib/shared/drive-constraints.ts 3.42 KiB [built] [code generated]
      ./lib/shared/errors.ts 2.65 KiB [built] [code generated]
      ./lib/shared/utils.ts 636 bytes [built] [code generated]
  + 11 modules
webpack 5.75.0 compiled successfully in 13627 ms

asset etcher.js 1.26 MiB [compared for emit] [minimized] (name: etcher)
orphan modules 1.48 MiB [orphan] 354 modules
runtime modules 1.4 KiB 7 modules
built modules 2.42 MiB [built]
  cacheable modules 1.7 MiB 235 modules
  + 22 modules
webpack 5.75.0 compiled successfully in 9380 ms

> balena-etcher@1.18.13 build:sidecar
> npm run build:rebuild-mountutils && tsc --project tsconfig.sidecar.json && pkg build/util/api.js -c pkg-sidecar.json --target node18 --output generated/etcher-util

> balena-etcher@1.18.13 build:rebuild-mountutils
> cd node_modules/mountutils && npm rebuild

rebuilt dependencies successfully
> pkg@5.8.1
> Warning Cannot find module 'winusb-driver-generator' from '/Users/faridmirzayev/Desktop/Files/Dev/etcher/node_modules/etcher-sdk/build/scanner/adapters'  in /Users/faridmirzayev/Desktop/Files/Dev/etcher/node_modules/etcher-sdk/build/scanner/adapters/driverless.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/drivelist/build/Release/drivelist.node
  %2: path-to-executable/drivelist.node
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/drivelist/scripts/darwin.sh
  %2: path-to-executable/drivelist/darwin.sh
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/drivelist/scripts/linux.sh
  %2: path-to-executable/drivelist/linux.sh
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/drivelist/scripts/win32.bat
  %2: path-to-executable/drivelist/win32.bat
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/drivelist/build/Release/drivelist.node
  %2: path-to-executable/drivelist.node
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/drivelist/scripts/darwin.sh
  %2: path-to-executable/drivelist/darwin.sh
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/drivelist/scripts/linux.sh
  %2: path-to-executable/drivelist/linux.sh
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/drivelist/scripts/win32.bat
  %2: path-to-executable/drivelist/win32.bat

**Comment by lurch** [comment]
Does https://github.com/balena-io/etcher/blob/master/docs/PUBLISHING.md#packaging answer your question?

Etcher has gone through a big build-infrastructure change recently (see #4132 ), so any old instructions you find might be out of date.
