### ISSUE TITLE
Balena Etcher broke my second USB stick(Ventoy) that wasn't being used

### ISSUE THREAD

**Issue by DFelipehDEV** [balena-io/etcher#4155]
- **Etcher version:** 1.18.11
- **Operating system and architecture:** Windows 11 64 Bits
- **Image flashed:** MX Linux
- **What do you think should have happened:** Balena Etcher should have formatted the USB stick i selected
- **What happened:** Balena Etcher formatted both my USB sticks, one of those was a ventoy usb. The ventoy one is now using 8.74 mb and the rest 30 gigs are not allocated. All files were lost
- **Do you see any meaningful error information in the DevTools?** No

![imagem](https://github.com/balena-io/etcher/assets/56834989/18ff7101-7e3a-48da-abde-24da7876c289)

**Comment by aethernet** [comment]
Unless you have a repro, i'll consider that you checked both devices in the selection screen.
