### ISSUE TITLE
gconf packages no longer needed

### ISSUE THREAD

**Issue by QuentiumYT** [balena-io/etcher#4157]
- **Etcher version:** 1.19.3
- **Operating system and architecture:** Ubuntu mantic 23.10

Depends: gconf-service but it is not installable
Depends: gconf2 but it is not installable
Depends: libgconf-2-4 but it is not installable
Depends: libgdk-pixbuf2.0-0 but it is not installed

Related to https://github.com/mattermost/desktop/issues/2853

**Comment by lurch** [comment]
See also https://github.com/balena-io/etcher/issues?q=is%3Aissue+is%3Aopen+gconf
