### ISSUE TITLE
Balena v1.19.3 doesnt start.

### ISSUE THREAD

**Issue by Ntemis** [balena-io/etcher#4159]
Setting up balena-etcher (1.19.3) ...
chmod: cannot access '/opt/balenaEtcher/chrome-sandbox': No such file or directory
Error in file "/usr/share/applications/xreader.desktop": "application/x-ext-cbzapplication/oxps" is an invalid MIME type ("application/x-ext-cbzapplication/oxps" contains an invalid character in the subtype)
ubuntu 22.04

**Comment by lurch** [comment]
Looks like you've run into https://github.com/linuxmint/xreader/issues/632 which isn't anything to do with Etcher?

**Comment by aethernet** [comment]
@Ntemis Can you give more context? OS, arch, ...

**Comment by Ntemis** [comment]
After a reboot it comes up, closing
