### ISSUE TITLE
Malwarebytes is flagging balenaetcher as malware

### ISSUE THREAD

**Issue by nascentt** [balena-io/etcher#4164]
- **Etcher version:1.18.13.0** 
- **Operating system and architecture:Windows 10** 
- **Image flashed:** 
- **What do you think should have happened:** 
- **What happened:malwarebytes is flagging balena etcher as malware 'Malware.AI.3253061021'**
- **Do you see any meaningful error information in the DevTools?**

**Comment by pelicanmedia** [comment]
Same here. Both quarantined.
<img width="1098" alt="Screenshot 2024-01-21 at 16 19 46" src="https://github.com/balena-io/etcher/assets/9213582/b612676c-8aaf-4f3e-b891-d7874c3f6180">

**Comment by aethernet** [comment]
Looks like false positive found by their AI system.

Can you check if it also happens with 1.19.3 (pre-release)?

**Comment by pelicanmedia** [comment]
There is no virus warning after a new scan, but I get the below when installing 1.19.3...
<img width="608" alt="Screenshot 2024-01-24 at 10 09 22" src="https://github.com/balena-io/etcher/assets/9213582/a3726978-673a-4cb1-8276-0290d531e867">

**Comment by aethernet** [comment]
I have been able to reproduced. This is actually a bug in the installer and not in etcher itself. If you let it go, it will eventually install and launch etcher.

I'm currently trying to find the cause.

**Comment by Olman62** [comment]
The application made my 2 flash drives as write-protected and I cannot format them.
