### ISSUE TITLE
Downloading the macOS version from your website gives me an appimage file that can not be opened.

### ISSUE THREAD

**Issue by b-hayes** [balena-io/etcher#4171]
- **Etcher version:** 
- latest
- **Operating system and architecture:** 
- macos sonoma
- **Image flashed:** 
- na
- **What do you think should have happened:** 
- I should probably receive a file that works on macos given that is the version of the app I am atetmpting to download form you.
- **What happened:**
- I get some trange file that cant be used on macos
- **Do you see any meaningful error information in the DevTools?** 
- no

**Comment by dfunckt** [comment]
Where are you trying to download etcher from? Can you share a link to that website?

As it is, our website shows a list of options and the user gets to pick what to download based on their platform and preference. Which leads me to believe you either try to download etcher from one of the many fake sites. or just select the wrong platform option.

**Comment by lurch** [comment]
(AFAIK, AppImage files are only used on Linux and not macOS or Windows?)

**Comment by b-hayes** [comment]
It was coming from the official websites macos x64 link. Seems I get a dmg file when i try it now tho so 🤷🏼‍♂️

**Comment by mullapuh** [comment]
Dont think this is solved. Just tried to download and result is the same

**Comment by lurch** [comment]
Do the downloads [here](https://github.com/balena-io/etcher/releases) work properly?

**Comment by wlegate** [comment]
It's not working for me either on MacOS 14.4.X @lurch… it downloads & seemingly installs fine, but no interface actually appears when you open the app. I downloaded it two separate times from the official MacOS install link.

**Comment by b-hayes** [comment]
@wlegate sounds like a different problem. I wasn't getting an installable file it was for the wrong platform entirely. You should probably open a new issue.
