### ISSUE TITLE
Etcher pro turns off automatically while flashing and the issue is resolved only after Turning OFF the incoming powersupply and Turning ON again.

### ISSUE THREAD

**Issue by Kamalakannan4832** [balena-io/etcher#4190]
- **Etcher version:*1.14.3* 
- **Operating system and architecture:*etcher pro * 
- **Image flashed:*16GB* 
- **What do you think should have happened:** <the etcher pro is unresponsive >
- **What happened:* The etcher pro is not responding after sometime *
- **Do you see any meaningful error information in the DevTools?*No*

**Comment by Kamalakannan4832** [comment]
if anyone faced this issue, then guide me to solve it

**Comment by aethernet** [comment]
Can you contact etcher-pro support for this? We're better equipped to help over there.

@Kamalakannan4832
