### ISSUE TITLE
Crashing when using larger destination drives, anything below 250 that was tested works, anything that or higher crashes

### ISSUE THREAD

**Issue by TheSashmo** [balena-io/etcher#4198]
- **Etcher version:**  
- 1.19.5
- **Operating system and architecture:**  
- Mac Sonoma 114.4.1
- **Image flashed:** 
- could not flash
- **What do you think should have happened:** 
- When sleecting destination drives that are larger than 250 causes the app to lock up and loose ability to click anything and all icond disaaper and I have to force close the application
- **What happened:**
- **Do you see any meaningful error information in the DevTools?** 

https://capture.dropbox.com/Cei9RZL12j9oEFQi  here is what the developer window shows when it crashes

**Comment by aethernet** [comment]
I think i know the issue and it should be fixed by https://github.com/balena-io/etcher/pull/4208
