### ISSUE TITLE
"A JavaScript Error Occured in the Main Process" Error on startup

### ISSUE THREAD

**Issue by SemihGuner** [balena-io/etcher#4201]
- **Etcher version:** 1.19.5
- **Operating system and architecture:** Windows 10 x64
- **Image flashed:** Nobara Official.
- **What do you think should have happened:**  I just opened the app, and the error popped out. 
- **What happened:** The error says that there's "A JavaScript Error Occured in the Main Process". When I clicked OK, the app continued to run normally. I don't know if it broke anything inside the app, though. 
- **Do you see any meaningful error information in the DevTools?**  No, I currently don't.
![Ekran görüntüsü 2024-04-10 204615](https://github.com/balena-io/etcher/assets/78794302/3f01d841-db06-4b56-b361-e9842b83985c)

**Comment by Alex313031** [comment]
@SemihGuner Yup. They need to fix it. I have fixed it in my fork, by simply editing one line. They didn't do import correctly.

**Comment by aethernet** [comment]
@Alex313031 what was the fix?

**Comment by aethernet** [comment]
nvm found it :)
https://github.com/balena-io/etcher/pull/4209
