### ISSUE TITLE
Broke two USB flashes

### ISSUE THREAD

**Issue by 411A** [balena-io/etcher#4218]
- **Etcher version:** 1.18.11
- **Operating system and architecture:** Windows 11
- **Image flashed:** Ubuntu 22.04.6
- **What do you think should have happened:** Just don't break USB, or give us some precautions on how to not break it!
- **What happened:** Read-only USB flash, can't format or repair from cmd

I tried using Balena Etcher on two USB flash drives to make a bootable image of Ubuntu 22.04.6. The first attempt was successful, but the BIOS never recognized the drive. I then realized it's became an empty read-only drive.
The second attempt was also successful, and I was able to install Ubuntu. However, when I tried to format the USB flash drive to reclaim it, I discovered it had become read-only again. I attempted various command-line solutions, but they were unsuccessful.
With the second flash drive, I suspect the read-only issue occurred because Ubuntu prompted me to remove the USB without providing a safe eject option right after successful installation. The cause of the first drive's issue remains unclear...

**Comment by aethernet** [comment]
please check [the doc](https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives)
