### ISSUE TITLE
Add arm64 architecture support for linux

### ISSUE THREAD

**Issue by Tianming-Wu** [balena-io/etcher#4220]
- **Operating system and architecture:**  Ubuntu 24.04 aem64 Raspberry Pi 4

Actually, this is a suggestion.
Since I have limited access to some of the websites in the China mainland, I can only post it here.

I found that the Linux version does not contain a version running on arm64. Can you add it? I need it to flash images on my raspberry pi.

I've carefully examined the relase page and I'm sure I haven't seen an available one. If it is **just unseen**, please make it easier to be found.

Or, how to compile it? There wasn't any information about it. I've downloaded the source, but I haven't figured out how to compile it.

**Comment by aethernet** [comment]
You can certainly build etcher for linux/arm64, I suggest you look at electron-forge requirements. I don't have the bandwidth to add another build target in the short term.

If you can use a command line, an alternative I can recommend is using [balena-cli](https://github.com/balena-io/balena-cli/releases/tag/v18.2.2) `balena local flash` command. It use the same flashing code as etcher (without the graphical interface).
