### ISSUE TITLE
Cant Flash To USB With Portable Etcher 

### ISSUE THREAD

**Issue by HydraCatYT** [balena-io/etcher#4230]
- **Etcher version: v1.18.11 (PORTABLE)** 
- **Windows 10 (64 bit) (x86):** 
- **Image i tried to flash: archlinux-2024.05.01-x86_64** 
- **What should have happened: Select the image i flashed and then chose a flash drive then flash it**
- **What happened: The application points to non existent files**
- **Do you see any meaningful error information in the DevTools?: No i Dont** 

only workaround is installing etcher then using portable (but that defeats the wole purpose of portable)

**Comment by aethernet** [comment]
won't be fixed sorry, our new packager doesn't support portable for the time being. Might be reintroduced later on...
