### ISSUE TITLE
******

### ISSUE THREAD

**Issue by beatnickgr** [balena-io/etcher#4232]
I copy paste the instructions under this link :

https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64

sudo apt install ./balena-etcher_******_amd64.deb
Reading package lists... Done
E: Unsupported file ./balena-etcher_******_amd64.deb given on commandline

Probably the ****** must be replaced with something else?
Please clarify the instructions.

**Comment by aethernet** [comment]
it should be the file you downloaded those * represents the version

**Comment by Appytoo** [comment]
rubbish unhelpful rubbish. none if it works

**Comment by Appytoo** [comment]
There is no appimage! There is only a link to a download which does not work These people like to waste your time
