### ISSUE TITLE
Unable to download Balena Etcher for MAC OS

### ISSUE THREAD

**Issue by Brianb-ie** [balena-io/etcher#4235]
- **MAC OS:** 
- **MAC:** 
- **No:** 
- **Trying to download Etcher for Mac OS  but not working:** 
- **When downloading the file either directed to another Balena webpage where the 404 error appears or it downloads a .dmg.txt file which contains only the text "not found":**
- **No**

**Comment by drd-dev** [comment]
Same.

**Comment by aethernet** [comment]
Fixed :)

**Comment by Brianb-ie** [comment]
Yes indeed 😊 thank you 




On Thursday, May 30, 2024, 10:57 AM, Edwin Joassart ***@***.***> wrote:




Fixed :)
