### ISSUE TITLE
Portable Etcher for Windows link doesn't work

### ISSUE THREAD

**Issue by peternewman** [balena-io/etcher#4236]
- **Etcher version:** Any
- **Operating system and architecture:** Any
- **Image flashed:** N/A
- **What do you think should have happened:** No link, or link works
- **What happened:** 404
- **Do you see any meaningful error information in the DevTools?** N/A

https://etcher.balena.io/#download-etcher has a broken link for ETCHER FOR WINDOWS (X86|X64) (PORTABLE) to:
https://github.com/balena-io/etcher/releases/download/v1.19.19/balenaEtcher-Portable-1.19.19.exe

Possibly related to #4073 ?

**Comment by afurno-cisco** [comment]
the download button `Etcher for Windows (x86|x64) (Installer)`  took me to a 404 github page

**Comment by aethernet** [comment]
We changed the file naming scheme while switching the build tooling and forget to change that on the marketing website.
It's been fixed last night.

**Comment by peternewman** [comment]
Thanks @aethernet .

This doesn't seem to include a link to https://github.com/balena-io/etcher/releases/download/v1.19.19/balenaEtcher-win32-x64-1.19.19.zip though which seems to be the standalone (no installer) version, just the setup EXE version for Windows.
