### ISSUE TITLE
Error: (0, h.requestMetadata) is not a function

### ISSUE THREAD

**Issue by drsheep404** [balena-io/etcher#4345]
- **Etcher version:** 1.19.x
- **Operating system and architecture:** Debian Bullseye, AppImage
- **Image flashed:** xubuntu-22.04.5-desktop-amd64.iso
- **What do you think should have happened:** Next step, selecting device to flash
- **What happened:** It don't use the iso file due it's issue.

In Version 1.18.11 it works (also AppImage). Both tested with exact same iso.
Top left: 1.19.25 (also older 1.19.x versions don't work)
Bottom right: 1.18.11

![image](https://github.com/user-attachments/assets/02c832f6-c363-4cc3-a733-61b198846546)

**Comment by lurch** [comment]
See #4150
