### ISSUE TITLE
Collect anonymised drive quality related data

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#652]
The scope of this task is to:
- Extend [drivelist](https://github.com/resin-io-modules/drivelist) to detect a drive's model, type, serial, etc for all operating systems.
- Anonymously send drive quality data somewhere, like the speed, if such drive reported validation errors, etc.

**Comment by davidak** [comment]
of course you ask the user before sending his data to others, right?

**Comment by jviotti** [comment]
Hey there @davidak,

We have a setting option to drop-out from analytics, but I agree that we should present a modal to the user on the first run, or something like that.

**Comment by jviotti** [comment]
Closing stale issues
